"""Curated vocabularies for the bounded shadow-pilot validation study (MVP 1F).

Every pilot evaluation and metric identifies the evidence class used. Synthetic or
supplied-snapshot results are NEVER aggregated into a metric presented as live
enterprise performance. All reviewer/outcome/value categories are curated (no
free-form aggregation).
"""
from __future__ import annotations

from enum import Enum


class PilotEvidenceClass(str, Enum):
    LIVE_GITHUB_METADATA = "LIVE_GITHUB_METADATA"
    LIVE_ENTERPRISE_SIGNAL = "LIVE_ENTERPRISE_SIGNAL"
    SUPPLIED_ENTERPRISE_SNAPSHOT = "SUPPLIED_ENTERPRISE_SNAPSHOT"
    HISTORICAL_REPLAY = "HISTORICAL_REPLAY"
    SYNTHETIC_CONTROL = "SYNTHETIC_CONTROL"
    REVIEWER_FEEDBACK = "REVIEWER_FEEDBACK"
    OPERATIONAL_OBSERVATION = "OPERATIONAL_OBSERVATION"


#: Evidence classes that count as *live* enterprise performance evidence.
LIVE_EVIDENCE_CLASSES = frozenset({
    PilotEvidenceClass.LIVE_GITHUB_METADATA,
    PilotEvidenceClass.LIVE_ENTERPRISE_SIGNAL,
})
#: Evidence classes that must never be aggregated into a "live performance" metric.
NON_LIVE_EVIDENCE_CLASSES = frozenset({
    PilotEvidenceClass.SUPPLIED_ENTERPRISE_SNAPSHOT,
    PilotEvidenceClass.HISTORICAL_REPLAY,
    PilotEvidenceClass.SYNTHETIC_CONTROL,
})


class PilotCohort(str, Enum):
    ROUTINE_LOW_RISK = "ROUTINE_LOW_RISK"
    SENSITIVE_CODE_PATH = "SENSITIVE_CODE_PATH"
    AI_GENERATED_OR_AI_ASSISTED = "AI_GENERATED_OR_AI_ASSISTED"
    STALE_HEAD_OR_REVISED_CHANGE = "STALE_HEAD_OR_REVISED_CHANGE"
    MISSING_OR_STALE_EVIDENCE = "MISSING_OR_STALE_EVIDENCE"
    ACTIVE_CHANGE_RESTRICTION = "ACTIVE_CHANGE_RESTRICTION"
    INCIDENT_OR_OPERATIONAL_RISK = "INCIDENT_OR_OPERATIONAL_RISK"
    AUTHORITY_OR_SEPARATION_OF_DUTIES = "AUTHORITY_OR_SEPARATION_OF_DUTIES"
    CONFLICTING_SOURCE_SIGNALS = "CONFLICTING_SOURCE_SIGNALS"
    CONTROL_GROUP = "CONTROL_GROUP"


class ReviewMode(str, Enum):
    BLINDED_INITIAL_THEN_REVEALED = "BLINDED_INITIAL_THEN_REVEALED"
    REVIEW_NOT_BLINDED = "REVIEW_NOT_BLINDED"


class StatusAssessment(str, Enum):
    AGREE = "AGREE"
    TOO_STRICT = "TOO_STRICT"
    TOO_LENIENT = "TOO_LENIENT"
    WRONG_STATUS = "WRONG_STATUS"
    INSUFFICIENT_INFORMATION = "INSUFFICIENT_INFORMATION"


class InterventionAssessment(str, Enum):
    CORRECT_INTERVENTION = "CORRECT_INTERVENTION"
    UNNECESSARY_INTERVENTION = "UNNECESSARY_INTERVENTION"
    MISSING_INTERVENTION = "MISSING_INTERVENTION"
    WRONG_INTERVENTION_TYPE = "WRONG_INTERVENTION_TYPE"
    WRONG_REQUIRED_AUTHORITY = "WRONG_REQUIRED_AUTHORITY"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class RootCause(str, Enum):
    POLICY_CONFIGURATION = "POLICY_CONFIGURATION"
    SOURCE_DATA = "SOURCE_DATA"
    SOURCE_FRESHNESS = "SOURCE_FRESHNESS"
    SOURCE_CONFLICT = "SOURCE_CONFLICT"
    ADAPTER_FAILURE = "ADAPTER_FAILURE"
    CHANGE_IDENTITY = "CHANGE_IDENTITY"
    AUTHORITY_MAPPING = "AUTHORITY_MAPPING"
    INTERVENTION_ROUTING = "INTERVENTION_ROUTING"
    REVIEWER_INTERPRETATION = "REVIEWER_INTERPRETATION"
    PRODUCT_LOGIC = "PRODUCT_LOGIC"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    OTHER_CURATED = "OTHER_CURATED"


class IncrementalValue(str, Enum):
    VALUE_BEYOND_CI_CONFIRMED = "VALUE_BEYOND_CI_CONFIRMED"
    DUPLICATES_EXISTING_CONTROL = "DUPLICATES_EXISTING_CONTROL"
    PARTIALLY_USEFUL = "PARTIALLY_USEFUL"
    NOT_USEFUL = "NOT_USEFUL"
    UNDETERMINED = "UNDETERMINED"


class IncrementalValueLabel(str, Enum):
    EXISTING_CI_ALREADY_CAUGHT = "EXISTING_CI_ALREADY_CAUGHT"
    GITHUB_RULE_ALREADY_CAUGHT = "GITHUB_RULE_ALREADY_CAUGHT"
    MANUAL_REVIEW_ALREADY_CAUGHT = "MANUAL_REVIEW_ALREADY_CAUGHT"
    UGENCE_UNIQUE_SIGNAL = "UGENCE_UNIQUE_SIGNAL"
    UGENCE_EARLIER_DETECTION = "UGENCE_EARLIER_DETECTION"
    UGENCE_BETTER_ROUTING = "UGENCE_BETTER_ROUTING"
    UGENCE_BETTER_AUDITABILITY = "UGENCE_BETTER_AUDITABILITY"
    NO_INCREMENTAL_VALUE = "NO_INCREMENTAL_VALUE"
    UNDETERMINED = "UNDETERMINED"


#: Labels that assert Ugence uniquely detected something — require an evidence ref.
UNIQUE_VALUE_LABELS = frozenset({
    IncrementalValueLabel.UGENCE_UNIQUE_SIGNAL,
    IncrementalValueLabel.UGENCE_EARLIER_DETECTION,
})


class ActualOutcome(str, Enum):
    MERGED_LATER = "MERGED_LATER"
    MERGED_UNCHANGED = "MERGED_UNCHANGED"
    MERGED_AFTER_CODE_CHANGE = "MERGED_AFTER_CODE_CHANGE"
    MERGED_AFTER_EVIDENCE_REFRESH = "MERGED_AFTER_EVIDENCE_REFRESH"
    MERGED_AFTER_REAUTHORIZATION = "MERGED_AFTER_REAUTHORIZATION"
    MERGED_AFTER_HUMAN_EXCEPTION = "MERGED_AFTER_HUMAN_EXCEPTION"
    WAITED_FOR_CHANGE_WINDOW = "WAITED_FOR_CHANGE_WINDOW"
    BLOCKED_BY_EXISTING_CONTROL = "BLOCKED_BY_EXISTING_CONTROL"
    ABANDONED = "ABANDONED"
    REVERTED_LATER = "REVERTED_LATER"
    INCIDENT_ASSOCIATED = "INCIDENT_ASSOCIATED"
    NO_ACTION = "NO_ACTION"
    UNKNOWN = "UNKNOWN"


class AmendmentReason(str, Enum):
    POLICY_DEFECT = "POLICY_DEFECT"
    SOURCE_CONFIGURATION_DEFECT = "SOURCE_CONFIGURATION_DEFECT"
    ADAPTER_DEFECT = "ADAPTER_DEFECT"
    REVIEW_PROTOCOL_DEFECT = "REVIEW_PROTOCOL_DEFECT"
    SECURITY_REQUIREMENT = "SECURITY_REQUIREMENT"
    SCOPE_REDUCTION = "SCOPE_REDUCTION"
    OPERATOR_ERROR = "OPERATOR_ERROR"


class CalibrationAdjustment(str, Enum):
    NO_CHANGE = "NO_CHANGE"
    SIGNAL_REQUIREMENT_CHANGE = "SIGNAL_REQUIREMENT_CHANGE"
    FRESHNESS_WINDOW_CHANGE = "FRESHNESS_WINDOW_CHANGE"
    TRUST_THRESHOLD_CHANGE = "TRUST_THRESHOLD_CHANGE"
    STATUS_PRECEDENCE_CHANGE = "STATUS_PRECEDENCE_CHANGE"
    INTERVENTION_ROUTING_CHANGE = "INTERVENTION_ROUTING_CHANGE"
    AUTHORITY_MAPPING_CHANGE = "AUTHORITY_MAPPING_CHANGE"
    COHORT_SPECIFIC_POLICY = "COHORT_SPECIFIC_POLICY"
    ADAPTER_REPAIR = "ADAPTER_REPAIR"
    MORE_EVIDENCE_REQUIRED = "MORE_EVIDENCE_REQUIRED"


class AdverseCaseKind(str, Enum):
    POSSIBLE_FALSE_CLEAR = "POSSIBLE_FALSE_CLEAR"
    POSSIBLE_UNNECESSARY_BLOCK = "POSSIBLE_UNNECESSARY_BLOCK"
    POSSIBLE_UNNECESSARY_ESCALATE = "POSSIBLE_UNNECESSARY_ESCALATE"
    MISSED_AUTHORITY_REQUIREMENT = "MISSED_AUTHORITY_REQUIREMENT"
    STALE_HEAD_MISS = "STALE_HEAD_MISS"
    SOURCE_CONFLICT_MISHANDLING = "SOURCE_CONFLICT_MISHANDLING"
    POLICY_AMENDMENT_AFTER_START = "POLICY_AMENDMENT_AFTER_START"
    REVIEWER_SAFETY_CONCERN = "REVIEWER_SAFETY_CONCERN"
    INTEGRITY_ANOMALY = "INTEGRITY_ANOMALY"
    CREDENTIAL_OR_BOUNDARY_CONCERN = "CREDENTIAL_OR_BOUNDARY_CONCERN"


class CheckpointKind(str, Enum):
    PRE_PILOT = "PRE_PILOT"
    EARLY_CHECKPOINT = "EARLY_CHECKPOINT"
    MIDPOINT = "MIDPOINT"
    PRE_CLOSEOUT = "PRE_CLOSEOUT"
    FINAL = "FINAL"


class CheckpointRecommendation(str, Enum):
    CONTINUE = "CONTINUE"
    PAUSE = "PAUSE"
    STOP = "STOP"


class PilotReadinessVerdict(str, Enum):
    READY_FOR_ENFORCEMENT_DESIGN = "READY_FOR_ENFORCEMENT_DESIGN"
    PILOT_CALIBRATION_REQUIRED = "PILOT_CALIBRATION_REQUIRED"
    PRODUCT_VALUE_NOT_PROVEN = "PRODUCT_VALUE_NOT_PROVEN"
    INSUFFICIENT_LIVE_EVIDENCE = "INSUFFICIENT_LIVE_EVIDENCE"
    SAFETY_OR_INTEGRITY_BLOCKED = "SAFETY_OR_INTEGRITY_BLOCKED"


class EvidenceStatus(str, Enum):
    IMPLEMENTED = "IMPLEMENTED"
    OFFLINE_VERIFIED = "OFFLINE_VERIFIED"
    LIVE_GITHUB_VERIFIED = "LIVE_GITHUB_VERIFIED"
    LIVE_ENTERPRISE_SIGNAL_VERIFIED = "LIVE_ENTERPRISE_SIGNAL_VERIFIED"
    REVIEWER_FEEDBACK_COLLECTED = "REVIEWER_FEEDBACK_COLLECTED"
    NOT_RUN = "NOT_RUN"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


__all__ = [
    "PilotEvidenceClass", "LIVE_EVIDENCE_CLASSES", "NON_LIVE_EVIDENCE_CLASSES",
    "PilotCohort", "ReviewMode", "StatusAssessment", "InterventionAssessment", "RootCause",
    "IncrementalValue", "IncrementalValueLabel", "UNIQUE_VALUE_LABELS", "ActualOutcome",
    "AmendmentReason", "CalibrationAdjustment", "AdverseCaseKind", "CheckpointKind",
    "CheckpointRecommendation", "PilotReadinessVerdict", "EvidenceStatus",
]
