#-----------------------------------------------------------------------------
# PCAM FPGA Timing Constraints
#-----------------------------------------------------------------------------
# Target: Xilinx Alveo U280
# Tool: Vivado 2023.2+
#
# Clock Domains:
#   - pcie_clk: 250 MHz (from PCIe IP)
#   - user_clk: 250-500 MHz (internal processing)
#-----------------------------------------------------------------------------

#=============================================================================
# Clock Definitions
#=============================================================================

# PCIe reference clock (100 MHz from board)
create_clock -name pcie_refclk -period 10.000 [get_ports pcie_refclk_p]

# PCIe generated clock (250 MHz from PCIe IP)
# Note: This is typically auto-generated by PCIe IP, shown here for reference
create_clock -name pcie_clk -period 4.000 [get_pins u_pcie/inst/gt_top_i/diablo_gt.diablo_gt_phy_wrapper/phy_clk_i/CLK_USERCLK]

# User clock (250 MHz default, can be 500 MHz for high-performance)
create_clock -name user_clk -period 4.000 [get_pins u_mmcm/CLKOUT0]

# Alternative: 500 MHz user clock for maximum performance
# create_clock -name user_clk -period 2.000 [get_pins u_mmcm/CLKOUT0]

#=============================================================================
# Clock Domain Crossing Constraints
#=============================================================================

# PCIe to User clock domain
set_clock_groups -asynchronous \
    -group [get_clocks pcie_clk] \
    -group [get_clocks user_clk]

# False paths for async FIFO synchronizers
set_false_path -from [get_cells -hierarchical -filter {NAME =~ *async_fifo*wr_ptr_gray_reg*}] \
               -to   [get_cells -hierarchical -filter {NAME =~ *async_fifo*wr_ptr_gray_meta_reg*}]

set_false_path -from [get_cells -hierarchical -filter {NAME =~ *async_fifo*rd_ptr_gray_reg*}] \
               -to   [get_cells -hierarchical -filter {NAME =~ *async_fifo*rd_ptr_gray_meta_reg*}]

# Max delay for CDC paths (2 cycles for synchronizer)
set_max_delay -datapath_only 8.000 \
    -from [get_cells -hierarchical -filter {NAME =~ *async_fifo*_meta_reg*}] \
    -to   [get_cells -hierarchical -filter {NAME =~ *async_fifo*_sync_reg*}]

#=============================================================================
# Input/Output Timing
#=============================================================================

# PCIe interface timing (handled by PCIe IP constraints)
# These are typically included from the IP's XDC file

# Debug signals (relaxed timing)
set_output_delay -clock user_clk -max 2.000 [get_ports debug_status[*]]
set_output_delay -clock user_clk -min 0.000 [get_ports debug_status[*]]

#=============================================================================
# Critical Path Constraints
#=============================================================================

# Top-K sorting network - pipeline register insertion points
set_max_delay 3.500 \
    -from [get_cells -hierarchical -filter {NAME =~ *topk_network*stage_data_reg[*]*}] \
    -to   [get_cells -hierarchical -filter {NAME =~ *topk_network*stage_data_reg[*]*}]

# Bank memory access paths
set_max_delay 3.500 \
    -from [get_cells -hierarchical -filter {NAME =~ *bank_array*bank_rd_addr_reg*}] \
    -to   [get_cells -hierarchical -filter {NAME =~ *bank_mem*mem_reg*}]

# Score update arithmetic
set_max_delay 3.500 \
    -from [get_cells -hierarchical -filter {NAME =~ *score_update*term*_reg*}] \
    -to   [get_cells -hierarchical -filter {NAME =~ *score_update*updated_score_reg*}]

#=============================================================================
# Physical Constraints
#=============================================================================

# BRAM placement - keep banks close together
create_pblock pblock_bank_array
add_cells_to_pblock [get_pblocks pblock_bank_array] [get_cells -hierarchical -filter {NAME =~ *bank_array*}]
resize_pblock pblock_bank_array -add {SLICE_X0Y0:SLICE_X100Y200 RAMB36_X0Y0:RAMB36_X10Y40}

# Top-K network placement - spread across fabric for routing
create_pblock pblock_topk
add_cells_to_pblock [get_pblocks pblock_topk] [get_cells -hierarchical -filter {NAME =~ *topk_network*}]
resize_pblock pblock_topk -add {SLICE_X100Y0:SLICE_X200Y200}

# PCIe endpoint - near PCIe hard block
create_pblock pblock_pcie
add_cells_to_pblock [get_pblocks pblock_pcie] [get_cells -hierarchical -filter {NAME =~ *pcie_endpoint*}]
# Location depends on board - U280 PCIe is in SLR0

#=============================================================================
# Multi-Cycle Paths
#=============================================================================

# Decay engine operates on idle cycles - relaxed timing
set_multicycle_path 2 -setup \
    -from [get_cells -hierarchical -filter {NAME =~ *decay_engine*current_*_reg*}] \
    -to   [get_cells -hierarchical -filter {NAME =~ *decay_engine*bank_*_reg*}]

set_multicycle_path 1 -hold \
    -from [get_cells -hierarchical -filter {NAME =~ *decay_engine*current_*_reg*}] \
    -to   [get_cells -hierarchical -filter {NAME =~ *decay_engine*bank_*_reg*}]

# Update coalescer CAM lookup (can be multi-cycle if needed)
# set_multicycle_path 2 -setup \
#     -from [get_cells -hierarchical -filter {NAME =~ *update_coalescer*buffer*}] \
#     -to   [get_cells -hierarchical -filter {NAME =~ *update_coalescer*cam_match*}]

#=============================================================================
# False Paths
#=============================================================================

# Reset synchronizer
set_false_path -from [get_ports rst_n]

# Configuration registers (written once, read many)
set_false_path -from [get_cells -hierarchical -filter {NAME =~ *csr_bank*config_reg*}]

# Debug/status registers
set_false_path -to [get_cells -hierarchical -filter {NAME =~ *perf_counters*}]

#=============================================================================
# SLR Crossing Constraints (for Alveo U280 - 3 SLRs)
#=============================================================================

# Constrain SLR crossing paths
# PCIe is in SLR0, PCAM core in SLR1, memory controllers in SLR2

# set_max_delay 4.000 -datapath_only \
#     -from [get_cells -hierarchical -filter {NAME =~ *pcie_endpoint*}] \
#     -to   [get_cells -hierarchical -filter {NAME =~ *pcam_core*}]

# Use Laguna registers for SLR crossing
# set_property USER_SLR_ASSIGNMENT SLR1 [get_cells -hierarchical -filter {NAME =~ *pcam_core*}]

#=============================================================================
# Power Optimization
#=============================================================================

# Clock gating enable
set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets user_clk]

# Block RAM power optimization
set_property RAM_STYLE BLOCK [get_cells -hierarchical -filter {NAME =~ *bank_mem*mem_reg*}]

#=============================================================================
# Debug
#=============================================================================

# Mark nets for debug probing (optional, comment out for production)
# set_property MARK_DEBUG true [get_nets {pcam_top/state[*]}]
# set_property MARK_DEBUG true [get_nets {pcam_top/bank_busy[*]}]
# set_property MARK_DEBUG true [get_nets {pcam_top/topk_out_valid}]

#=============================================================================
# Timing Exceptions Summary
#=============================================================================
#
# Expected WNS (Worst Negative Slack) targets:
#   - pcie_clk domain: > 0.500 ns
#   - user_clk domain: > 0.200 ns
#   - CDC paths: N/A (false paths or set_max_delay)
#
# If timing fails:
#   1. Enable pipeline registers in topk_network (PIPELINE_STAGES parameter)
#   2. Reduce user_clk to 250 MHz
#   3. Use placement constraints to reduce routing congestion
#   4. Enable physical optimization (phys_opt_design)
#=============================================================================
