"""The closed set of validation finding codes.

Codes are stable identifiers, not messages. A consumer keys on the code; the
message is prose that may be reworded. Every code is listed here so that the set
is reviewable in one place and so a test can assert no code is emitted that was
never declared.
"""

from __future__ import annotations

# -- schema layer ---------------------------------------------------------
SCHEMA_VERSION_MISSING = "AC_SCHEMA_VERSION_MISSING"
SCHEMA_VERSION_UNRECOGNIZED = "AC_SCHEMA_VERSION_UNRECOGNIZED"
SCHEMA_VERSION_RETIRED = "AC_SCHEMA_VERSION_RETIRED"
SCHEMA_VERSION_WRONG_KIND = "AC_SCHEMA_VERSION_WRONG_KIND"
DRAFT_IS_NOT_A_CONSTITUTION = "AC_DRAFT_IS_NOT_A_CONSTITUTION"
SCHEMA_STRUCTURE_INVALID = "AC_SCHEMA_STRUCTURE_INVALID"
PAYLOAD_NOT_A_MAPPING = "AC_PAYLOAD_NOT_A_MAPPING"

# -- mandatory fields -----------------------------------------------------
MANDATORY_FIELD_MISSING = "AC_MANDATORY_FIELD_MISSING"
MANDATORY_FIELD_AMBIGUOUS = "AC_MANDATORY_FIELD_AMBIGUOUS"

# -- digests --------------------------------------------------------------
DIGEST_ABSENT = "AC_DIGEST_ABSENT"
DIGEST_MALFORMED = "AC_DIGEST_MALFORMED"
DIGEST_MISMATCH = "AC_DIGEST_MISMATCH"

# -- capability requirements ---------------------------------------------
REQUIREMENT_ID_AMBIGUOUS = "AC_REQUIREMENT_ID_AMBIGUOUS"
REQUIREMENT_CONDITION_MISSING = "AC_REQUIREMENT_CONDITION_MISSING"
REQUIREMENT_CONDITION_UNEXPECTED = "AC_REQUIREMENT_CONDITION_UNEXPECTED"
REQUIREMENT_CONTRADICTORY = "AC_REQUIREMENT_CONTRADICTORY"
REQUIREMENT_UNRESOLVABLE = "AC_REQUIREMENT_UNRESOLVABLE"

# -- constitution ---------------------------------------------------------
SELF_RATIFICATION = "AC_SELF_RATIFICATION"
ARTIFACT_VERSION_MALFORMED = "AC_ARTIFACT_VERSION_MALFORMED"
PREDECESSOR_SELF_REFERENCE = "AC_PREDECESSOR_SELF_REFERENCE"
SUCCESSION_LINEAGE_MISMATCH = "AC_SUCCESSION_LINEAGE_MISMATCH"
SUCCESSION_VERSION_NOT_BUMPED = "AC_SUCCESSION_VERSION_NOT_BUMPED"
SUCCESSION_NO_MATERIAL_CHANGE = "AC_SUCCESSION_NO_MATERIAL_CHANGE"
SUCCESSION_VERSION_UNORDERABLE = "AC_SUCCESSION_VERSION_UNORDERABLE"
OBLIGATION_CONTRADICTION = "AC_OBLIGATION_CONTRADICTION"

# -- developer implementation contract -----------------------------------
CONTRACT_CONTRADICTORY_BEHAVIOUR = "AC_CONTRACT_CONTRADICTORY_BEHAVIOUR"
CONTRACT_NO_OBLIGATIONS = "AC_CONTRACT_NO_OBLIGATIONS"

# -- conformance subject --------------------------------------------------
SUBJECT_ENTRY_AMBIGUOUS = "AC_SUBJECT_ENTRY_AMBIGUOUS"

#: Every code this build can emit. Gated by tests/contract/test_finding_codes.py.
ALL_CODES = frozenset(
    {
        SCHEMA_VERSION_MISSING,
        SCHEMA_VERSION_UNRECOGNIZED,
        SCHEMA_VERSION_RETIRED,
        SCHEMA_VERSION_WRONG_KIND,
        DRAFT_IS_NOT_A_CONSTITUTION,
        SCHEMA_STRUCTURE_INVALID,
        PAYLOAD_NOT_A_MAPPING,
        MANDATORY_FIELD_MISSING,
        MANDATORY_FIELD_AMBIGUOUS,
        DIGEST_ABSENT,
        DIGEST_MALFORMED,
        DIGEST_MISMATCH,
        REQUIREMENT_ID_AMBIGUOUS,
        REQUIREMENT_CONDITION_MISSING,
        REQUIREMENT_CONDITION_UNEXPECTED,
        REQUIREMENT_CONTRADICTORY,
        REQUIREMENT_UNRESOLVABLE,
        SELF_RATIFICATION,
        ARTIFACT_VERSION_MALFORMED,
        PREDECESSOR_SELF_REFERENCE,
        SUCCESSION_LINEAGE_MISMATCH,
        SUCCESSION_VERSION_NOT_BUMPED,
        SUCCESSION_NO_MATERIAL_CHANGE,
        SUCCESSION_VERSION_UNORDERABLE,
        OBLIGATION_CONTRADICTION,
        CONTRACT_CONTRADICTORY_BEHAVIOUR,
        CONTRACT_NO_OBLIGATIONS,
        SUBJECT_ENTRY_AMBIGUOUS,
    }
)
