"""initial phase A/B schema

Revision ID: dfd7ee81e09c
Revises: 
Create Date: 2026-08-04 14:03:07.474637
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'dfd7ee81e09c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couples',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('unpaired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'UNPAIRED')", name='ck_status_enum'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('credential_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'DEACTIVATED', 'DELETION_PENDING', 'DELETED')", name='ck_status_enum'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('resource_type', sa.String(length=48), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=True),
    sa.Column('couple_id', sa.Uuid(), nullable=True),
    sa.Column('outcome', sa.String(length=8), nullable=False),
    sa.Column('denial_reason_code', sa.String(length=48), nullable=True),
    sa.Column('consent_event_id', sa.Uuid(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("outcome IN ('ALLOW', 'DENY')", name='ck_outcome_enum'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_couple_id'), 'audit_events', ['couple_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_table('birth_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.Uuid(), nullable=True),
    sa.Column('preferred_name', sa.String(length=120), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('birth_time_local', sa.Time(), nullable=True),
    sa.Column('birth_time_precision', sa.String(length=16), nullable=False),
    sa.Column('ambiguity_resolution', sa.String(length=8), nullable=True),
    sa.Column('birthplace_label', sa.String(length=256), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('iana_timezone', sa.String(length=64), nullable=False),
    sa.Column('utc_birth_instant', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("birth_time_precision IN ('EXACT', 'APPROXIMATE', 'UNKNOWN')", name='ck_birth_time_precision_enum'),
    sa.CheckConstraint('input_confidence >= 0 AND input_confidence <= 1', name='ck_bp_conf'),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_bp_lat'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_bp_lon'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['birth_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'version', name='uq_birth_profile_user_version')
    )
    op.create_index(op.f('ix_birth_profiles_user_id'), 'birth_profiles', ['user_id'], unique=False)
    op.create_table('consent_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('couple_id', sa.Uuid(), nullable=False),
    sa.Column('granter_user_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('source_scope', sa.String(length=16), nullable=False),
    sa.Column('artifact_type', sa.String(length=48), nullable=False),
    sa.Column('bounded_summary', sa.String(length=2000), nullable=False),
    sa.Column('purpose', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("event_type IN ('REQUEST', 'GRANT', 'REVOKE', 'EXPIRE')", name='ck_event_type_enum'),
    sa.CheckConstraint("source_scope IN ('PRIVATE_A', 'PRIVATE_B', 'SHARED')", name='ck_source_scope_enum'),
    sa.CheckConstraint("state IN ('REQUESTED', 'GRANTED', 'REVOKED', 'EXPIRED')", name='ck_state_enum'),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granter_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_events_couple_id'), 'consent_events', ['couple_id'], unique=False)
    op.create_table('couple_invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inviter_user_id', sa.Uuid(), nullable=False),
    sa.Column('couple_id', sa.Uuid(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('accepted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED')", name='ck_status_enum'),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_invitation_token')
    )
    op.create_index(op.f('ix_couple_invitations_inviter_user_id'), 'couple_invitations', ['inviter_user_id'], unique=False)
    op.create_table('couple_memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('couple_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scope_slot', sa.String(length=1), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("scope_slot IN ('A', 'B')", name='ck_scope_slot_enum'),
    sa.CheckConstraint("status IN ('ACTIVE', 'REVOKED')", name='ck_status_enum'),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('couple_id', 'scope_slot', name='uq_membership_couple_slot'),
    sa.UniqueConstraint('couple_id', 'user_id', name='uq_membership_couple_user')
    )
    op.create_index(op.f('ix_couple_memberships_couple_id'), 'couple_memberships', ['couple_id'], unique=False)
    op.create_index(op.f('ix_couple_memberships_user_id'), 'couple_memberships', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('rotated_from_id', sa.Uuid(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['rotated_from_id'], ['user_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash', name='uq_sessions_refresh_hash')
    )
    op.create_index('ix_sessions_user_active', 'user_sessions', ['user_id', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('natal_chart_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('birth_profile_id', sa.Uuid(), nullable=False),
    sa.Column('birth_profile_version', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.String(length=32), nullable=False),
    sa.Column('provider_version', sa.String(length=64), nullable=False),
    sa.Column('ephemeris_mode', sa.String(length=32), nullable=False),
    sa.Column('ayanamsa', sa.String(length=32), nullable=False),
    sa.Column('julian_day', sa.Float(), nullable=False),
    sa.Column('moon_longitude', sa.Float(), nullable=False),
    sa.Column('rashi_index', sa.Integer(), nullable=False),
    sa.Column('rashi_name', sa.String(length=24), nullable=False),
    sa.Column('nakshatra_index', sa.Integer(), nullable=False),
    sa.Column('nakshatra_name', sa.String(length=32), nullable=False),
    sa.Column('pada', sa.Integer(), nullable=False),
    sa.Column('numerical_precision_class', sa.String(length=24), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('fallback_reason', sa.String(length=128), nullable=True),
    sa.Column('input_confidence', sa.Float(), nullable=False),
    sa.Column('time_assumption', sa.String(length=48), nullable=True),
    sa.Column('calculation_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint('moon_longitude >= 0 AND moon_longitude < 360', name='ck_natal_lon'),
    sa.CheckConstraint('nakshatra_index >= 0 AND nakshatra_index <= 26', name='ck_natal_nak'),
    sa.CheckConstraint('pada >= 1 AND pada <= 4', name='ck_natal_pada'),
    sa.CheckConstraint('rashi_index >= 0 AND rashi_index <= 11', name='ck_natal_rashi'),
    sa.ForeignKeyConstraint(['birth_profile_id'], ['birth_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('birth_profile_id', 'birth_profile_version', 'provider_id', 'provider_version', 'ephemeris_mode', 'ayanamsa', name='uq_natal_version_tuple')
    )
    op.create_index(op.f('ix_natal_chart_snapshots_birth_profile_id'), 'natal_chart_snapshots', ['birth_profile_id'], unique=False)
    op.create_index(op.f('ix_natal_chart_snapshots_user_id'), 'natal_chart_snapshots', ['user_id'], unique=False)
    op.create_table('shared_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('couple_id', sa.Uuid(), nullable=False),
    sa.Column('consent_event_id', sa.Uuid(), nullable=False),
    sa.Column('source_scope', sa.String(length=16), nullable=False),
    sa.Column('artifact_type', sa.String(length=48), nullable=False),
    sa.Column('payload_snapshot', sa.Text(), nullable=False),
    sa.Column('provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("source_scope IN ('PRIVATE_A', 'PRIVATE_B', 'SHARED')", name='ck_source_scope_enum'),
    sa.ForeignKeyConstraint(['consent_event_id'], ['consent_events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_artifacts_couple_id'), 'shared_artifacts', ['couple_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_artifacts_couple_id'), table_name='shared_artifacts')
    op.drop_table('shared_artifacts')
    op.drop_index(op.f('ix_natal_chart_snapshots_user_id'), table_name='natal_chart_snapshots')
    op.drop_index(op.f('ix_natal_chart_snapshots_birth_profile_id'), table_name='natal_chart_snapshots')
    op.drop_table('natal_chart_snapshots')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index('ix_sessions_user_active', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_couple_memberships_user_id'), table_name='couple_memberships')
    op.drop_index(op.f('ix_couple_memberships_couple_id'), table_name='couple_memberships')
    op.drop_table('couple_memberships')
    op.drop_index(op.f('ix_couple_invitations_inviter_user_id'), table_name='couple_invitations')
    op.drop_table('couple_invitations')
    op.drop_index(op.f('ix_consent_events_couple_id'), table_name='consent_events')
    op.drop_table('consent_events')
    op.drop_index(op.f('ix_birth_profiles_user_id'), table_name='birth_profiles')
    op.drop_table('birth_profiles')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_couple_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('users')
    op.drop_table('couples')
    # ### end Alembic commands ###
