"""Error and refusal vocabularies (specification §11).

``ContractErrorCode`` is raised by constructors, wrapped in ``ContractError``.
``RefusalCode`` is returned by the comparison engine inside ``Refusal`` values;
the engine never raises on a governed input, it refuses.
"""

from __future__ import annotations

from enum import Enum


class ContractErrorCode(str, Enum):
    REF_BLANK_FIELD = "REF_BLANK_FIELD"
    DIGEST_MALFORMED = "DIGEST_MALFORMED"
    CATALOG_DUPLICATE_ENTRY = "CATALOG_DUPLICATE_ENTRY"
    CATALOG_UNSORTED = "CATALOG_UNSORTED"
    SIGNAL_TOKEN_UNKNOWN = "SIGNAL_TOKEN_UNKNOWN"
    SCALAR_LABEL_FIELD_PRESENT = "SCALAR_LABEL_FIELD_PRESENT"
    STATUS_DECLARED_NOT_DERIVED = "STATUS_DECLARED_NOT_DERIVED"
    REVERSIBILITY_UNDETERMINED_ON_CLASS = "REVERSIBILITY_UNDETERMINED_ON_CLASS"
    ADMISSION_REF_REQUIRED = "ADMISSION_REF_REQUIRED"
    DIMENSIONS_EMPTY = "DIMENSIONS_EMPTY"
    DIMENSIONS_UNSORTED = "DIMENSIONS_UNSORTED"
    TELEMETRY_INVARIANT = "TELEMETRY_INVARIANT"
    ARTIFACT_KIND_UNKNOWN = "ARTIFACT_KIND_UNKNOWN"
    DECIMAL_UNPARSEABLE = "DECIMAL_UNPARSEABLE"
    DATETIME_NAIVE = "DATETIME_NAIVE"
    LINEAGE_SELF_REFERENCE = "LINEAGE_SELF_REFERENCE"
    EVIDENCE_AXIS_SET_BY_PRODUCER = "EVIDENCE_AXIS_SET_BY_PRODUCER"
    ASSESSOR_ENGINE_MISMATCH = "ASSESSOR_ENGINE_MISMATCH"


class RefusalCode(str, Enum):
    UNSUPPORTED_SCHEMA_VERSION = "UNSUPPORTED_SCHEMA_VERSION"
    UNSUPPORTED_COMPARATOR = "UNSUPPORTED_COMPARATOR"
    UNIT_MISMATCH = "UNIT_MISMATCH"
    SCALE_UNSUPPORTED = "SCALE_UNSUPPORTED"
    AGGREGATION_UNDECLARED = "AGGREGATION_UNDECLARED"
    RESOURCE_AGGREGATION_UNDECLARED = "RESOURCE_AGGREGATION_UNDECLARED"
    DIMENSION_UNAVAILABLE = "DIMENSION_UNAVAILABLE"
    TASK_CLASS_MISMATCH = "TASK_CLASS_MISMATCH"
    BASELINE_ABSENT = "BASELINE_ABSENT"
    METHOD_RECORDS_ABSENT = "METHOD_RECORDS_ABSENT"
    QUALITY_RESULT_ABSENT = "QUALITY_RESULT_ABSENT"
    QUALITY_CLAIM_NOT_INDEPENDENT = "QUALITY_CLAIM_NOT_INDEPENDENT"
    THRESHOLD_UNRESOLVABLE = "THRESHOLD_UNRESOLVABLE"
    THRESHOLD_ONLY_NOT_ADMITTED = "THRESHOLD_ONLY_NOT_ADMITTED"
    LINEAGE_UNRESOLVED = "LINEAGE_UNRESOLVED"
    SELF_ATTESTATION = "SELF_ATTESTATION"
    SELF_VERIFICATION = "SELF_VERIFICATION"
    VERIFICATION_WITHOUT_ATTESTATION = "VERIFICATION_WITHOUT_ATTESTATION"
    ENVELOPE_ORPHAN = "ENVELOPE_ORPHAN"
    CANDIDATES_EMPTY = "CANDIDATES_EMPTY"


class ContractError(ValueError):
    """A constructor refusal. ``code`` names the §11 rule that fired."""

    def __init__(self, code: ContractErrorCode, detail: str = "") -> None:
        if not isinstance(code, ContractErrorCode):
            raise TypeError("ContractError requires a ContractErrorCode")
        self.code = code
        self.detail = detail
        super().__init__(f"{code.value}: {detail}" if detail else code.value)


__all__ = ["ContractErrorCode", "RefusalCode", "ContractError"]
