"""Why no dispatch happened. A denial by the executor is a record, not a refusal."""

from __future__ import annotations

from enum import Enum

__all__ = ["DispatchRefusal"]


class DispatchRefusal(str, Enum):
    GRANT_NOT_FOUND = "GRANT_NOT_FOUND"
    GRANT_EXPIRED = "GRANT_EXPIRED"
    GRANT_NOT_REDERIVED = "GRANT_NOT_REDERIVED"
    AUTHORIZATION_NOT_FOUND = "AUTHORIZATION_NOT_FOUND"
    AUTHORIZATION_NOT_AUTHORIZED = "AUTHORIZATION_NOT_AUTHORIZED"
    ENVELOPE_NOT_FOUND = "ENVELOPE_NOT_FOUND"
    RESERVATION_NOT_FOUND = "RESERVATION_NOT_FOUND"
    RESERVATION_NOT_RESERVED = "RESERVATION_NOT_RESERVED"
    LEASE_EXPIRED = "LEASE_EXPIRED"
    TARGET_SCOPE_MISMATCH = "TARGET_SCOPE_MISMATCH"
    TARGET_NOT_ADDRESSABLE = "TARGET_NOT_ADDRESSABLE"
    ACTION_NOT_DISPATCHABLE = "ACTION_NOT_DISPATCHABLE"
    EXECUTOR_INTEGRITY = "EXECUTOR_INTEGRITY"
