#!/usr/bin/env python3
"""
Authored hidden cases — PRIVATE source of truth (evaluation-side only).

This module holds BOTH the executable content and the private annotations for
each hidden case. It must never be imported by a resolver. The public loaders
(`corpus.py` / `annotations.py`) split it into a resolver-facing view (question +
documents only, behind an opaque content-hash id) and an evaluation-facing view
(gold graph, governance explanation, packet expectation, justification,
confidence, ambiguity, difficulty, capability).

Design rules honoured here:
  * internal `ref` names are NEVER exposed (the public id is a content hash).
  * document ids / citations / text carry NO capability, difficulty, or answer
    labels — they read as ordinary contract text.
  * cases are authored across capabilities, difficulty 1–5, many variation
    dimensions, and negative controls.

ALL DATA IS SYNTHETIC.
"""

from __future__ import annotations


def D(doc_id, citation, order, text):
    return {"doc_id": doc_id, "citation": citation, "order": order, "text": text}


AUTHORED = [
    # ---------- Level 1 — single relationship ---------------------------------
    {
        "ref": "l1_version_supersession_passive",
        "question": "May the customer exit the agreement, and on what notice?",
        "documents": [
            D("a", "Master Terms cl. 5.2 p.4", 0,
              "The customer shall not exit the engagement at will."),
            D("b", "Amending Deed 2 cl. 1 p.31", 1,
              "Clause 5.2 is hereby rescinded and substituted; the customer may exit at will on giving thirty days written notice."),
        ],
        "capability": ["version_supersession"], "difficulty": 1,
        "variation": ["voice", "wording", "entity_names"],
        "gold_nodes": {"Master Terms cl. 5.2 p.4": "Clause", "Amending Deed 2 cl. 1 p.31": "Clause"},
        "gold_edges": [("Amending Deed 2 cl. 1 p.31", "supersedes", "Master Terms cl. 5.2 p.4")],
        "governing": ["Amending Deed 2 cl. 1 p.31"], "abstain": False,
        "expectation": {"tfc": "allowed", "notice_days": 30, "penalty": None},
        "governance_explanation": "The amending deed rescinds and substitutes clause 5.2, so it governs.",
        "justification": "'Rescinded and substituted' is an unambiguous supersession without the development-corpus cue phrase.",
        "confidence": 0.98, "ambiguity": "none", "negative_control": None,
    },
    {
        "ref": "l1_scoped_exception_active",
        "question": "Can the buyer terminate for convenience?",
        "documents": [
            D("a", "Frame Agreement §9 p.7", 0,
              "Either party may terminate for convenience upon forty-five days notice."),
            D("b", "Frame Agreement §9.1 p.7", 1,
              "This right does not apply while a statement of work is active."),
        ],
        "capability": ["scoped_exceptions"], "difficulty": 1,
        "variation": ["explicit_implicit", "section_reference"],
        "gold_nodes": {"Frame Agreement §9 p.7": "Clause", "Frame Agreement §9.1 p.7": "Exception"},
        "gold_edges": [("Frame Agreement §9.1 p.7", "exception_to", "Frame Agreement §9 p.7")],
        "governing": ["Frame Agreement §9 p.7"], "abstain": False,
        "expectation": {"tfc": "allowed", "notice_days": 45, "penalty": None},
        "governance_explanation": "The general right governs; the scoped carve-out qualifies it.",
        "justification": "Exception is scoped ('while a SOW is active') without the word 'except'.",
        "confidence": 0.95, "ambiguity": "The answer is conditional on SOW status; top-line right stands.",
        "negative_control": None,
    },
    {
        "ref": "l1_definition_single",
        "question": "How is the Fee defined?",
        "documents": [
            D("a", "Schedule 1 §1 p.2", 0,
              "In this Schedule, Fee signifies the monthly recurring charge exclusive of tax."),
        ],
        "capability": ["definition_inheritance"], "difficulty": 1,
        "variation": ["wording"],
        "gold_nodes": {"Schedule 1 §1 p.2": "Definition"},
        "gold_edges": [],
        "governing": ["Schedule 1 §1 p.2"], "abstain": False,
        "expectation": {"tfc": "unknown", "notice_days": None, "penalty": None},
        "governance_explanation": "A single definition governs the term Fee.",
        "justification": "'signifies' rather than 'means'; single-node definition.",
        "confidence": 0.9, "ambiguity": "Question is definitional, not about termination.",
        "negative_control": None,
    },

    # ---------- Level 2 — two-hop reasoning -----------------------------------
    {
        "ref": "l2_effective_date_precedence",
        "question": "Is termination for convenience permitted, and on what notice?",
        "documents": [
            D("a", "Variation VII (effective 01/01/2021) p.5", 0,
              "Termination for convenience is prohibited."),
            D("b", "Variation III (effective 15 March 2023) p.9", 1,
              "Termination for convenience is permitted on sixty days notice."),
        ],
        "capability": ["effective_date_precedence"], "difficulty": 2,
        "variation": ["date_format", "doc_order", "number_format"],
        "gold_nodes": {"Variation VII (effective 01/01/2021) p.5": "Clause",
                       "Variation III (effective 15 March 2023) p.9": "Clause"},
        "gold_edges": [("Variation III (effective 15 March 2023) p.9", "effective_after",
                        "Variation VII (effective 01/01/2021) p.5")],
        "governing": ["Variation III (effective 15 March 2023) p.9"], "abstain": False,
        "expectation": {"tfc": "allowed", "notice_days": 60, "penalty": None},
        "governance_explanation": "The later EFFECTIVE date governs, not the later document number or position.",
        "justification": "Numbering (VII vs III) and order are decoys; effective date 2023 > 2021 decides.",
        "confidence": 0.95, "ambiguity": "Requires parsing two date formats.", "negative_control": None,
    },
    {
        "ref": "l2_cross_document_reference_implicit",
        "question": "What is the early-termination charge?",
        "documents": [
            D("a", "Order Form §3 p.1", 0,
              "Any early-termination charge is the amount stated in the applicable pricing appendix."),
            D("b", "Pricing Appendix p.14", 1,
              "The early-termination charge equals two months of charges."),
        ],
        "capability": ["cross_document_reference", "implicit_references"], "difficulty": 2,
        "variation": ["explicit_implicit", "doc_granularity"],
        "gold_nodes": {"Order Form §3 p.1": "Clause", "Pricing Appendix p.14": "Clause"},
        "gold_edges": [("Order Form §3 p.1", "references", "Pricing Appendix p.14")],
        "governing": ["Order Form §3 p.1", "Pricing Appendix p.14"], "abstain": False,
        "expectation": {"tfc": "unknown", "notice_days": None, "penalty": "2 months' fees"},
        "governance_explanation": "The order form defers the value to the pricing appendix, which supplies it.",
        "justification": "Reference is implicit ('the applicable pricing appendix'), not a named schedule id.",
        "confidence": 0.9, "ambiguity": "'applicable' must resolve to the single appendix present.",
        "negative_control": None,
    },
    {
        "ref": "l2_definition_inheritance",
        "question": "Does the confidentiality term cover source code?",
        "documents": [
            D("a", "MSA §1 p.2", 0,
              "Confidential Information includes all non-public technical materials."),
            D("b", "SOW §1 p.1", 1,
              "Terms defined in the MSA carry the same meaning here; Deliverables comprise source code."),
        ],
        "capability": ["definition_inheritance", "transitive_authority"], "difficulty": 2,
        "variation": ["section_reference", "wording"],
        "gold_nodes": {"MSA §1 p.2": "Definition", "SOW §1 p.1": "Definition"},
        "gold_edges": [("SOW §1 p.1", "same_as", "MSA §1 p.2")],
        "governing": ["MSA §1 p.2", "SOW §1 p.1"], "abstain": False,
        "expectation": {"tfc": "unknown", "notice_days": None, "penalty": None},
        "governance_explanation": "The SOW inherits the MSA definition; source code (a Deliverable) is technical material.",
        "justification": "Definition inheritance via 'carry the same meaning', a transitive link.",
        "confidence": 0.82, "ambiguity": "Whether source code is 'technical material' is a small inferential step.",
        "negative_control": None,
    },

    # ---------- Level 3 — multiple interacting relationships -------------------
    {
        "ref": "l3_hierarchical_governance",
        "question": "What notice applies to termination for convenience?",
        "documents": [
            D("a", "MSA §7 p.10", 0, "Termination for convenience requires ninety days notice."),
            D("b", "Order Form §2 p.1", 1, "Termination for convenience requires thirty days notice."),
            D("c", "Governance Charter §4 p.3", 2,
              "Where documents conflict, the order of precedence is: Order Form, then MSA, then Schedules."),
        ],
        "capability": ["hierarchical_governance", "multiple_authorities"], "difficulty": 3,
        "variation": ["doc_granularity", "wording"],
        "gold_nodes": {"MSA §7 p.10": "Clause", "Order Form §2 p.1": "Clause",
                       "Governance Charter §4 p.3": "Policy"},
        "gold_edges": [("Order Form §2 p.1", "governs_over", "MSA §7 p.10")],
        "governing": ["Order Form §2 p.1"], "abstain": False,
        "expectation": {"tfc": "unknown", "notice_days": 30, "penalty": None},
        "governance_explanation": "A precedence charter ranks the Order Form above the MSA, so 30 days governs.",
        "justification": "Precedence is stated as an ordered list in a third document, not a pairwise clause.",
        "confidence": 0.9, "ambiguity": "Charter must be read as governance metadata, not a clause.",
        "negative_control": None,
    },
    {
        "ref": "l3_partial_override",
        "question": "Can either party terminate for convenience, and what notice and penalty?",
        "documents": [
            D("a", "MSA §7 p.10", 0,
              "Either party may terminate for convenience on ninety days notice, with no charge."),
            D("b", "Amendment 5 §1 p.20", 1,
              "Section 7 is amended only as to notice, which becomes thirty days; all other terms are unaffected."),
        ],
        "capability": ["partial_overrides"], "difficulty": 3,
        "variation": ["wording", "explicit_implicit"],
        "gold_nodes": {"MSA §7 p.10": "Clause", "Amendment 5 §1 p.20": "Clause"},
        "gold_edges": [("Amendment 5 §1 p.20", "amends", "MSA §7 p.10")],
        "governing": ["MSA §7 p.10", "Amendment 5 §1 p.20"], "abstain": False,
        "expectation": {"tfc": "allowed", "notice_days": 30, "penalty": None},
        "governance_explanation": "Only the notice is overridden; the permission and no-charge survive.",
        "justification": "Partial override: amendment touches one attribute, base governs the rest.",
        "confidence": 0.9, "ambiguity": "Must merge attributes from two documents.", "negative_control": None,
    },
    {
        "ref": "l3_table_vs_text",
        "question": "What is the early-termination penalty?",
        "documents": [
            D("a", "MSA §7.3 p.10", 0,
              "The early-termination penalty is three months of fees."),
            D("b", "Schedule of Charges (table) p.22", 1,
              "Row: Early termination | Penalty: 6 months of fees."),
        ],
        "capability": ["table_vs_text", "conflicting_amendments"], "difficulty": 3,
        "variation": ["table_prose", "number_format"],
        "gold_nodes": {"MSA §7.3 p.10": "Clause", "Schedule of Charges (table) p.22": "Table"},
        "gold_edges": [("MSA §7.3 p.10", "conflicts_with", "Schedule of Charges (table) p.22")],
        "governing": ["MSA §7.3 p.10"], "abstain": False,
        "expectation": {"tfc": "unknown", "notice_days": None, "penalty": None},
        "governance_explanation": "Prose and table disagree on the penalty; the conflict must be flagged, not silently resolved.",
        "justification": "Table-vs-text numeric contradiction with no precedence rule -> penalty unresolved.",
        "confidence": 0.8, "ambiguity": "Without a precedence rule the penalty is genuinely unresolved.",
        "negative_control": None,
    },
    {
        "ref": "l3_appendix_precedence",
        "question": "Is termination for convenience permitted?",
        "documents": [
            D("a", "MSA §7 p.10", 0, "Termination for convenience is not permitted."),
            D("b", "Appendix H §2 p.40", 1,
              "This Appendix prevails over the body of the Agreement. Termination for convenience is permitted on ninety days notice."),
        ],
        "capability": ["appendix_precedence"], "difficulty": 3,
        "variation": ["wording", "doc_granularity"],
        "gold_nodes": {"MSA §7 p.10": "Clause", "Appendix H §2 p.40": "Clause"},
        "gold_edges": [("Appendix H §2 p.40", "governs_over", "MSA §7 p.10")],
        "governing": ["Appendix H §2 p.40"], "abstain": False,
        "expectation": {"tfc": "allowed", "notice_days": 90, "penalty": None},
        "governance_explanation": "The appendix asserts precedence over the body, so its permission governs.",
        "justification": "Appendix-level precedence ('prevails over the body').",
        "confidence": 0.9, "ambiguity": "none", "negative_control": None,
    },
    {
        "ref": "l3_entity_renaming_policy_migration",
        "question": "Which policy governs termination, and what is the outcome?",
        "documents": [
            D("a", "MSA §7 p.10", 0, "Termination for convenience is permitted on sixty days notice."),
            D("b", "Policy P-100 p.2", 1,
              "Policy P-100 is superseded by Policy Q-1; refer to Q-1 for the current rule."),
            D("c", "Policy Q-1 p.1", 2,
              "For regulated engagements, termination for convenience is prohibited, notwithstanding any contract term."),
        ],
        "capability": ["policy_migration", "entity_renaming", "transitive_authority"], "difficulty": 3,
        "variation": ["policy_naming", "wording"],
        "gold_nodes": {"MSA §7 p.10": "Clause", "Policy P-100 p.2": "Policy", "Policy Q-1 p.1": "Policy"},
        "gold_edges": [("Policy Q-1 p.1", "supersedes", "Policy P-100 p.2"),
                       ("Policy Q-1 p.1", "overrides", "MSA §7 p.10")],
        "governing": ["Policy Q-1 p.1"], "abstain": False,
        "expectation": {"tfc": "prohibited", "notice_days": None, "penalty": None},
        "governance_explanation": "P-100 migrated to Q-1; Q-1 overrides the contract for regulated engagements.",
        "justification": "Policy migration (renaming) plus policy-over-contract override; two hops.",
        "confidence": 0.85, "ambiguity": "Assumes the engagement is 'regulated'.", "negative_control": None,
    },

    # ---------- Level 4 — conflicting governance ------------------------------
    {
        "ref": "l4_parallel_overrides_agreeing",
        "question": "Can the vendor be terminated for convenience?",
        "documents": [
            D("a", "MSA §7 p.10", 0, "Either party may terminate for convenience on ninety days notice."),
            D("b", "Corporate Policy G-2 p.2", 1,
              "Termination for convenience of critical suppliers is barred, notwithstanding any contract term."),
            D("c", "Regulatory Directive R-9 p.1", 2,
              "For designated suppliers, at-will termination is prohibited regardless of contractual permission."),
        ],
        "capability": ["parallel_overrides", "multiple_authorities"], "difficulty": 4,
        "variation": ["policy_naming", "wording", "voice"],
        "gold_nodes": {"MSA §7 p.10": "Clause", "Corporate Policy G-2 p.2": "Policy",
                       "Regulatory Directive R-9 p.1": "Policy"},
        "gold_edges": [("Corporate Policy G-2 p.2", "overrides", "MSA §7 p.10"),
                       ("Regulatory Directive R-9 p.1", "overrides", "MSA §7 p.10")],
        "governing": ["Corporate Policy G-2 p.2", "Regulatory Directive R-9 p.1"], "abstain": False,
        "expectation": {"tfc": "prohibited", "notice_days": None, "penalty": None},
        "governance_explanation": "Two parallel authorities both override the clause and agree it is prohibited.",
        "justification": "Parallel overrides that AGREE -> outcome is determinate (prohibited).",
        "confidence": 0.9, "ambiguity": "Both authorities align, so no tie-break needed.", "negative_control": None,
    },
    {
        "ref": "l4_conditional_applicability",
        "question": "Is termination for convenience permitted for this engagement?",
        "documents": [
            D("a", "MSA §7 p.10", 0, "Termination for convenience is permitted on sixty days notice."),
            D("b", "Rider 4 §1 p.15", 1,
              "If the engagement is government-facing, termination for convenience is unavailable; otherwise the MSA applies."),
        ],
        "capability": ["conditional_applicability", "scoped_exceptions"], "difficulty": 4,
        "variation": ["explicit_implicit", "wording"],
        "gold_nodes": {"MSA §7 p.10": "Clause", "Rider 4 §1 p.15": "Exception"},
        "gold_edges": [("Rider 4 §1 p.15", "exception_to", "MSA §7 p.10")],
        "governing": ["MSA §7 p.10"], "abstain": False,
        "expectation": {"tfc": "allowed", "notice_days": 60, "penalty": None},
        "governance_explanation": "The general rule governs; the rider applies only under a condition not asserted here.",
        "justification": "Conditional exception; absent the condition, base governs. Answer is conditional.",
        "confidence": 0.7,
        "ambiguity": "If the engagement is government-facing the answer flips; condition unknown here.",
        "negative_control": None,
    },
    {
        "ref": "l4_multi_hop_transitive",
        "question": "What early-termination penalty applies?",
        "documents": [
            D("a", "MSA §7.3 p.10", 0, "The penalty is as set out in Schedule C."),
            D("b", "Schedule C p.30", 1, "The penalty is as set out in Exhibit 4."),
            D("c", "Exhibit 4 p.44", 2, "The early-termination penalty is four months of fees."),
        ],
        "capability": ["multi_hop", "cross_document_reference", "transitive_authority"], "difficulty": 4,
        "variation": ["doc_granularity", "section_reference"],
        "gold_nodes": {"MSA §7.3 p.10": "Clause", "Schedule C p.30": "Clause", "Exhibit 4 p.44": "Clause"},
        "gold_edges": [("MSA §7.3 p.10", "references", "Schedule C p.30"),
                       ("Schedule C p.30", "references", "Exhibit 4 p.44")],
        "governing": ["MSA §7.3 p.10", "Schedule C p.30", "Exhibit 4 p.44"], "abstain": False,
        "expectation": {"tfc": "unknown", "notice_days": None, "penalty": "4 months' fees"},
        "governance_explanation": "Two reference hops resolve the penalty to Exhibit 4's value.",
        "justification": "Multi-hop transitive reference chain A->B->C with a real ground term at C.",
        "confidence": 0.9, "ambiguity": "none", "negative_control": None,
    },
    {
        "ref": "l4_nested_exception",
        "question": "May the customer terminate for convenience during the Initial Term?",
        "documents": [
            D("a", "MSA §7 p.10", 0, "Either party may terminate for convenience on sixty days notice."),
            D("b", "Schedule D §4 p.18", 1,
              "During the Initial Term the customer may not exercise the foregoing right."),
            D("c", "Schedule D §5 p.19", 2,
              "The preceding restriction does not apply to a change-of-control termination."),
        ],
        "capability": ["nested_exceptions"], "difficulty": 4,
        "variation": ["wording", "explicit_implicit"],
        "gold_nodes": {"MSA §7 p.10": "Clause", "Schedule D §4 p.18": "Exception",
                       "Schedule D §5 p.19": "Exception"},
        "gold_edges": [("Schedule D §4 p.18", "exception_to", "MSA §7 p.10"),
                       ("Schedule D §5 p.19", "exception_to", "Schedule D §4 p.18")],
        "governing": ["MSA §7 p.10"], "abstain": False,
        "expectation": {"tfc": "allowed", "notice_days": 60, "penalty": None},
        "governance_explanation": "A restriction on the right is itself qualified by a nested carve-out; top-line right stands generally.",
        "justification": "Two-level nested exception (exception to an exception).",
        "confidence": 0.65,
        "ambiguity": "Answer for the plain Initial Term case is restricted; nested carve-out re-enables it for change-of-control.",
        "negative_control": None,
    },

    # ---------- Level 5 — deep enterprise reasoning ---------------------------
    {
        "ref": "l5_competing_authorities_dated_migration",
        "question": "Is termination for convenience permitted, and on what notice?",
        "documents": [
            D("a", "MSA §7 p.10", 0, "Termination for convenience is permitted on ninety days notice."),
            D("b", "Order Form §2 (effective 2020) p.1", 1,
              "For this order, termination for convenience requires thirty days notice; this Order Form prevails over the MSA."),
            D("c", "Policy P-7 p.2", 2, "Policy P-7 has been migrated to Policy P-8."),
            D("d", "Policy P-8 (effective 2024) p.1", 3,
              "For strategic accounts, termination for convenience is prohibited, notwithstanding any order or contract term."),
        ],
        "capability": ["multiple_authorities", "hierarchical_governance", "policy_migration",
                       "effective_date_precedence", "transitive_authority"], "difficulty": 5,
        "variation": ["policy_naming", "date_format", "doc_order", "wording"],
        "gold_nodes": {"MSA §7 p.10": "Clause", "Order Form §2 (effective 2020) p.1": "Clause",
                       "Policy P-7 p.2": "Policy", "Policy P-8 (effective 2024) p.1": "Policy"},
        "gold_edges": [("Order Form §2 (effective 2020) p.1", "governs_over", "MSA §7 p.10"),
                       ("Policy P-8 (effective 2024) p.1", "supersedes", "Policy P-7 p.2"),
                       ("Policy P-8 (effective 2024) p.1", "overrides", "Order Form §2 (effective 2020) p.1")],
        "governing": ["Policy P-8 (effective 2024) p.1"], "abstain": False,
        "expectation": {"tfc": "prohibited", "notice_days": None, "penalty": None},
        "governance_explanation": "Order Form beats MSA; but the migrated, later policy P-8 overrides even the Order Form for strategic accounts.",
        "justification": "Four interacting constraints: hierarchy, migration, effective date, policy-over-contract.",
        "confidence": 0.75, "ambiguity": "Assumes a 'strategic account'; otherwise 30 days would govern.",
        "negative_control": None,
    },
    {
        "ref": "l5_conflicting_amendments_tiebreak",
        "question": "What notice applies to termination for convenience?",
        "documents": [
            D("a", "Amendment A (effective 2022-06-01) p.3", 0,
              "Termination for convenience requires thirty days notice."),
            D("b", "Amendment B (effective 2022-06-01) p.4", 1,
              "Termination for convenience requires sixty days notice."),
            D("c", "Execution Ledger p.1", 2,
              "Amendment B was executed after Amendment A on the same effective date."),
        ],
        "capability": ["conflicting_amendments", "version_supersession"], "difficulty": 5,
        "variation": ["date_format", "wording", "doc_granularity"],
        "gold_nodes": {"Amendment A (effective 2022-06-01) p.3": "Clause",
                       "Amendment B (effective 2022-06-01) p.4": "Clause",
                       "Execution Ledger p.1": "Document"},
        "gold_edges": [("Amendment B (effective 2022-06-01) p.4", "supersedes",
                        "Amendment A (effective 2022-06-01) p.3")],
        "governing": ["Amendment B (effective 2022-06-01) p.4"], "abstain": False,
        "expectation": {"tfc": "allowed", "notice_days": 60, "penalty": None},
        "governance_explanation": "Same effective date; the execution ledger breaks the tie in favour of the later-executed Amendment B.",
        "justification": "Tie on effective date resolved by execution order recorded in a third document.",
        "confidence": 0.7, "ambiguity": "Depends on treating execution order as the tie-break rule.",
        "negative_control": None,
    },

    # ---------- Negative controls --------------------------------------------
    {
        "ref": "neg_no_relationship",
        "question": "Is termination for convenience permitted?",
        "documents": [
            D("a", "NDA §2 p.1", 0, "Each party shall keep the other's information confidential for five years."),
            D("b", "Invoice 88 p.1", 1, "Amount due for professional services rendered in the quarter."),
        ],
        "capability": ["no_relationship"], "difficulty": 2,
        "variation": ["doc_granularity"],
        "gold_nodes": {"NDA §2 p.1": "Clause", "Invoice 88 p.1": "Document"},
        "gold_edges": [], "governing": [], "abstain": True,
        "expectation": {"abstain": True},
        "governance_explanation": "No document addresses termination; there is nothing to govern.",
        "justification": "Negative control: the queried relationship simply does not exist in the corpus.",
        "confidence": 0.95, "ambiguity": "none", "negative_control": "no_relationship",
    },
    {
        "ref": "neg_unresolvable_conflict",
        "question": "What notice applies to termination for convenience?",
        "documents": [
            D("a", "Amendment X (effective 2023-01-01) p.2", 0,
              "Termination for convenience requires thirty days notice."),
            D("b", "Amendment Y (effective 2023-01-01) p.2", 1,
              "Termination for convenience requires ninety days notice."),
        ],
        "capability": ["unresolvable_conflict", "conflicting_amendments"], "difficulty": 4,
        "variation": ["date_format", "wording"],
        "gold_nodes": {"Amendment X (effective 2023-01-01) p.2": "Clause",
                       "Amendment Y (effective 2023-01-01) p.2": "Clause"},
        "gold_edges": [("Amendment X (effective 2023-01-01) p.2", "conflicts_with",
                        "Amendment Y (effective 2023-01-01) p.2")],
        "governing": [], "abstain": True,
        "expectation": {"abstain": True},
        "governance_explanation": "Identical effective dates, contradictory terms, no tie-break -> cannot resolve.",
        "justification": "Negative control: correct behaviour is abstention, not a guess.",
        "confidence": 0.95, "ambiguity": "Genuinely unresolvable without further evidence.",
        "negative_control": "unresolvable_conflict",
    },
    {
        "ref": "neg_insufficient_evidence",
        "question": "What is the early-termination penalty?",
        "documents": [
            D("a", "Order Form §3 p.1", 0,
              "The early-termination penalty is as stated in the Master Pricing Terms."),
        ],
        "capability": ["insufficient_evidence", "implicit_references"], "difficulty": 3,
        "variation": ["explicit_implicit"],
        "gold_nodes": {"Order Form §3 p.1": "Clause"},
        "gold_edges": [("Order Form §3 p.1", "references", "Master Pricing Terms")],
        "governing": [], "abstain": True,
        "expectation": {"abstain": True},
        "governance_explanation": "The value is deferred to a document not present; evidence is insufficient.",
        "justification": "Negative control: dangling reference to an absent document -> abstain.",
        "confidence": 0.95, "ambiguity": "none", "negative_control": "insufficient_evidence",
    },
    {
        "ref": "neg_circular_reference",
        "question": "What is the termination fee?",
        "documents": [
            D("a", "MSA §7 p.10", 0, "The termination fee is defined in the Fee Schedule."),
            D("b", "Fee Schedule p.20", 1, "The termination fee is as defined in the MSA."),
        ],
        "capability": ["circular_reference"], "difficulty": 3,
        "variation": ["wording"],
        "gold_nodes": {"MSA §7 p.10": "Clause", "Fee Schedule p.20": "Clause"},
        "gold_edges": [("MSA §7 p.10", "references", "Fee Schedule p.20"),
                       ("Fee Schedule p.20", "references", "MSA §7 p.10")],
        "governing": [], "abstain": True,
        "expectation": {"abstain": True},
        "governance_explanation": "Each document defers to the other; no ground term exists.",
        "justification": "Negative control: reference cycle -> abstain.",
        "confidence": 0.97, "ambiguity": "none", "negative_control": "circular_reference",
    },
    {
        "ref": "neg_multiple_valid_interpretations",
        "question": "Does 'affiliate' include a minority-owned joint venture?",
        "documents": [
            D("a", "MSA §1 p.2", 0,
              "Affiliate means an entity that controls, is controlled by, or is under common control with a party."),
            D("b", "MSA §1.1 p.2", 1,
              "Control is not defined."),
        ],
        "capability": ["multiple_valid_interpretations", "definition_inheritance"], "difficulty": 4,
        "variation": ["wording", "explicit_implicit"],
        "gold_nodes": {"MSA §1 p.2": "Definition", "MSA §1.1 p.2": "Clause"},
        "gold_edges": [],
        "governing": [], "abstain": True,
        "expectation": {"abstain": True},
        "governance_explanation": "'Control' is undefined, so minority-JV inclusion has more than one defensible reading.",
        "justification": "Negative control: genuine interpretive ambiguity -> abstain rather than assert.",
        "confidence": 0.8, "ambiguity": "Two defensible interpretations; neither is entailed.",
        "negative_control": "multiple_valid_interpretations",
    },
]
