"""Hiring-owned domain audit event taxonomy (H1).

These event types cover the **candidate-facing hiring product entities** —
requisitions, job definitions, candidates, applications, and evidence intake —
whose lifecycles are owned by AI Hiring (see
``docs/ai-hiring/PLATFORM_BOUNDARY.md``). They are *deliberately* a hiring-owned
enum, not members of the frozen kernel ``ugence_decision_authority`` ``AuditEventType``:
Platform v1.0 is frozen and does not (and must not) enumerate hiring product
events. This taxonomy is additive, application-local, and never crosses the
platform boundary.

The kernel ``AuditService`` / ``AuditEventType`` remain reserved for the governance
chain (case → recommendation → decision → action → execution), wired in later
phases. Nothing here scores, ranks, recommends, or decides.
"""

from __future__ import annotations

from enum import Enum


class HiringDomainEventType(str, Enum):
    """Append-only lifecycle events for H1 hiring product entities."""

    # --- Requisition ---
    REQUISITION_CREATED = "REQUISITION_CREATED"
    REQUISITION_OPENED = "REQUISITION_OPENED"
    REQUISITION_PUT_ON_HOLD = "REQUISITION_PUT_ON_HOLD"
    REQUISITION_RESUMED = "REQUISITION_RESUMED"
    REQUISITION_FILLED = "REQUISITION_FILLED"
    REQUISITION_CLOSED = "REQUISITION_CLOSED"
    REQUISITION_CANCELLED = "REQUISITION_CANCELLED"

    # --- Job definition ---
    JOB_DEFINITION_DRAFTED = "JOB_DEFINITION_DRAFTED"
    JOB_DEFINITION_PUBLISHED = "JOB_DEFINITION_PUBLISHED"
    JOB_DEFINITION_RETIRED = "JOB_DEFINITION_RETIRED"

    # --- Candidate ---
    CANDIDATE_REGISTERED = "CANDIDATE_REGISTERED"
    CANDIDATE_PROFILE_REVISED = "CANDIDATE_PROFILE_REVISED"
    CANDIDATE_WITHDRAWN = "CANDIDATE_WITHDRAWN"

    # --- Application ---
    APPLICATION_SUBMITTED = "APPLICATION_SUBMITTED"
    APPLICATION_SCREENING_STARTED = "APPLICATION_SCREENING_STARTED"
    APPLICATION_ADVANCED_TO_ASSESSMENT = "APPLICATION_ADVANCED_TO_ASSESSMENT"
    APPLICATION_ADVANCED_TO_REVIEW = "APPLICATION_ADVANCED_TO_REVIEW"
    APPLICATION_CLOSED = "APPLICATION_CLOSED"
    APPLICATION_WITHDRAWN = "APPLICATION_WITHDRAWN"

    # --- Evidence intake (collection + provenance binding) ---
    EVIDENCE_INTAKE_RECEIVED = "EVIDENCE_INTAKE_RECEIVED"
    EVIDENCE_INTAKE_PROVENANCE_BOUND = "EVIDENCE_INTAKE_PROVENANCE_BOUND"

    # --- H2: recommendation & evidence synthesis ---
    SYNTHESIS_REQUESTED = "SYNTHESIS_REQUESTED"
    SYNTHESIS_COMPLETED = "SYNTHESIS_COMPLETED"
    RECOMMENDATION_GENERATED = "RECOMMENDATION_GENERATED"
    RECOMMENDATION_GENERATION_FAILED = "RECOMMENDATION_GENERATION_FAILED"
    CLAIM_CREATED = "CLAIM_CREATED"
    CLAIM_EVALUATED = "CLAIM_EVALUATED"
    EVIDENCE_INSUFFICIENCY_DETECTED = "EVIDENCE_INSUFFICIENCY_DETECTED"
    RECOMMENDATION_SUBMITTED_FOR_REVIEW = "RECOMMENDATION_SUBMITTED_FOR_REVIEW"
    RECOMMENDATION_REJECTED_BY_REVIEWER = "RECOMMENDATION_REJECTED_BY_REVIEWER"
    RECOMMENDATION_RETURNED_FOR_REVISION = "RECOMMENDATION_RETURNED_FOR_REVISION"
    RECOMMENDATION_ACCEPTED_FOR_CONSIDERATION = "RECOMMENDATION_ACCEPTED_FOR_CONSIDERATION"
    ADDITIONAL_EVIDENCE_REQUESTED = "ADDITIONAL_EVIDENCE_REQUESTED"
    RECOMMENDATION_SUPERSEDED = "RECOMMENDATION_SUPERSEDED"

    # --- H3: governance integration (DGM case → human decision) ---
    GOVERNANCE_CASE_OPENED = "GOVERNANCE_CASE_OPENED"
    RECOMMENDATION_BOUND_TO_CASE = "RECOMMENDATION_BOUND_TO_CASE"
    GOVERNANCE_REVIEW_ASSIGNED = "GOVERNANCE_REVIEW_ASSIGNED"
    GOVERNANCE_REVIEW_COMPLETED = "GOVERNANCE_REVIEW_COMPLETED"
    HUMAN_DECISION_RECORDED = "HUMAN_DECISION_RECORDED"
    GOVERNANCE_DECISION_OVERRIDE_RECORDED = "GOVERNANCE_DECISION_OVERRIDE_RECORDED"
    GOVERNANCE_RECOMMENDATION_REJECTED = "GOVERNANCE_RECOMMENDATION_REJECTED"
    GOVERNANCE_CASE_SUPERSEDED = "GOVERNANCE_CASE_SUPERSEDED"
    GOVERNANCE_CASE_CLOSED = "GOVERNANCE_CASE_CLOSED"

    # --- H4: action authorization, execution, reconciliation ---
    ACTION_PROPOSED = "ACTION_PROPOSED"
    ACTION_REVISED = "ACTION_REVISED"
    ACTION_READY_FOR_AUTHORIZATION = "ACTION_READY_FOR_AUTHORIZATION"
    ACTION_AUTHORIZATION_REQUESTED = "ACTION_AUTHORIZATION_REQUESTED"
    ACTION_AUTHORIZED = "ACTION_AUTHORIZED"
    ACTION_AUTHORIZATION_REFUSED = "ACTION_AUTHORIZATION_REFUSED"
    ACTION_OBLIGATION_UNMET = "ACTION_OBLIGATION_UNMET"
    HIRING_EXECUTION_REQUESTED = "HIRING_EXECUTION_REQUESTED"
    HIRING_EXECUTION_ATTEMPTED = "HIRING_EXECUTION_ATTEMPTED"
    HIRING_EXECUTION_SUCCEEDED = "HIRING_EXECUTION_SUCCEEDED"
    HIRING_EXECUTION_FAILED = "HIRING_EXECUTION_FAILED"
    HIRING_EXECUTION_RETRIED = "HIRING_EXECUTION_RETRIED"
    RECONCILIATION_COMPLETED = "RECONCILIATION_COMPLETED"
    RECONCILIATION_MISMATCH_DETECTED = "RECONCILIATION_MISMATCH_DETECTED"
    COMPENSATION_PROPOSED = "COMPENSATION_PROPOSED"
    REMEDIATION_REQUESTED = "REMEDIATION_REQUESTED"
    ACTION_SUPERSEDED = "ACTION_SUPERSEDED"
    ACTION_CANCELLED = "ACTION_CANCELLED"

    # --- Access / boundary (denials) ---
    DOMAIN_ACCESS_DENIED = "DOMAIN_ACCESS_DENIED"


# Events that record a denial / boundary rejection rather than a state change.
DENIAL_EVENTS = frozenset({HiringDomainEventType.DOMAIN_ACCESS_DENIED})
