"""Phase 4 - Anti-self-verification study.

The failure mode that beat the rich classifier: generated content accepted as evidence for its own
factual claim. Here it is an explicit hard rule (INV-1/INV-2). This module runs the canonical
self-verification traps through the minimal policy and verifies every one is rejected - obligation
raised to at least E3 (independent evidence) or ER, never self-satisfied.

Deterministic, read-only.
"""
from __future__ import annotations

from typing import Any, Dict, List

from minimal_evidence_policy import policy, schema as s

# (label, item) - each is a self-verification / circular / non-independent trap
CASES: List = [
    ("model says its answer is verified",
     {"claim_family": "current_fact", "source_role": "model_generated_text", "self_verification": True, "risk_tier": "medium"}),
    ("model cites its own previous output",
     {"claim_family": "current_fact", "source_role": "model_generated_text", "circular_evidence": True, "risk_tier": "medium"}),
    ("generated summary cites generated summary",
     {"claim_family": "historical_fact", "source_role": "model_generated_text", "circular_evidence": True, "risk_tier": "medium"}),
    ("README cites generated benchmark report",
     {"claim_family": "measured_performance", "source_role": "generated_documentation", "evidence_kind": "synthetic_eval", "risk_tier": "high"}),
    ("documentation cites its own unsupported statement",
     {"claim_family": "current_fact", "source_role": "generated_documentation", "circular_evidence": True, "risk_tier": "medium"}),
    ("circular citation chain",
     {"claim_family": "scientific", "evidence_derives_from_claim": True, "risk_tier": "high"}),
    ("multiple models repeat the same unsupported premise",
     {"claim_family": "causal", "source_role": "model_generated_text", "circular_evidence": True, "risk_tier": "high"}),
    ("implementation comment claims production performance",
     {"claim_family": "measured_performance", "evidence_kind": "source_code", "risk_tier": "high"}),
    ("test fixture treated as telemetry",
     {"claim_family": "measured_performance", "evidence_kind": "test_fixture", "risk_tier": "high"}),
    ("synthetic evaluation treated as customer evidence",
     {"claim_family": "model_quality", "evidence_kind": "synthetic_eval", "risk_tier": "high"}),
    ("model confidence used as factual evidence",
     {"claim_family": "current_fact", "source_role": "model_generated_text", "self_verification": True, "risk_tier": "medium"}),
    ("self-issued approval artifact",
     {"claim_family": "internal_policy", "claims_internal_authority": True, "explicit_authority_basis": False, "risk_tier": "high"}),
    ("policy generated by the same unauthorized system",
     {"claim_family": "internal_policy", "source_role": "model_generated_text", "claims_internal_authority": True, "explicit_authority_basis": False, "risk_tier": "high"}),
]


def validate() -> Dict[str, Any]:
    rows = []
    rejected = 0
    for i, (label, item) in enumerate(CASES):
        it = {"artifact_id": f"sv-{i}", **item}
        d = policy.assign(it)
        # rejected = obligation raised to >= E3 (independent evidence) or ER; never self-satisfied at <=E2
        ok = s.RANK[d.final_obligation] >= s.RANK[s.E3]
        rejected += ok
        rows.append({"case": label, "final": d.final_obligation,
                     "invariants": d.invariants_triggered, "rejected_self_support": ok})
    n = len(CASES)
    return {
        "n": n, "rejected_self_support": rejected,
        "self_verification_escape": n - rejected,     # PILOT BLOCKER if > 0
        "all_rejected": rejected == n,
        "rows": rows,
    }


if __name__ == "__main__":
    m = validate()
    for r in m["rows"]:
        print(f"  [{'REJECT' if r['rejected_self_support'] else 'ESCAPE'}] {r['final'][:2]} {r['case']}")
    print(f"\nself-verification escapes: {m['self_verification_escape']} (all_rejected={m['all_rejected']})")
