"""Pilot refusal vocabulary (specification §3–§6, §8). Every code is a refusal."""

from __future__ import annotations

from enum import Enum


class PilotErrorCode(str, Enum):
    ROLE_INCONSISTENT = "ROLE_INCONSISTENT"
    ADVISORY_REQUIRED = "ADVISORY_REQUIRED"
    ADVISORY_MISMATCH = "ADVISORY_MISMATCH"
    METHOD_DUPLICATE = "METHOD_DUPLICATE"
    METHOD_NOT_IN_CATALOG = "METHOD_NOT_IN_CATALOG"
    BENCHMARK_MANIFEST_MISMATCH = "BENCHMARK_MANIFEST_MISMATCH"
    BENCHMARK_HEAD_MISMATCH = "BENCHMARK_HEAD_MISMATCH"
    AGGREGATION_MISMATCH = "AGGREGATION_MISMATCH"
    ATTESTED_FIELDS_INVALID = "ATTESTED_FIELDS_INVALID"
    CATALOG_MISMATCH = "CATALOG_MISMATCH"
    RULE_SET_MISMATCH = "RULE_SET_MISMATCH"
    COMPOSITION_INCOMPLETE = "COMPOSITION_INCOMPLETE"
    MANIFEST_MISMATCH = "MANIFEST_MISMATCH"
    MANIFEST_NOT_VALIDATED = "MANIFEST_NOT_VALIDATED"
    MANIFEST_NOT_PRIOR = "MANIFEST_NOT_PRIOR"
    RECORD_MISMATCH = "RECORD_MISMATCH"
    QUALITY_EVALUATION_MISMATCH = "QUALITY_EVALUATION_MISMATCH"
    QUALITY_RESULT_MISMATCH = "QUALITY_RESULT_MISMATCH"
    ATTESTATION_MISMATCH = "ATTESTATION_MISMATCH"
    TELEMETRY_NOT_RECOMPUTED = "TELEMETRY_NOT_RECOMPUTED"
    SELF_ATTESTATION = "SELF_ATTESTATION"
    CAPTURE_INCOMPLETE = "CAPTURE_INCOMPLETE"
    WORKFLOW_FAILED = "WORKFLOW_FAILED"
    PROVIDER_FACTORY_INVALID = "PROVIDER_FACTORY_INVALID"
    EVALUATOR_KIND_INCONSISTENT = "EVALUATOR_KIND_INCONSISTENT"
    EVALUATOR_SELF_LOOP = "EVALUATOR_SELF_LOOP"
    STATE_TRANSITION_INVALID = "STATE_TRANSITION_INVALID"
    REVISION_WITHOUT_CHANGE = "REVISION_WITHOUT_CHANGE"
    REVISION_SCOPE_MISMATCH = "REVISION_SCOPE_MISMATCH"
    LINEAGE_INCOMPLETE = "LINEAGE_INCOMPLETE"
    SUMMARY_NOT_PERMITTED = "SUMMARY_NOT_PERMITTED"
    COUNT_INVALID = "COUNT_INVALID"
    SCHEMA_VERSION_UNSUPPORTED = "SCHEMA_VERSION_UNSUPPORTED"


class PilotError(ValueError):
    def __init__(self, code: PilotErrorCode, detail: str = "") -> None:
        if not isinstance(code, PilotErrorCode):
            raise TypeError("PilotError requires a PilotErrorCode")
        self.code = code
        self.detail = detail
        super().__init__(f"{code.value}: {detail}" if detail else code.value)


__all__ = ["PilotErrorCode", "PilotError"]
