"""
Sentinel - Agentic LLM Framework

A framework for building agentic AI systems that wrap existing LLM APIs
(ChatGPT, Gemini, Claude, etc.) with:

1. Goal Decomposition - Extract structured intent from user input
2. Memory Store - Persistent context management external to LLM
3. Reflective Generation - Self-revising responses with quality critic
4. Coherence Tracking - Track conversation-level coherence metrics
5. Safety Contract - Fail-closed action gating
6. Local Critic - Cost-optimized quality evaluation (10-100x cheaper)
7. Adaptive Policy Engine - Policy-level memory that modifies behavior
8. Confidence Gate - Behavioral confidence control (gates execution, not annotations)
9. MCP Gateway - Safe tool integration with risk-based access control
10. Proactive Scheduler - Autonomous task execution with safety controls

Usage:
    from agentic.agentic_framework import AgenticLLMWrapper

    # With OpenAI
    from agentic.agentic_framework.llm_adapters import OpenAIAdapter
    llm = OpenAIAdapter(api_key="...")
    agent = AgenticLLMWrapper(llm)

    # Start session
    agent.new_session()

    # Run conversation
    result = agent.run("What is the capital of France?")
    print(result.response)
"""

from agentic.agentic_framework.agent import AgenticLLMWrapper
from agentic.agentic_framework.goal_decomposition import GoalState, ActionItem, decompose_goal, normalize_action_type
from agentic.agentic_framework.memory_store import AgentMemory, TurnSnapshot, MemoryStore
from agentic.agentic_framework.reflective_loop import (
    ReflectiveGenerator,
    QualityCritic,
    RuleBasedCritic,
    LLMBasedCritic,
    QualityCritique,
    GenerationResult,
)
from agentic.agentic_framework.coherence_tracker import (
    CoherenceMetrics,
    CoherenceState,
    CoherenceEngine,
)
from agentic.agentic_framework.safety_contract import (
    SafetyContract,
    SafetyContractEvaluator,
)
from agentic.agentic_framework.local_critic import (
    LocalCritic,
    OllamaBackend,
    TransformersBackend,
    LlamaCppBackend,
    CostAwareCriticSelector,
    SelectionStrategy,
    create_ollama_critic,
    create_transformers_critic,
    create_llamacpp_critic,
    create_cost_aware_critic,
)
from agentic.agentic_framework.adaptive_policy import (
    AdaptivePolicyEngine,
    SessionTrajectory,
    ToolPermission,
    PolicyDecision,
    PolicyParameters,
    SessionPerformanceHistory,
    PerformanceSnapshot,
    create_adaptive_policy_engine,
)
from agentic.agentic_framework.confidence_gate import (
    ConfidenceGate,
    ConfidenceSignals,
    UnifiedConfidence,
    EscalationLevel,
    EscalationDecision,
    ExecutionMode,
    ExecutionPermission,
    BudgetAllocation,
    MemoryWeight,
    ConfidenceGateDecision,
    create_confidence_gate,
    create_strict_confidence_gate,
    create_permissive_confidence_gate,
    signals_from_critique,
    signals_from_coherence_metrics,
    signals_from_policy_decision,
    merge_signals,
)
from agentic.agentic_framework.sovereign_bridge import (
    signals_from_sovereign_state,
    coherence_from_sovereign_state,
    SovereignCoherenceState,
)
from agentic.agentic_framework.mcp_gateway import (
    SafeMCPGateway,
    MCPToolCall,
    MCPToolResult,
    ToolRiskLevel,
    ToolRiskClassifier,
    ToolSpec,
    AuditEntry,
    MCPClientInterface,
    MockMCPClient,
    create_safe_mcp_gateway,
    create_mock_mcp_gateway,
)
from agentic.agentic_framework.agent_builder import build_agent
from agentic.agentic_framework.proactive_scheduler import (
    ProactiveScheduler,
    ScheduledTask,
    ExecutionRecord,
    CronExpression,
    TaskStatus,
    ScheduleType,
    create_proactive_scheduler,
    create_task,
)
from agentic.agentic_framework.cancellation import CancellationToken
from agentic.agentic_framework.approval import (
    ApprovalCallback,
    ApprovalController,
    ApprovalPolicy,
    ApprovalResponse,
    PendingApproval,
)
from agentic.agentic_framework.approval_coverage import (
    ApprovalCoverageEntry,
    describe_approval_coverage,
    format_approval_coverage,
)
from agentic.agentic_framework.token_budget import (
    BudgetPolicy,
    UsageStats,
    estimate_tokens,
)
from agentic.agentic_framework.memory_retention import MemoryRetentionPolicy
from agentic.agentic_framework.structured_output import (
    OutputSchema,
    SchemaTarget,
    StructuredRunResult,
)
from agentic.agentic_framework.tracing import (
    AgentRunTrace,
    TraceCollector,
)
from agentic.agentic_framework.trace_viewer import (
    format_trace,
    format_trace_summary,
    format_trace_timeline,
)
from agentic.agentic_framework.streaming_events import (
    AgentRunEvent,
    make_event,
    RUN_STARTED,
    GENERATION_STARTED,
    TEXT_CHUNK,
    GENERATION_COMPLETED,
    SAFETY_GATE_RESULT,
    ACTION_STARTED,
    ACTION_COMPLETED,
    RUN_COMPLETED,
    STRUCTURED_VALIDATION,
    RUN_ERROR,
    RUN_CANCELLED,
    REVISION_STARTED,
    REVISION_COMPLETED,
    APPROVAL_REQUESTED,
    APPROVAL_RESOLVED,
    USAGE_UPDATED,
    BUDGET_EXCEEDED,
)
from agentic.agentic_framework.tool_discovery import (
    DiscoveredTool,
    ToolCatalog,
)
from agentic.agentic_framework.llm_adapters import (
    MockLLMAdapter,
    SequentialMockAdapter,
    OpenAIAdapter,
    AnthropicAdapter,
    MistralAdapter,
    MistralCGAdapter,
)
from agentic.agentic_framework.adaptive_prompts import (
    AutoReasoningPipeline,
    AdaptivePromptEngine,
    AdaptivePromptTemplates,
    ComplexityDetector,
    ReasoningDepth,
    ComplexitySignal,
    ReasoningStage,
    ComplexityAnalysis,
    ReasoningStep,
    AdaptivePromptResult,
    create_adaptive_pipeline,
    create_progressive_pipeline,
    create_always_deep_pipeline,
    create_conservative_pipeline,
)
from agentic.agentic_framework.iterate_loop import (
    Observation,
    LoopStep,
    LoopHistory,
    LoopResult,
    CompletionVerdict,
    CompletionChecker,
    PredicateCompletionChecker,
    KeywordCompletionChecker,
    LLMCompletionChecker,
    IterativeAgentRunner,
    run_until_done,
)
from agentic.agentic_framework.multi_agent import (
    RegisteredAgent,
    AgentRegistry,
    AgentTurn,
    Handoff,
    RouteDecision,
    Router,
    KeywordRouter,
    LLMRouter,
    MultiAgentResult,
    MultiAgentOrchestrator,
)
from agentic.agentic_framework.run_budget import (
    BudgetDimension,
    TerminationReason,
    RunBudgetStatus,
    RunBudgetLimits,
    RunBudgetUsage,
    Reservation,
    BudgetViolation,
    BudgetExhausted,
    RunBudget,
    BudgetedAdapter,
    attach_run_budget,
    format_run_budget,
)
from agentic.agentic_framework.replanning import (
    ObservationStatus,
    PlanStepState,
    ReplanDecision,
    StopReason,
    PlanObservation,
    PlanStep,
    Plan,
    PlanRevision,
    ReplanPolicy,
    DeterministicReplanPolicy,
    Replanner,
    RuleBasedReplanner,
    ObservationBuilder,
    ScriptedObservationBuilder,
    DefaultObservationBuilder,
    StagnationConfig,
    StagnationDetector,
    ReplanningResult,
    ReplanningRunner,
    format_plan,
    format_replanning_trace,
)
from agentic.agentic_framework.plan_validity import (
    AssumptionState,
    PlanValidity,
    AssumptionTransition,
    PlanAssumption,
    AssumptionRegistry,
    AssumptionDependency,
    AssumptionDependencyGraph,
    AssumptionObservation,
    AssumptionEvaluation,
    AssumptionEvaluator,
    RuleBasedAssumptionEvaluator,
    PlanValidityResult,
    PlanValidityEvaluator,
    ValidityTraceEntry,
    PlanValidityTrace,
    AssumptionContext,
    AssumptionAwareReplanPolicy,
    selective_replanner,
    build_assumption_aware_runner,
    format_assumptions,
    format_validity_trace,
)
from agentic.agentic_framework.working_memory import (
    MemoryState,
    ExpirationKind,
    ExpirationPolicy,
    MemoryStatusTransition,
    MemoryRecord,
    MemoryVersion,
    MemoryAccess,
    MemorySelectionPolicy,
    DeterministicSelectionPolicy,
    MemoryLifecycle,
    MemoryOperation,
    MemoryTrace,
    WorkingMemory,
    MemoryWrite,
    MemoryObservation,
    MemoryAwareObservationBuilder,
    MemoryAssumptionBridge,
    format_working_memory,
    format_memory_trace,
)
from agentic.agentic_framework.coordination import (
    CoordinationState,
    RejectionReason,
    MissionStatus,
    AgentProfile,
    CapabilityRegistry,
    CoordinationGoal,
    Mission,
    DelegationContract,
    AgentAssignment,
    AssignmentTransition,
    GoalOwnershipLedger,
    AuthorityDecision,
    AuthorityModel,
    WorkerResult,
    WorkerExecutor,
    WorkerUnavailable,
    ScriptedWorker,
    AgentWorker,
    CoordinationTraceEntry,
    CoordinationTrace,
    CoordinationResult,
    Coordinator,
    format_coordination_trace,
)
from agentic.agentic_framework.hierarchical_planning import (
    GoalStatus,
    HierarchyStatus,
    Goal,
    GoalTransition,
    GoalNode,
    GoalDependency,
    GoalTree,
    MissionPlan,
    GoalDecomposer,
    StaticDecomposer,
    RuleBasedDecomposer,
    WaveRecord,
    HierarchyTrace,
    HierarchyResult,
    HierarchyExecutor,
    format_goal_tree,
    format_hierarchy_trace,
)
from agentic.agentic_framework.event_workflows import (
    WorkflowStatus,
    WaitKind,
    EventType,
    WaitCondition,
    WorkflowEvent,
    WorkflowTransition,
    WorkflowTraceEntry,
    WorkflowTrace,
    WorkflowInstance,
    WorkflowEngine,
    ResumeEngine,
    format_workflow_trace,
)
from agentic.agentic_framework.workflow_durability import (
    SCHEMA_VERSION,
    EventOutcome,
    AssignmentRecoveryStatus,
    TransactionState,
    FaultPoint,
    RecoveryError,
    CheckpointConflict,
    canonical_json,
    digest_of,
    WorkflowCheckpoint,
    CheckpointSerializer,
    CheckpointIntegrityValidator,
    CheckpointStore,
    InMemoryCheckpointStore,
    FileCheckpointStore,
    EventTransaction,
    RecoveryJournal,
    RecoveryResult,
    WorkflowRestorer,
    FaultInjector,
    DurableWorkflowEngine,
    format_recovery_trace,
)

__all__ = [
    # Main agent
    "AgenticLLMWrapper",
    # Goal decomposition
    "GoalState",
    "ActionItem",
    "decompose_goal",
    "normalize_action_type",
    # Memory
    "AgentMemory",
    "TurnSnapshot",
    "MemoryStore",
    # Reflective generation
    "ReflectiveGenerator",
    "QualityCritic",
    "RuleBasedCritic",
    "LLMBasedCritic",
    "QualityCritique",
    "GenerationResult",
    # Coherence
    "CoherenceMetrics",
    "CoherenceState",
    "CoherenceEngine",
    # Safety
    "SafetyContract",
    "SafetyContractEvaluator",
    # Local Critics (cheap reflection)
    "LocalCritic",
    "OllamaBackend",
    "TransformersBackend",
    "LlamaCppBackend",
    "CostAwareCriticSelector",
    "SelectionStrategy",
    "create_ollama_critic",
    "create_transformers_critic",
    "create_llamacpp_critic",
    "create_cost_aware_critic",
    # Adaptive Policy Engine (policy-level memory)
    "AdaptivePolicyEngine",
    "SessionTrajectory",
    "ToolPermission",
    "PolicyDecision",
    "PolicyParameters",
    "SessionPerformanceHistory",
    "PerformanceSnapshot",
    "create_adaptive_policy_engine",
    # Confidence Gate (behavioral confidence control)
    "ConfidenceGate",
    "ConfidenceSignals",
    "UnifiedConfidence",
    "EscalationLevel",
    "EscalationDecision",
    "ExecutionMode",
    "ExecutionPermission",
    "BudgetAllocation",
    "MemoryWeight",
    "ConfidenceGateDecision",
    "create_confidence_gate",
    "create_strict_confidence_gate",
    "create_permissive_confidence_gate",
    "signals_from_critique",
    "signals_from_coherence_metrics",
    "signals_from_policy_decision",
    "merge_signals",
    # Sovereign State Bridge (V11.0.0: tensor → agentic wiring)
    "signals_from_sovereign_state",
    "coherence_from_sovereign_state",
    "SovereignCoherenceState",
    # MCP Gateway (safe tool integration)
    "SafeMCPGateway",
    "MCPToolCall",
    "MCPToolResult",
    "ToolRiskLevel",
    "ToolRiskClassifier",
    "AuditEntry",
    "MCPClientInterface",
    "MockMCPClient",
    "ToolSpec",
    "create_safe_mcp_gateway",
    "create_mock_mcp_gateway",
    # Agent builder
    "build_agent",
    # Proactive Scheduler (autonomous task execution)
    "ProactiveScheduler",
    "ScheduledTask",
    "ExecutionRecord",
    "CronExpression",
    "TaskStatus",
    "ScheduleType",
    "create_proactive_scheduler",
    "create_task",
    # Cancellation (R2)
    "CancellationToken",
    # Tracing (R11)
    "AgentRunTrace",
    "TraceCollector",
    # Trace viewer (R11)
    "format_trace",
    "format_trace_summary",
    "format_trace_timeline",
    # Structured Output (R6)
    "OutputSchema",
    "SchemaTarget",
    "StructuredRunResult",
    # Streaming Events (R1) + Cancellation event (R2)
    "AgentRunEvent",
    "make_event",
    "RUN_STARTED",
    "GENERATION_STARTED",
    "TEXT_CHUNK",
    "GENERATION_COMPLETED",
    "SAFETY_GATE_RESULT",
    "ACTION_STARTED",
    "ACTION_COMPLETED",
    "RUN_COMPLETED",
    "RUN_ERROR",
    "RUN_CANCELLED",
    "REVISION_STARTED",
    "REVISION_COMPLETED",
    "STRUCTURED_VALIDATION",
    "APPROVAL_REQUESTED",
    "APPROVAL_RESOLVED",
    "USAGE_UPDATED",
    "BUDGET_EXCEEDED",
    # Token / Cost Budget (R9)
    "BudgetPolicy",
    "UsageStats",
    "estimate_tokens",
    # Memory Retention (v2.5)
    "MemoryRetentionPolicy",
    # Approval / Human-in-the-Loop (R4)
    "ApprovalCallback",
    "ApprovalController",
    "ApprovalPolicy",
    "ApprovalResponse",
    "PendingApproval",
    # Approval coverage (R4 + gateway visibility)
    "ApprovalCoverageEntry",
    "describe_approval_coverage",
    "format_approval_coverage",
    # MCP Discovery / Tool Introspection (R8)
    "DiscoveredTool",
    "ToolCatalog",
    # LLM Adapters
    "MockLLMAdapter",
    "SequentialMockAdapter",
    "OpenAIAdapter",
    "AnthropicAdapter",
    "MistralAdapter",
    "MistralCGAdapter",
    # Adaptive Prompts (automated AI reasoning)
    "AutoReasoningPipeline",
    "AdaptivePromptEngine",
    "AdaptivePromptTemplates",
    "ComplexityDetector",
    "ReasoningDepth",
    "ComplexitySignal",
    "ReasoningStage",
    "ComplexityAnalysis",
    "ReasoningStep",
    "AdaptivePromptResult",
    "create_adaptive_pipeline",
    "create_progressive_pipeline",
    "create_always_deep_pipeline",
    "create_conservative_pipeline",
    # Iterate-until-done loop (governed re-planning)
    "Observation",
    "LoopStep",
    "LoopHistory",
    "LoopResult",
    "CompletionVerdict",
    "CompletionChecker",
    "PredicateCompletionChecker",
    "KeywordCompletionChecker",
    "LLMCompletionChecker",
    "IterativeAgentRunner",
    "run_until_done",
    # Multi-agent orchestration & handoff
    "RegisteredAgent",
    "AgentRegistry",
    "AgentTurn",
    "Handoff",
    "RouteDecision",
    "Router",
    "KeywordRouter",
    "LLMRouter",
    "MultiAgentResult",
    "MultiAgentOrchestrator",
    # Cumulative Run Budget (H11) — shared run-level resource governance
    "BudgetDimension",
    "TerminationReason",
    "RunBudgetStatus",
    "RunBudgetLimits",
    "RunBudgetUsage",
    "Reservation",
    "BudgetViolation",
    "BudgetExhausted",
    "RunBudget",
    "BudgetedAdapter",
    "attach_run_budget",
    "format_run_budget",
    # Observation-driven replanning (H12)
    "ObservationStatus",
    "PlanStepState",
    "ReplanDecision",
    "StopReason",
    "PlanObservation",
    "PlanStep",
    "Plan",
    "PlanRevision",
    "ReplanPolicy",
    "DeterministicReplanPolicy",
    "Replanner",
    "RuleBasedReplanner",
    "ObservationBuilder",
    "ScriptedObservationBuilder",
    "DefaultObservationBuilder",
    "StagnationConfig",
    "StagnationDetector",
    "ReplanningResult",
    "ReplanningRunner",
    "format_plan",
    "format_replanning_trace",
    # Plan validity & assumption tracking (H13)
    "AssumptionState",
    "PlanValidity",
    "AssumptionTransition",
    "PlanAssumption",
    "AssumptionRegistry",
    "AssumptionDependency",
    "AssumptionDependencyGraph",
    "AssumptionObservation",
    "AssumptionEvaluation",
    "AssumptionEvaluator",
    "RuleBasedAssumptionEvaluator",
    "PlanValidityResult",
    "PlanValidityEvaluator",
    "ValidityTraceEntry",
    "PlanValidityTrace",
    "AssumptionContext",
    "AssumptionAwareReplanPolicy",
    "selective_replanner",
    "build_assumption_aware_runner",
    "format_assumptions",
    "format_validity_trace",
    # Governed working memory & state continuity (H14)
    "MemoryState",
    "ExpirationKind",
    "ExpirationPolicy",
    "MemoryStatusTransition",
    "MemoryRecord",
    "MemoryVersion",
    "MemoryAccess",
    "MemorySelectionPolicy",
    "DeterministicSelectionPolicy",
    "MemoryLifecycle",
    "MemoryOperation",
    "MemoryTrace",
    "WorkingMemory",
    "MemoryWrite",
    "MemoryObservation",
    "MemoryAwareObservationBuilder",
    "MemoryAssumptionBridge",
    "format_working_memory",
    "format_memory_trace",
    # Authority-aware multi-agent coordination (H16)
    "CoordinationState",
    "RejectionReason",
    "MissionStatus",
    "AgentProfile",
    "CapabilityRegistry",
    "CoordinationGoal",
    "Mission",
    "DelegationContract",
    "AgentAssignment",
    "AssignmentTransition",
    "GoalOwnershipLedger",
    "AuthorityDecision",
    "AuthorityModel",
    "WorkerResult",
    "WorkerExecutor",
    "WorkerUnavailable",
    "ScriptedWorker",
    "AgentWorker",
    "CoordinationTraceEntry",
    "CoordinationTrace",
    "CoordinationResult",
    "Coordinator",
    "format_coordination_trace",
    # Hierarchical planning & goal decomposition (H15)
    "GoalStatus",
    "HierarchyStatus",
    "Goal",
    "GoalTransition",
    "GoalNode",
    "GoalDependency",
    "GoalTree",
    "MissionPlan",
    "GoalDecomposer",
    "StaticDecomposer",
    "RuleBasedDecomposer",
    "WaveRecord",
    "HierarchyTrace",
    "HierarchyResult",
    "HierarchyExecutor",
    "format_goal_tree",
    "format_hierarchy_trace",
    # Event-driven execution & long-lived workflows (H17)
    "WorkflowStatus",
    "WaitKind",
    "EventType",
    "WaitCondition",
    "WorkflowEvent",
    "WorkflowTransition",
    "WorkflowTraceEntry",
    "WorkflowTrace",
    "WorkflowInstance",
    "WorkflowEngine",
    "ResumeEngine",
    "format_workflow_trace",
    # Durable workflow state, checkpointing & recovery (H18)
    "SCHEMA_VERSION",
    "EventOutcome",
    "AssignmentRecoveryStatus",
    "TransactionState",
    "FaultPoint",
    "RecoveryError",
    "CheckpointConflict",
    "canonical_json",
    "digest_of",
    "WorkflowCheckpoint",
    "CheckpointSerializer",
    "CheckpointIntegrityValidator",
    "CheckpointStore",
    "InMemoryCheckpointStore",
    "FileCheckpointStore",
    "EventTransaction",
    "RecoveryJournal",
    "RecoveryResult",
    "WorkflowRestorer",
    "FaultInjector",
    "DurableWorkflowEngine",
    "format_recovery_trace",
]

__version__ = "1.18.0"  # + H18 durable workflow checkpointing & deterministic recovery
