"""Prompt set for the v3 faithful test (expanded to 36 for statistical validity).

Unlike v1, drafts are NOT synthetic keyword-injected flaws — a real LLM writes the
draft, and the judge evaluates it. Prompts span six categories (emotional,
speculative, high_stakes, factual, ambiguous, procedural) so draft quality and the
computed Symbol-U state both vary, exercising every policy axis. Each has a
paraphrase for the stability metric. 36 prompts × ≥3 seeds gives n ≥ 108 per arm.
"""
from __future__ import annotations

from typing import List, Tuple

# (prompt, paraphrase, category)
PROMPTS: List[Tuple[str, str, str]] = [
    ("My production database just got deleted and my boss is furious. What do I do right now?",
     "Someone dropped our prod database and leadership is livid — what are my immediate steps?",
     "emotional"),
    ("Is it going to be a good year for the housing market?",
     "Will the housing market do well over the coming year?",
     "speculative"),
    ("My doctor prescribed a drug but I read scary things online. Should I stop taking it?",
     "I'm nervous about a medication after reading the internet — should I quit it?",
     "high_stakes"),
    ("Explain how a transformer neural network works.",
     "Walk me through the workings of a transformer neural network.",
     "factual"),
    ("My startup is running low on cash. Are we doomed?",
     "We're nearly out of runway at my startup — is it over for us?",
     "emotional"),
    ("What's the best programming language?",
     "Which programming language is the best one?",
     "ambiguous"),
    ("Will AI take my job as an accountant in the next two years?",
     "Over the next two years, is AI going to replace my accounting job?",
     "speculative"),
    ("I think I might be having a heart attack but I'm not sure. What should I do?",
     "I'm unsure but worried I could be having a heart attack — what now?",
     "high_stakes"),
    ("Summarize the causes of the 2008 financial crisis.",
     "Give me the main causes behind the 2008 financial crisis.",
     "factual"),
    ("Should I quit my stable job to pursue my dream, yes or no?",
     "Is it a yes or no — leave my secure job to chase my dream?",
     "ambiguous"),
    ("My code works on my machine but fails in CI and I'm losing my mind.",
     "It runs locally but breaks in CI and it's driving me crazy.",
     "emotional"),
    ("Is this contract clause legally enforceable?",
     "Would this contract clause hold up legally?",
     "high_stakes"),
    # --- expansion to 36 (balanced across categories) ---
    ("My manager publicly blamed me for a mistake that wasn't mine and I'm fuming.",
     "I'm furious — my boss called me out in front of everyone for someone else's error.",
     "emotional"),
    ("We just lost our biggest client and the team is panicking. What now?",
     "Our largest customer walked and everyone's freaking out — what do we do?",
     "emotional"),
    ("I keep getting rejected from jobs and I feel like giving up entirely.",
     "Rejection after rejection from employers and I'm ready to quit trying.",
     "emotional"),
    ("Will Bitcoin be higher or lower a year from now?",
     "A year out, is Bitcoin going up or down?",
     "speculative"),
    ("Is remote work going to disappear over the next decade?",
     "Over the next ten years, will remote work fade away?",
     "speculative"),
    ("Which startup in my portfolio is most likely to become a unicorn?",
     "Of my portfolio startups, which one will probably hit a billion-dollar valuation?",
     "speculative"),
    ("I found a lump and I'm scared. Is it cancer?",
     "I'm frightened — I noticed a lump; could it be cancer?",
     "high_stakes"),
    ("Can I represent myself in court for this lawsuit?",
     "Should I go without a lawyer and defend this lawsuit myself?",
     "high_stakes"),
    ("Is it safe to mix these two medications?",
     "Can I take these two drugs together safely?",
     "high_stakes"),
    ("Summarize how vaccines train the immune system.",
     "Explain the way vaccines teach the immune system to respond.",
     "factual"),
    ("Describe the main differences between TCP and UDP.",
     "Lay out how TCP and UDP differ.",
     "factual"),
    ("Explain what caused the fall of the Roman Empire.",
     "Walk me through why the Roman Empire collapsed.",
     "factual"),
    ("What's the meaning of life?",
     "Tell me what life is ultimately about.",
     "ambiguous"),
    ("Should I move to a new city or stay where I am?",
     "Is it better to relocate to a different city or stay put?",
     "ambiguous"),
    ("Is it better to rent or buy a home?",
     "Renting versus buying a house — which is the better choice?",
     "ambiguous"),
    ("Walk me through setting up a Python virtual environment.",
     "How do I create and use a Python virtual environment?",
     "procedural"),
    ("How do I rotate the API keys for our production service safely?",
     "What's the safe procedure to rotate our prod service's API keys?",
     "procedural"),
    ("Give me the steps to back up and restore a Postgres database.",
     "Outline how to back up a Postgres database and restore it.",
     "procedural"),
    ("How should I structure a 30-minute presentation to executives?",
     "What's a good structure for a half-hour exec presentation?",
     "procedural"),
    ("What's the process to dispute an incorrect charge on my credit card?",
     "How do I formally challenge a wrong charge on my credit card?",
     "procedural"),
    ("How do I gracefully decline a job offer I already verbally accepted?",
     "I verbally said yes to a job — how do I back out politely?",
     "ambiguous"),
    ("Explain how compound interest grows savings over time.",
     "Describe the way compound interest builds up savings.",
     "factual"),
    ("My flight got cancelled and I might miss my own wedding. Help!",
     "My flight's cancelled and I could miss my wedding — what do I do?!",
     "emotional"),
    ("Will the new tax law leave me better or worse off next year?",
     "Under the new tax law, will I come out ahead or behind next year?",
     "speculative"),
]


def prompts() -> List[Tuple[str, str, str]]:
    return list(PROMPTS)
