"""Externally supplied structured observations (immutable, advisory).

An observation is **not** generated by the runtime. It is submitted by an
authorized human assessor, a deterministic upstream process, or an imported
approved record. The runtime *validates* it against the published scale — it does
not compute or interpret the value. AI-supplied observations are rejected in
Phase 3B.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import Field, model_validator

from ..common import utc_now
from ..domain.base import DomainModel
from ..errors import DomainValidationError
from ..ontology.taxonomy import ReasonCode
from ..rubrics.scoring_scale import ScaleType
from ..rubrics.uncertainty import UncertaintyLevel
from .status import SupplierType


class Observation(DomainModel):
    """A supplied, validated observation for one criterion. Value is a token."""

    observation_id: str
    workspace_id: str
    criterion_id: str
    capability_id: str
    capability_version: int
    value: str  # canonical string token, validated against the declared scale
    scale_type: ScaleType
    supplied_by: str
    supplier_type: SupplierType
    supplied_at: datetime = Field(default_factory=utc_now)
    evidence_binding_ids: tuple[str, ...] = ()
    uncertainty: Optional[UncertaintyLevel] = None
    reason_codes: tuple[ReasonCode, ...] = ()
    explanation_reference: str = ""

    @model_validator(mode="after")
    def _validate(self) -> "Observation":
        for req in ("observation_id", "workspace_id", "criterion_id",
                    "capability_id", "value", "supplied_by"):
            if not str(getattr(self, req)).strip():
                raise DomainValidationError(f"{req} is required")
        return self