"""
Symbol-U Pipeline Models (v3.0)

Dataclasses representing the main artifacts passed between pipeline stages.

These models provide a clean, typed interface for data flowing through:
    UserRequest -> Persona -> MLCR -> Fusion -> DHA -> Renderer -> RenderedOutput

The design follows the Symbol-U AGI architecture where:
- Persona represents the communicative identity layer
- MLCR handles multi-layer consciousness routing (Bhava awareness)
- Fusion blends HRM/LCM/MoE channels (Kosha integration)
- DHA manages delivery harmonization & adaptation
- Renderer produces the final output surface
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class UserRequest:
    """
    Incoming user request to the pipeline.

    Attributes:
        user_id: Optional identifier for session/user tracking.
        text: The raw query or input text.
        metadata: Additional context (e.g., domain hints, emotional cues).
        render_mode: Output mode preference - minimal / standard / enhanced / regulated.
    """

    text: str
    user_id: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
    render_mode: Optional[str] = None  # e.g., "minimal", "standard", "enhanced", "regulated"

    def __post_init__(self) -> None:
        if not self.text or not self.text.strip():
            raise ValueError("UserRequest.text must be a non-empty string")


@dataclass
class PersonaContext:
    """
    Resolved persona context after persona selection.

    Attributes:
        active_persona_id: The selected persona identifier (e.g., "analyst", "sage", "coach").
        persona_config: Full persona configuration including traits, tone settings, etc.
    """

    active_persona_id: str
    persona_config: Dict[str, Any] = field(default_factory=dict)


@dataclass
class MlcrResult:
    """
    Result from MLCR (Multi-Layer Consciousness RAG) engine.

    Wraps the routing decision including activation plan, explain_log,
    and renderer context generated by MLCR.

    Attributes:
        entries: The raw MLCR output (routing decision dictionary).
        meta: Additional metadata for debugging/tracing.
    """

    entries: Any  # Keep loose - wraps whatever mlcr_engine.route() returns
    meta: Dict[str, Any] = field(default_factory=dict)

    @property
    def explain_log(self) -> Dict[str, Any]:
        """Extract explain_log from MLCR entries if available."""
        if isinstance(self.entries, dict):
            return self.entries.get("explain_log", {})
        return {}

    @property
    def activation_plan(self) -> Dict[str, Any]:
        """Extract activation_plan from MLCR entries if available."""
        if isinstance(self.entries, dict):
            return self.entries.get("activation_plan", {})
        return {}

    @property
    def renderer_context(self) -> Dict[str, Any]:
        """Extract renderer_context from MLCR entries if available."""
        if isinstance(self.entries, dict):
            return self.entries.get("renderer_context", {})
        return {}


@dataclass
class FusionResult:
    """
    Result from Fusion Engine.

    Contains the selected candidate, ranked alternatives, and routing decisions.

    Attributes:
        fused_candidates: The fusion engine result (selected candidate + rankings).
        trace: Trace data for debugging/explainability.
    """

    fused_candidates: Any  # Wraps FusionResult from fusion_engine
    trace: Dict[str, Any] = field(default_factory=dict)

    @property
    def selected_text(self) -> Optional[str]:
        """Extract the selected candidate text if available."""
        if hasattr(self.fused_candidates, "selected_candidate"):
            candidate = self.fused_candidates.selected_candidate
            if hasattr(candidate, "text"):
                return candidate.text
        return None

    @property
    def routing(self) -> Dict[str, Any]:
        """Extract routing decisions from fusion result."""
        if hasattr(self.fused_candidates, "routing"):
            return self.fused_candidates.routing
        return {}


@dataclass
class DhaDecision:
    """
    Decision from DHA (Delivery Harmonization & Adaptation) Engine.

    Captures the delivery adaptation including tone profile, readiness analysis,
    and any safety/resistance flags.

    Attributes:
        guarded_text: The potentially transformed/adapted text.
        tone_profile: Delivery profile (e.g., "sweet_resonance", "inverse_jolt", "symbolic_metaphor").
        readiness_level: User readiness level (HIGH / MEDIUM / LOW).
        resistance_flags: Detected resistance patterns.
        safety_flags: Safety filter results.
        adaptation_notes: Additional adaptation metadata.
    """

    guarded_text: str
    tone_profile: str  # e.g., "sweet_resonance", "inverse_jolt", "symbolic_metaphor"
    readiness_level: str  # HIGH / MEDIUM / LOW
    resistance_flags: Dict[str, Any] = field(default_factory=dict)
    safety_flags: Dict[str, Any] = field(default_factory=dict)
    adaptation_notes: Dict[str, Any] = field(default_factory=dict)


@dataclass
class RenderedOutput:
    """
    Final rendered output from the pipeline.

    Attributes:
        raw_text: The final rendered text content.
        mode: The render mode used (minimal / standard / enhanced / regulated).
        meta: Additional metadata (layers, trace info, etc.).
    """

    raw_text: str
    mode: str
    meta: Dict[str, Any] = field(default_factory=dict)


@dataclass
class PipelineContext:
    """
    Full context object passed through the pipeline stages.

    Accumulates results from each stage for tracing and debugging.
    The router_mode field enables Option C routing (linear for v3.0,
    with future support for adaptive flows).

    Attributes:
        request: The original UserRequest.
        persona: PersonaContext after persona resolution.
        mlcr: MlcrResult after MLCR routing.
        fusion: FusionResult after candidate fusion.
        dha: DhaDecision after delivery harmonization.
        rendered: RenderedOutput after final rendering.
        router_mode: Pipeline routing mode ("linear" for v3.0).
    """

    request: UserRequest
    persona: Optional[PersonaContext] = None
    mlcr: Optional[MlcrResult] = None
    fusion: Optional[FusionResult] = None
    dha: Optional[DhaDecision] = None
    rendered: Optional[RenderedOutput] = None
    router_mode: str = "linear"

    def to_dict(self) -> Dict[str, Any]:
        """Serialize context to dictionary for logging/debugging."""
        return {
            "request": {
                "user_id": self.request.user_id,
                "text": self.request.text,
                "render_mode": self.request.render_mode,
            },
            "persona": {
                "active_persona_id": self.persona.active_persona_id if self.persona else None,
            },
            "mlcr": {
                "has_entries": self.mlcr is not None and self.mlcr.entries is not None,
            },
            "fusion": {
                "has_candidates": self.fusion is not None,
            },
            "dha": {
                "tone_profile": self.dha.tone_profile if self.dha else None,
                "readiness_level": self.dha.readiness_level if self.dha else None,
            },
            "rendered": {
                "mode": self.rendered.mode if self.rendered else None,
                "has_text": self.rendered is not None and bool(self.rendered.raw_text),
            },
            "router_mode": self.router_mode,
        }


# Public exports
__all__ = [
    "UserRequest",
    "PersonaContext",
    "MlcrResult",
    "FusionResult",
    "DhaDecision",
    "RenderedOutput",
    "PipelineContext",
]
