#!/usr/bin/env python3
"""
Authored pilot candidates (PRIVATE). Each carries the three role artifacts and an
adjudication. Tooling projects these into separate role records and enforces
blinding, lifecycle, agreement, duplicate/template, difficulty, sufficiency, and
bias checks. Only ACCEPTED candidates enter the hidden pilot executable corpus.

For unambiguous cases the author's intended graph and the blind annotator's graph
agree (that is the point of a clean case). A few candidates carry deliberate
divergence, ambiguity, or defects to exercise adjudication and the reject/
quarantine gates. ALL DATA SYNTHETIC.
"""

from __future__ import annotations


def _mk(ref, q, docs, cap, pd, rationale, nodes, edges, gov, abstain, factors,
        variation, prov, decision="ACCEPTED", adj="", ann_nodes=None, ann_edges=None,
        ann_gov=None, ann_abstain=None, ambiguity="none", conf=0.9, negctl=None, packet=None):
    intended = {"nodes": nodes, "edges": [tuple(e) for e in edges],
                "governing": gov, "abstain": abstain}
    ann_graph = {"nodes": ann_nodes if ann_nodes is not None else dict(nodes),
                 "edges": [tuple(e) for e in (ann_edges if ann_edges is not None else edges)]}
    a_gov = ann_gov if ann_gov is not None else list(gov)
    a_abs = ann_abstain if ann_abstain is not None else abstain
    pkt = {"abstain": True} if a_abs else (packet or {})
    return {
        "ref": ref, "question": q,
        "documents": [dict(doc_id=d[0], citation=d[1], order=d[2], text=d[3]) for d in docs],
        "intended_capability": cap, "proposed_difficulty": pd,
        "author_rationale": rationale, "intended_graph": intended,
        "ann_graph": ann_graph, "ann_governing": a_gov,
        "ann_defeated": [d for (_s, t, d) in ann_graph["edges"]
                         if t in ("supersedes", "overrides", "governs_over")],
        "ann_abstain": a_abs, "ann_packet": pkt, "ann_ambiguity": ambiguity,
        "ann_confidence": conf, "provenance": prov,
        "difficulty_factors": factors, "variation": variation,
        "decision": decision, "adj_rationale": adj or ("clean; author and annotator agree"),
        "negative_control": negctl,
    }


C = []  # candidate list

# Documented adjudicator overrides for the duplicate/template gate. A near-
# structural match that is a DELIBERATE contrastive pair (same structure, opposite
# outcome) is retained with a recorded rationale rather than quarantined.
DUP_OVERRIDES = {
    "cr_harmful": "Contrastive pair with cr_benign: identical reference-cycle "
                  "structure, OPPOSITE outcome (abstain vs resolvable). Retained to "
                  "test harmful-vs-benign cycle discrimination; not a template copy.",
    "cr_benign": "Contrastive pair with cr_harmful (identical structure, opposite "
                 "outcome). Retained deliberately; not a template copy.",
}

# ============ partial_overrides (need >=2 new) ============================== #
C.append(_mk("po_notice_only", "What notice applies to termination for convenience, and any charge?",
    [("a", "MSA §8 p.9", 0, "Either party may terminate for convenience on ninety days notice, at no charge."),
     ("b", "Rider 2 §1 p.14", 1, "Section 8 is modified solely as to the notice period, now forty-five days; all else stands.")],
    ["partial_overrides"], 3, "Only the notice attribute is overridden; permission and no-charge survive.",
    {"MSA §8 p.9": "Clause", "Rider 2 §1 p.14": "Clause"},
    [("Rider 2 §1 p.14", "amends", "MSA §8 p.9")], ["MSA §8 p.9", "Rider 2 §1 p.14"], False,
    {"n_docs": 2, "n_relationships": 1, "hop_depth": 0}, ["wording"],
    {"Rider 2 §1 p.14|amends|MSA §8 p.9": "modified solely as to the notice period"},
    packet={"tfc": "allowed", "notice_days": 45, "penalty": None}))
C.append(_mk("po_charge_only", "Is termination for convenience permitted, and what is the charge?",
    [("a", "MSA §8 p.9", 0, "Either party may terminate for convenience on sixty days notice, at no charge."),
     ("b", "Amendment 9 §2 p.22", 1, "The no-charge provision of Section 8 is deleted; a one-month charge now applies. The remainder of Section 8 is unaffected.")],
    ["partial_overrides"], 3, "Only the charge attribute changes; permission and notice survive.",
    {"MSA §8 p.9": "Clause", "Amendment 9 §2 p.22": "Clause"},
    [("Amendment 9 §2 p.22", "amends", "MSA §8 p.9")], ["MSA §8 p.9", "Amendment 9 §2 p.22"], False,
    {"n_docs": 2, "n_relationships": 1}, ["wording", "number_format"],
    {"Amendment 9 §2 p.22|amends|MSA §8 p.9": "no-charge provision of Section 8 is deleted"},
    packet={"tfc": "allowed", "notice_days": 60, "penalty": "1 months' fees"}))

# ============ parallel_overrides (>=2 new; one agree, one disagree->abstain) = #
C.append(_mk("parov_agree", "Can this supplier be terminated at will?",
    [("a", "MSA §7 p.8", 0, "Either party may terminate at will on ninety days notice."),
     ("b", "Policy K-3 p.2", 1, "At-will termination of key suppliers is barred, notwithstanding any contract term."),
     ("c", "Directive D-2 p.1", 2, "For designated suppliers, at-will exit is prohibited regardless of contract.")],
    ["parallel_overrides", "multiple_authorities"], 4, "Two authorities override and agree.",
    {"MSA §7 p.8": "Clause", "Policy K-3 p.2": "Policy", "Directive D-2 p.1": "Policy"},
    [("Policy K-3 p.2", "overrides", "MSA §7 p.8"), ("Directive D-2 p.1", "overrides", "MSA §7 p.8")],
    ["Policy K-3 p.2", "Directive D-2 p.1"], False,
    {"n_docs": 3, "n_relationships": 2, "competing_authorities": 2}, ["policy_naming", "voice"],
    {"Policy K-3 p.2|overrides|MSA §7 p.8": "notwithstanding any contract term",
     "Directive D-2 p.1|overrides|MSA §7 p.8": "regardless of contract"},
    packet={"tfc": "prohibited", "notice_days": None, "penalty": None}))
C.append(_mk("parov_disagree", "What notice applies to termination for convenience?",
    [("a", "Policy K-4 p.2", 0, "For this account, termination for convenience requires thirty days notice, notwithstanding the contract."),
     ("b", "Directive D-5 p.1", 1, "For this account, termination for convenience requires ninety days notice, overriding any contract term.")],
    ["parallel_overrides", "unresolvable_conflict"], 4, "Two overriding authorities disagree with no ranking -> abstain.",
    {"Policy K-4 p.2": "Policy", "Directive D-5 p.1": "Policy"},
    [("Policy K-4 p.2", "conflicts_with", "Directive D-5 p.1")], [], True,
    {"n_docs": 2, "n_relationships": 1, "competing_authorities": 2, "must_abstain": True},
    ["policy_naming"], {"Policy K-4 p.2|conflicts_with|Directive D-5 p.1": "notwithstanding the contract"},
    ambiguity="two overriding authorities disagree; no ranking", negctl="unresolvable_conflict",
    adj="parallel overrides disagree with no precedence rule -> abstain is correct"))

# ============ nested_exceptions (>=2 new) =================================== #
C.append(_mk("nest_two_level", "May the customer terminate for convenience in year one?",
    [("a", "MSA §7 p.8", 0, "Either party may terminate for convenience on sixty days notice."),
     ("b", "Schedule E §2 p.15", 1, "During year one the customer may not use that right."),
     ("c", "Schedule E §3 p.16", 2, "That year-one bar does not apply to a material-breach termination.")],
    ["nested_exceptions"], 4, "Exception to an exception.",
    {"MSA §7 p.8": "Clause", "Schedule E §2 p.15": "Exception", "Schedule E §3 p.16": "Exception"},
    [("Schedule E §2 p.15", "exception_to", "MSA §7 p.8"),
     ("Schedule E §3 p.16", "exception_to", "Schedule E §2 p.15")],
    ["MSA §7 p.8"], False, {"n_docs": 3, "n_relationships": 2, "exception_nesting": 2},
    ["wording", "explicit_implicit"],
    {"Schedule E §2 p.15|exception_to|MSA §7 p.8": "may not use that right",
     "Schedule E §3 p.16|exception_to|Schedule E §2 p.15": "does not apply to a material-breach"},
    ambiguity="year-one convenience exit restricted; nested carve-out is for breach, not convenience",
    packet={"tfc": "allowed", "notice_days": 60, "penalty": None}))
C.append(_mk("nest_scope_narrow", "Can the buyer exit for convenience?",
    [("a", "Frame §5 p.4", 0, "The buyer may exit for convenience on thirty days notice."),
     ("b", "Annex 2 §1 p.20", 1, "This right is suspended during any renewal negotiation."),
     ("c", "Annex 2 §2 p.21", 2, "The suspension in the preceding clause is limited to the first renewal only.")],
    ["nested_exceptions", "scoped_exceptions"], 4, "Nested, scope-narrowing exception.",
    {"Frame §5 p.4": "Clause", "Annex 2 §1 p.20": "Exception", "Annex 2 §2 p.21": "Exception"},
    [("Annex 2 §1 p.20", "exception_to", "Frame §5 p.4"),
     ("Annex 2 §2 p.21", "exception_to", "Annex 2 §1 p.20")],
    ["Frame §5 p.4"], False, {"n_docs": 3, "n_relationships": 2, "exception_nesting": 2},
    ["wording"], {"Annex 2 §1 p.20|exception_to|Frame §5 p.4": "suspended during any renewal negotiation",
                  "Annex 2 §2 p.21|exception_to|Annex 2 §1 p.20": "limited to the first renewal only"},
    ambiguity="exit right stands outside first-renewal window",
    packet={"tfc": "allowed", "notice_days": 30, "penalty": None}))

# ============ multi_hop (>=2 new) =========================================== #
C.append(_mk("mh_three_hop", "What is the early-termination charge?",
    [("a", "Order §4 p.1", 0, "The charge is as set out in Schedule B."),
     ("b", "Schedule B p.12", 1, "The charge is as set out in Annex 3."),
     ("c", "Annex 3 p.19", 2, "The charge is as set out in Exhibit Z."),
     ("d", "Exhibit Z p.30", 3, "The early-termination charge is five months of fees.")],
    ["multi_hop", "cross_document_reference"], 4, "Three reference hops to a ground term.",
    {"Order §4 p.1": "Clause", "Schedule B p.12": "Clause", "Annex 3 p.19": "Clause", "Exhibit Z p.30": "Clause"},
    [("Order §4 p.1", "references", "Schedule B p.12"), ("Schedule B p.12", "references", "Annex 3 p.19"),
     ("Annex 3 p.19", "references", "Exhibit Z p.30")],
    ["Order §4 p.1", "Schedule B p.12", "Annex 3 p.19", "Exhibit Z p.30"], False,
    {"n_docs": 4, "n_relationships": 3, "hop_depth": 3}, ["doc_granularity"],
    {"Order §4 p.1|references|Schedule B p.12": "set out in Schedule B",
     "Schedule B p.12|references|Annex 3 p.19": "set out in Annex 3",
     "Annex 3 p.19|references|Exhibit Z p.30": "set out in Exhibit Z"},
    packet={"tfc": "unknown", "notice_days": None, "penalty": "5 months' fees"}))
C.append(_mk("mh_mixed_implicit", "Where is the governing fee, and what is it?",
    [("a", "MSA §9 p.10", 0, "Fees follow the current rate card."),
     ("b", "Rate Card p.25", 1, "Termination fees are those in the fee appendix."),
     ("c", "Fee Appendix p.33", 2, "The termination fee is three months of charges.")],
    ["multi_hop", "implicit_references"], 3, "Two hops, first implicit ('current rate card').",
    {"MSA §9 p.10": "Clause", "Rate Card p.25": "Clause", "Fee Appendix p.33": "Clause"},
    [("MSA §9 p.10", "references", "Rate Card p.25"), ("Rate Card p.25", "references", "Fee Appendix p.33")],
    ["MSA §9 p.10", "Rate Card p.25", "Fee Appendix p.33"], False,
    {"n_docs": 3, "n_relationships": 2, "hop_depth": 2}, ["explicit_implicit"],
    {"MSA §9 p.10|references|Rate Card p.25": "follow the current rate card",
     "Rate Card p.25|references|Fee Appendix p.33": "those in the fee appendix"},
    packet={"tfc": "unknown", "notice_days": None, "penalty": "3 months' fees"}))

# ============ table_vs_text (>=2 new) ======================================= #
C.append(_mk("tvt_notice", "What notice applies to termination for convenience?",
    [("a", "MSA §7 p.8", 0, "Termination for convenience requires ninety days notice."),
     ("b", "Notice Table Exhibit C p.40", 1, "Row: Convenience | Notice: 30 days.")],
    ["table_vs_text"], 3, "Prose vs table disagree on notice; no precedence -> flag.",
    {"MSA §7 p.8": "Clause", "Notice Table Exhibit C p.40": "Table"},
    [("MSA §7 p.8", "conflicts_with", "Notice Table Exhibit C p.40")], ["MSA §7 p.8"], False,
    {"n_docs": 2, "n_relationships": 1, "cross_format": True, "ambiguity": True},
    ["table_prose", "number_format"],
    {"MSA §7 p.8|conflicts_with|Notice Table Exhibit C p.40": "Notice: 30 days"},
    ambiguity="prose 90 vs table 30; unresolved without precedence",
    packet={"tfc": "allowed", "notice_days": None, "penalty": None}))
C.append(_mk("tvt_table_wins", "What is the early-termination penalty?",
    [("a", "MSA §7.3 p.8", 0, "The early-termination penalty is two months of fees."),
     ("b", "Charges Table Exhibit D p.41", 1, "The tables in the Exhibits prevail over the body. Row: Early termination | 4 months of fees.")],
    ["table_vs_text", "appendix_precedence"], 3, "Table asserts precedence over prose.",
    {"MSA §7.3 p.8": "Clause", "Charges Table Exhibit D p.41": "Table"},
    [("Charges Table Exhibit D p.41", "governs_over", "MSA §7.3 p.8")],
    ["Charges Table Exhibit D p.41"], False,
    {"n_docs": 2, "n_relationships": 1, "cross_format": True}, ["table_prose"],
    {"Charges Table Exhibit D p.41|governs_over|MSA §7.3 p.8": "Exhibits prevail over the body"},
    packet={"tfc": "unknown", "notice_days": None, "penalty": "4 months' fees"}))

# ============ appendix_precedence (>=2 new) ================================= #
C.append(_mk("apx_prevails", "Is termination for convenience permitted?",
    [("a", "MSA §7 p.8", 0, "Termination for convenience is not permitted."),
     ("b", "Appendix K §1 p.50", 1, "In case of inconsistency, this Appendix controls over the Agreement body. Termination for convenience is permitted on ninety days notice.")],
    ["appendix_precedence"], 3, "Appendix asserts precedence.",
    {"MSA §7 p.8": "Clause", "Appendix K §1 p.50": "Clause"},
    [("Appendix K §1 p.50", "governs_over", "MSA §7 p.8")], ["Appendix K §1 p.50"], False,
    {"n_docs": 2, "n_relationships": 1}, ["wording"],
    {"Appendix K §1 p.50|governs_over|MSA §7 p.8": "this Appendix controls over the Agreement body"},
    packet={"tfc": "allowed", "notice_days": 90, "penalty": None}))
C.append(_mk("apx_body_wins", "Does the appendix override the body here?",
    [("a", "MSA §2 p.3", 0, "The body of this Agreement prevails over any Appendix, which is illustrative only."),
     ("b", "Appendix M §1 p.52", 1, "Termination for convenience is barred."),
     ("c", "MSA §7 p.8", 2, "Termination for convenience is permitted on sixty days notice.")],
    ["appendix_precedence", "hierarchical_governance"], 4, "Body asserts precedence over appendix (reverse of the usual).",
    {"MSA §2 p.3": "Policy", "Appendix M §1 p.52": "Clause", "MSA §7 p.8": "Clause"},
    [("MSA §7 p.8", "governs_over", "Appendix M §1 p.52")], ["MSA §7 p.8"], False,
    {"n_docs": 3, "n_relationships": 1, "distractor_paths": 1}, ["wording", "doc_granularity"],
    {"MSA §7 p.8|governs_over|Appendix M §1 p.52": "body of this Agreement prevails over any Appendix"},
    ambiguity="reverse precedence: body beats appendix",
    packet={"tfc": "allowed", "notice_days": 60, "penalty": None}))

# ============ entity_renaming (>=2 new) ===================================== #
C.append(_mk("rename_party", "May the Provider terminate for convenience?",
    [("a", "MSA §1 p.2", 0, "Acme Corp (the 'Provider') and Beta LLC (the 'Client') agree as follows."),
     ("b", "Novation p.5", 1, "Acme Corp is renamed Acme Global; all references to Acme Corp mean Acme Global."),
     ("c", "MSA §7 p.8", 2, "The Provider may terminate for convenience on forty-five days notice.")],
    ["entity_renaming"], 3, "Party renamed; the right still attaches to the Provider.",
    {"MSA §1 p.2": "Definition", "Novation p.5": "Clause", "MSA §7 p.8": "Clause"},
    [("Novation p.5", "same_as", "MSA §1 p.2")], ["MSA §7 p.8"], False,
    {"n_docs": 3, "n_relationships": 1, "distractor_paths": 1}, ["entity_names"],
    {"Novation p.5|same_as|MSA §1 p.2": "all references to Acme Corp mean Acme Global"},
    packet={"tfc": "allowed", "notice_days": 45, "penalty": None}))
C.append(_mk("rename_policy_ref", "Which policy governs, after renaming?",
    [("a", "MSA §7 p.8", 0, "Termination for convenience is permitted on sixty days notice."),
     ("b", "Policy N-1 p.2", 1, "Policy N-1 is now published as Standard S-9; cite S-9 going forward."),
     ("c", "Standard S-9 p.1", 2, "Termination for convenience of audited accounts is prohibited, notwithstanding any contract term.")],
    ["entity_renaming", "policy_migration"], 4, "Policy renamed; renamed policy overrides for audited accounts.",
    {"MSA §7 p.8": "Clause", "Policy N-1 p.2": "Policy", "Standard S-9 p.1": "Policy"},
    [("Standard S-9 p.1", "same_as", "Policy N-1 p.2"), ("Standard S-9 p.1", "overrides", "MSA §7 p.8")],
    ["Standard S-9 p.1"], False, {"n_docs": 3, "n_relationships": 2, "competing_authorities": 1},
    ["policy_naming", "entity_names"],
    {"Standard S-9 p.1|same_as|Policy N-1 p.2": "now published as Standard S-9",
     "Standard S-9 p.1|overrides|MSA §7 p.8": "notwithstanding any contract term"},
    ambiguity="assumes an audited account",
    packet={"tfc": "prohibited", "notice_days": None, "penalty": None}))

# ============ conditional_applicability (>=2 new) =========================== #
C.append(_mk("cond_geo", "Is termination for convenience available for an EU deployment?",
    [("a", "MSA §7 p.8", 0, "Termination for convenience is permitted on ninety days notice."),
     ("b", "Rider 6 §1 p.16", 1, "For deployments in the EU, termination for convenience is unavailable; elsewhere the MSA applies.")],
    ["conditional_applicability", "scoped_exceptions"], 4, "Applicability conditioned on region.",
    {"MSA §7 p.8": "Clause", "Rider 6 §1 p.16": "Exception"},
    [("Rider 6 §1 p.16", "exception_to", "MSA §7 p.8")], ["MSA §7 p.8"], False,
    {"n_docs": 2, "n_relationships": 1, "ambiguity": True, "distractor_paths": 1}, ["explicit_implicit"],
    {"Rider 6 §1 p.16|exception_to|MSA §7 p.8": "For deployments in the EU"},
    ambiguity="EU deployment flips to unavailable; condition not asserted here",
    packet={"tfc": "allowed", "notice_days": 90, "penalty": None}))
C.append(_mk("cond_tier", "Can a Bronze-tier customer terminate for convenience?",
    [("a", "MSA §7 p.8", 0, "Termination for convenience is permitted on sixty days notice."),
     ("b", "Service Tiers §3 p.11", 1, "The convenience right applies only to Gold-tier customers.")],
    ["conditional_applicability"], 3, "Applicability conditioned on tier.",
    {"MSA §7 p.8": "Clause", "Service Tiers §3 p.11": "Exception"},
    [("Service Tiers §3 p.11", "exception_to", "MSA §7 p.8")], ["MSA §7 p.8"], False,
    {"n_docs": 2, "n_relationships": 1, "ambiguity": True}, ["wording"],
    {"Service Tiers §3 p.11|exception_to|MSA §7 p.8": "applies only to Gold-tier customers"},
    ambiguity="Bronze tier -> right does not apply; Gold -> applies",
    packet={"tfc": "allowed", "notice_days": 60, "penalty": None}))

# ============ negative controls: no_relationship (>=2) ====================== #
C.append(_mk("nr_wrong_topic", "What notice applies to termination for convenience?",
    [("a", "SLA §1 p.1", 0, "Uptime shall be at least 99.9 percent measured monthly."),
     ("b", "DPA §2 p.3", 1, "Personal data shall be processed only on documented instructions.")],
    ["no_relationship"], 2, "No document addresses termination.",
    {"SLA §1 p.1": "Clause", "DPA §2 p.3": "Clause"}, [], [], True,
    {"n_docs": 2, "n_relationships": 0, "must_abstain": True}, ["doc_granularity"], {},
    negctl="no_relationship", adj="queried relationship absent -> abstain"))
C.append(_mk("nr_adjacent", "Is termination for convenience permitted?",
    [("a", "MSA §6 p.7", 0, "Either party may terminate for material breach uncured after thirty days."),
     ("b", "MSA §10 p.11", 1, "Notices shall be delivered in writing.")],
    ["no_relationship"], 2, "Only for-cause termination exists; convenience not addressed.",
    {"MSA §6 p.7": "Clause", "MSA §10 p.11": "Clause"}, [], [], True,
    {"n_docs": 2, "n_relationships": 0, "must_abstain": True, "distractor_paths": 1}, ["wording"], {},
    ambiguity="for-cause present but convenience is not addressed", negctl="no_relationship",
    adj="convenience right absent; for-cause is a distractor -> abstain"))

# ============ negative controls: unresolvable_conflict (>=2) ================ #
C.append(_mk("uc_same_rank", "What notice applies to termination for convenience?",
    [("a", "Amendment P (effective 2024-02-01) p.2", 0, "Convenience termination requires thirty days notice."),
     ("b", "Amendment Q (effective 2024-02-01) p.2", 1, "Convenience termination requires ninety days notice.")],
    ["unresolvable_conflict", "conflicting_amendments"], 4, "Same effective date, no tie-break.",
    {"Amendment P (effective 2024-02-01) p.2": "Clause", "Amendment Q (effective 2024-02-01) p.2": "Clause"},
    [("Amendment P (effective 2024-02-01) p.2", "conflicts_with", "Amendment Q (effective 2024-02-01) p.2")],
    [], True, {"n_docs": 2, "n_relationships": 1, "temporal": True, "must_abstain": True},
    ["date_format"], {"Amendment P (effective 2024-02-01) p.2|conflicts_with|Amendment Q (effective 2024-02-01) p.2": "requires thirty days"},
    ambiguity="identical effective dates, contradictory terms", negctl="unresolvable_conflict"))
C.append(_mk("uc_two_precedence", "Which document governs on termination?",
    [("a", "Order Form §1 p.1", 0, "The Order Form prevails over the MSA."),
     ("b", "MSA §2 p.2", 1, "The MSA prevails over any Order Form."),
     ("c", "MSA §7 p.8", 2, "Convenience termination is permitted on sixty days notice.")],
    ["unresolvable_conflict", "hierarchical_governance"], 5, "Two documents each claim precedence.",
    {"Order Form §1 p.1": "Policy", "MSA §2 p.2": "Policy", "MSA §7 p.8": "Clause"},
    [("Order Form §1 p.1", "conflicts_with", "MSA §2 p.2")], [], True,
    {"n_docs": 3, "n_relationships": 1, "competing_authorities": 2, "must_abstain": True, "distractor_paths": 1},
    ["wording"], {"Order Form §1 p.1|conflicts_with|MSA §2 p.2": "Order Form prevails over the MSA"},
    ambiguity="mutually asserted precedence; unresolvable", negctl="unresolvable_conflict"))

# ============ negative controls: insufficient_evidence (>=2) ================ #
C.append(_mk("ie_absent_schedule", "What is the termination penalty?",
    [("a", "Order §5 p.1", 0, "The termination penalty is stated in the Master Fee Schedule.")],
    ["insufficient_evidence", "implicit_references"], 3, "Value deferred to an absent document.",
    {"Order §5 p.1": "Clause"}, [("Order §5 p.1", "references", "Master Fee Schedule")], [], True,
    {"n_docs": 1, "n_relationships": 1, "must_abstain": True}, ["explicit_implicit"],
    {"Order §5 p.1|references|Master Fee Schedule": "stated in the Master Fee Schedule"},
    negctl="insufficient_evidence"))
C.append(_mk("ie_undefined_term", "How long is the Cure Period for termination?",
    [("a", "MSA §6 p.7", 0, "Termination for cause requires expiry of the Cure Period."),
     ("b", "MSA §1 p.2", 1, "Capitalised terms have the meanings given where first used.")],
    ["insufficient_evidence"], 3, "A decisive term is never defined.",
    {"MSA §6 p.7": "Clause", "MSA §1 p.2": "Clause"}, [], [], True,
    {"n_docs": 2, "n_relationships": 0, "must_abstain": True}, ["wording"], {},
    ambiguity="Cure Period undefined; cannot compute", negctl="insufficient_evidence"))

# ============ negative controls: circular_reference (harmful + benign) ====== #
C.append(_mk("cr_harmful", "What is the termination fee?",
    [("a", "MSA §7 p.8", 0, "The termination fee is that stated in the Schedule."),
     ("b", "Schedule p.20", 1, "The termination fee is that stated in the MSA.")],
    ["circular_reference"], 3, "Harmful cycle: no ground term.",
    {"MSA §7 p.8": "Clause", "Schedule p.20": "Clause"},
    [("MSA §7 p.8", "references", "Schedule p.20"), ("Schedule p.20", "references", "MSA §7 p.8")],
    [], True, {"n_docs": 2, "n_relationships": 2, "hop_depth": 2, "must_abstain": True}, ["wording"],
    {"MSA §7 p.8|references|Schedule p.20": "stated in the Schedule",
     "Schedule p.20|references|MSA §7 p.8": "stated in the MSA"},
    negctl="circular_reference", adj="reference cycle with no ground term -> abstain"))
C.append(_mk("cr_benign", "What is the termination fee?",
    [("a", "MSA §7 p.8", 0, "The termination fee is that stated in the Schedule."),
     ("b", "Schedule p.20", 1, "The termination fee is that stated in the MSA. For the avoidance of doubt, it is two months of fees.")],
    ["circular_reference", "cross_document_reference"], 4, "Benign cycle: despite the loop a ground value is stated.",
    {"MSA §7 p.8": "Clause", "Schedule p.20": "Clause"},
    [("MSA §7 p.8", "references", "Schedule p.20"), ("Schedule p.20", "references", "MSA §7 p.8")],
    ["Schedule p.20"], False,
    {"n_docs": 2, "n_relationships": 2, "hop_depth": 2, "ambiguity": True, "distractor_paths": 1}, ["wording"],
    {"MSA §7 p.8|references|Schedule p.20": "stated in the Schedule",
     "Schedule p.20|references|MSA §7 p.8": "stated in the MSA"},
    ambiguity="cycle present but a ground term ('two months of fees') resolves it",
    packet={"tfc": "unknown", "notice_days": None, "penalty": "2 months' fees"},
    adj="benign cycle: ground value present -> resolvable, not abstain"))

C.append(_mk("cr_harmful_defs", "How is the Fee determined?",
    [("a", "Order §2 p.1", 0, "The Fee is as defined in the Glossary."),
     ("b", "Glossary p.9", 1, "Fee is as defined in the Order.")],
    ["circular_reference"], 3, "Definitional cycle with no ground value.",
    {"Order §2 p.1": "Clause", "Glossary p.9": "Clause"},
    [("Order §2 p.1", "references", "Glossary p.9"), ("Glossary p.9", "references", "Order §2 p.1")],
    [], True, {"n_docs": 2, "n_relationships": 2, "hop_depth": 2, "must_abstain": True}, ["wording"],
    {"Order §2 p.1|references|Glossary p.9": "defined in the Glossary",
     "Glossary p.9|references|Order §2 p.1": "defined in the Order"},
    negctl="circular_reference", adj="definitional cycle, no ground term -> abstain"))

# ============ negative controls: multiple_valid_interpretations (>=2) ======= #
C.append(_mk("mvi_undefined_control", "Does 'Change of Control' include a 40% share acquisition?",
    [("a", "MSA §1 p.2", 0, "Change of Control means an acquisition of a controlling interest."),
     ("b", "MSA §1.2 p.2", 1, "The threshold for a controlling interest is not specified.")],
    ["multiple_valid_interpretations", "definition_inheritance"], 4, "Threshold unspecified -> multiple readings.",
    {"MSA §1 p.2": "Definition", "MSA §1.2 p.2": "Clause"}, [], [], True,
    {"n_docs": 2, "n_relationships": 0, "ambiguity": True, "must_abstain": True}, ["wording"], {},
    ambiguity="40% may or may not be 'controlling'; unspecified", negctl="multiple_valid_interpretations"))
C.append(_mk("mvi_scope_ambiguous", "Does the termination right apply to renewals?",
    [("a", "MSA §7 p.8", 0, "Either party may terminate for convenience during the Term."),
     ("b", "MSA §3 p.4", 1, "The Term may be followed by renewal terms.")],
    ["multiple_valid_interpretations"], 3, "'Term' vs 'renewal terms' scope is genuinely ambiguous.",
    {"MSA §7 p.8": "Clause", "MSA §3 p.4": "Clause"}, [], [], True,
    {"n_docs": 2, "n_relationships": 0, "ambiguity": True, "must_abstain": True}, ["wording"], {},
    ambiguity="whether 'the Term' includes renewal terms is unsettled", negctl="multiple_valid_interpretations"))

# ============ Level-5 deep cases (>=5) ====================================== #
C.append(_mk("l5_order_migration_date", "Is convenience termination permitted, and on what notice?",
    [("a", "MSA §7 p.8", 0, "Convenience termination is permitted on ninety days notice."),
     ("b", "Order Form §2 (effective 2019) p.1", 1, "For this order, convenience termination requires thirty days notice; the Order Form prevails over the MSA."),
     ("c", "Policy T-1 p.2", 2, "Policy T-1 is migrated to Policy T-2."),
     ("d", "Policy T-2 (effective 2025) p.1", 3, "For strategic accounts, convenience termination is prohibited, notwithstanding any order or contract.")],
    ["multiple_authorities", "policy_migration", "effective_date_precedence", "hierarchical_governance"], 5,
    "Hierarchy + migration + date + override.",
    {"MSA §7 p.8": "Clause", "Order Form §2 (effective 2019) p.1": "Clause",
     "Policy T-1 p.2": "Policy", "Policy T-2 (effective 2025) p.1": "Policy"},
    [("Order Form §2 (effective 2019) p.1", "governs_over", "MSA §7 p.8"),
     ("Policy T-2 (effective 2025) p.1", "supersedes", "Policy T-1 p.2"),
     ("Policy T-2 (effective 2025) p.1", "overrides", "Order Form §2 (effective 2019) p.1")],
    ["Policy T-2 (effective 2025) p.1"], False,
    {"n_docs": 4, "n_relationships": 3, "competing_authorities": 2, "temporal": True, "distractor_paths": 2},
    ["policy_naming", "date_format", "doc_order"],
    {"Order Form §2 (effective 2019) p.1|governs_over|MSA §7 p.8": "Order Form prevails over the MSA",
     "Policy T-2 (effective 2025) p.1|supersedes|Policy T-1 p.2": "migrated to Policy T-2",
     "Policy T-2 (effective 2025) p.1|overrides|Order Form §2 (effective 2019) p.1": "notwithstanding any order or contract"},
    ambiguity="assumes a strategic account", packet={"tfc": "prohibited", "notice_days": None, "penalty": None}))
C.append(_mk("l5_nested_conditional_table", "What penalty applies to an EU convenience termination?",
    [("a", "MSA §7.3 p.8", 0, "The penalty is three months of fees."),
     ("b", "Penalty Table Exhibit E p.42", 1, "The Exhibit tables prevail over the body. Row: EU convenience | 5 months of fees."),
     ("c", "Rider 7 §1 p.17", 2, "For non-EU deployments the table does not apply.")],
    ["table_vs_text", "conditional_applicability", "appendix_precedence"], 5, "Table precedence + conditional scope.",
    {"MSA §7.3 p.8": "Clause", "Penalty Table Exhibit E p.42": "Table", "Rider 7 §1 p.17": "Exception"},
    [("Penalty Table Exhibit E p.42", "governs_over", "MSA §7.3 p.8"),
     ("Rider 7 §1 p.17", "exception_to", "Penalty Table Exhibit E p.42")],
    ["Penalty Table Exhibit E p.42"], False,
    {"n_docs": 3, "n_relationships": 2, "cross_format": True, "ambiguity": True, "distractor_paths": 1},
    ["table_prose", "explicit_implicit"],
    {"Penalty Table Exhibit E p.42|governs_over|MSA §7.3 p.8": "Exhibit tables prevail over the body",
     "Rider 7 §1 p.17|exception_to|Penalty Table Exhibit E p.42": "For non-EU deployments the table does not apply"},
    ambiguity="EU deployment assumed; non-EU reverts to prose",
    packet={"tfc": "unknown", "notice_days": None, "penalty": "5 months' fees"}))
C.append(_mk("l5_transitive_defs_governance", "Does the confidentiality survival clause bind a renamed affiliate?",
    [("a", "MSA §1 p.2", 0, "Affiliate means an entity under common control; Group means a party and its Affiliates."),
     ("b", "MSA §11 p.12", 1, "Confidentiality binds each member of the Group."),
     ("c", "Novation p.5", 2, "Sub-Co is renamed Sub-Global; references carry over."),
     ("d", "Org Chart p.6", 3, "Sub-Global is under common control with the Client.")],
    ["definition_inheritance", "transitive_authority", "entity_renaming"], 5, "Definition chain + renaming to bind an entity.",
    {"MSA §1 p.2": "Definition", "MSA §11 p.12": "Clause", "Novation p.5": "Clause", "Org Chart p.6": "Document"},
    [("MSA §11 p.12", "references", "MSA §1 p.2"), ("Novation p.5", "same_as", "Org Chart p.6")],
    ["MSA §11 p.12", "MSA §1 p.2"], False,
    {"n_docs": 4, "n_relationships": 2, "hop_depth": 1, "ambiguity": True, "distractor_paths": 1},
    ["entity_names"], {"MSA §11 p.12|references|MSA §1 p.2": "each member of the Group",
                       "Novation p.5|same_as|Org Chart p.6": "references carry over"},
    ambiguity="binding depends on chaining Affiliate->Group->renamed entity",
    packet={"tfc": "unknown", "notice_days": None, "penalty": None}))
C.append(_mk("l5_effective_conflict_ledger", "What notice governs after three amendments?",
    [("a", "Amd R (effective 2021) p.2", 0, "Convenience notice is ninety days."),
     ("b", "Amd S (effective 2023) p.2", 1, "Convenience notice is sixty days."),
     ("c", "Amd T (effective 2023) p.2", 2, "Convenience notice is thirty days."),
     ("d", "Execution Ledger p.1", 3, "On the 2023 effective date, Amd T was executed after Amd S.")],
    ["effective_date_precedence", "conflicting_amendments", "version_supersession"], 5,
    "Latest effective date has two amendments; ledger breaks the tie.",
    {"Amd R (effective 2021) p.2": "Clause", "Amd S (effective 2023) p.2": "Clause",
     "Amd T (effective 2023) p.2": "Clause", "Execution Ledger p.1": "Document"},
    [("Amd S (effective 2023) p.2", "effective_after", "Amd R (effective 2021) p.2"),
     ("Amd T (effective 2023) p.2", "supersedes", "Amd S (effective 2023) p.2")],
    ["Amd T (effective 2023) p.2"], False,
    {"n_docs": 4, "n_relationships": 2, "temporal": True, "distractor_paths": 2},
    ["date_format", "doc_granularity"],
    {"Amd S (effective 2023) p.2|effective_after|Amd R (effective 2021) p.2": "sixty days",
     "Amd T (effective 2023) p.2|supersedes|Amd S (effective 2023) p.2": "Amd T was executed after Amd S"},
    ambiguity="tie on 2023 resolved by execution order",
    packet={"tfc": "allowed", "notice_days": 30, "penalty": None}))
C.append(_mk("l5_parallel_scoped_override", "Can a regulated EU customer terminate for convenience?",
    [("a", "MSA §7 p.8", 0, "Convenience termination is permitted on sixty days notice."),
     ("b", "Policy U-1 p.2", 1, "For regulated customers, convenience termination is prohibited, notwithstanding any contract term."),
     ("c", "Rider 8 §1 p.18", 2, "Policy U-1 does not apply outside the EU.")],
    ["parallel_overrides", "conditional_applicability", "scoped_exceptions"], 5,
    "A policy override that is itself scoped by a rider.",
    {"MSA §7 p.8": "Clause", "Policy U-1 p.2": "Policy", "Rider 8 §1 p.18": "Exception"},
    [("Policy U-1 p.2", "overrides", "MSA §7 p.8"), ("Rider 8 §1 p.18", "exception_to", "Policy U-1 p.2")],
    ["Policy U-1 p.2"], False,
    {"n_docs": 3, "n_relationships": 2, "competing_authorities": 1, "ambiguity": True, "distractor_paths": 1},
    ["policy_naming", "explicit_implicit"],
    {"Policy U-1 p.2|overrides|MSA §7 p.8": "notwithstanding any contract term",
     "Rider 8 §1 p.18|exception_to|Policy U-1 p.2": "does not apply outside the EU"},
    ambiguity="EU+regulated -> prohibited; non-EU -> permitted",
    packet={"tfc": "prohibited", "notice_days": None, "penalty": None}))

# ============ genuinely deep (4+ operation) Level-5 cases =================== #
C.append(_mk("l5_five_hop_chain", "What is the early-termination charge?",
    [("a", "Order §4 p.1", 0, "The charge is as set out in Schedule B."),
     ("b", "Schedule B p.12", 1, "The charge is as set out in Annex 3."),
     ("c", "Annex 3 p.19", 2, "The charge is as set out in Exhibit Z."),
     ("d", "Exhibit Z p.30", 3, "The charge is as set out in Rider Q."),
     ("e", "Rider Q p.44", 4, "The early-termination charge is six months of fees.")],
    ["multi_hop", "cross_document_reference", "transitive_authority"], 5, "Four-hop reference chain.",
    {"Order §4 p.1": "Clause", "Schedule B p.12": "Clause", "Annex 3 p.19": "Clause",
     "Exhibit Z p.30": "Clause", "Rider Q p.44": "Clause"},
    [("Order §4 p.1", "references", "Schedule B p.12"), ("Schedule B p.12", "references", "Annex 3 p.19"),
     ("Annex 3 p.19", "references", "Exhibit Z p.30"), ("Exhibit Z p.30", "references", "Rider Q p.44")],
    ["Order §4 p.1", "Schedule B p.12", "Annex 3 p.19", "Exhibit Z p.30", "Rider Q p.44"], False,
    {"n_docs": 5, "n_relationships": 4, "hop_depth": 4}, ["doc_granularity"],
    {"Order §4 p.1|references|Schedule B p.12": "set out in Schedule B",
     "Schedule B p.12|references|Annex 3 p.19": "set out in Annex 3",
     "Annex 3 p.19|references|Exhibit Z p.30": "set out in Exhibit Z",
     "Exhibit Z p.30|references|Rider Q p.44": "set out in Rider Q"},
    packet={"tfc": "unknown", "notice_days": None, "penalty": "6 months' fees"}))
C.append(_mk("l5_four_authority_stack", "Is convenience termination permitted?",
    [("a", "MSA §7 p.8", 0, "Convenience termination is permitted on ninety days notice."),
     ("b", "Order Form §2 (effective 2020) p.1", 1, "The Order Form prevails over the MSA; convenience notice is thirty days."),
     ("c", "Policy V-1 p.2", 2, "Policy V-1 is migrated to Policy V-2."),
     ("d", "Policy V-2 (effective 2025) p.1", 3, "For regulated suppliers, convenience termination is prohibited, notwithstanding any order or contract.")],
    ["multiple_authorities", "hierarchical_governance", "policy_migration", "effective_date_precedence"], 5,
    "Four-authority stack: hierarchy + migration + date + override.",
    {"MSA §7 p.8": "Clause", "Order Form §2 (effective 2020) p.1": "Clause",
     "Policy V-1 p.2": "Policy", "Policy V-2 (effective 2025) p.1": "Policy"},
    [("Order Form §2 (effective 2020) p.1", "governs_over", "MSA §7 p.8"),
     ("Policy V-2 (effective 2025) p.1", "supersedes", "Policy V-1 p.2"),
     ("Policy V-2 (effective 2025) p.1", "overrides", "Order Form §2 (effective 2020) p.1")],
    ["Policy V-2 (effective 2025) p.1"], False,
    {"n_docs": 4, "n_relationships": 3, "competing_authorities": 2, "temporal": True, "distractor_paths": 2},
    ["policy_naming", "date_format"],
    {"Order Form §2 (effective 2020) p.1|governs_over|MSA §7 p.8": "Order Form prevails over the MSA",
     "Policy V-2 (effective 2025) p.1|supersedes|Policy V-1 p.2": "migrated to Policy V-2",
     "Policy V-2 (effective 2025) p.1|overrides|Order Form §2 (effective 2020) p.1": "notwithstanding any order or contract"},
    ambiguity="assumes a regulated supplier", packet={"tfc": "prohibited", "notice_days": None, "penalty": None}))
C.append(_mk("l5_triple_nested_exception", "May the buyer exit for convenience in month two?",
    [("a", "MSA §7 p.8", 0, "The buyer may exit for convenience on thirty days notice."),
     ("b", "Sched F §1 p.15", 1, "During the first year the buyer may not exercise that right."),
     ("c", "Sched F §2 p.16", 2, "The year-one bar does not apply to a change-of-control exit."),
     ("d", "Sched F §3 p.17", 3, "The change-of-control carve-out is itself unavailable in the first month.")],
    ["nested_exceptions", "scoped_exceptions"], 5, "Three-level nested exceptions.",
    {"MSA §7 p.8": "Clause", "Sched F §1 p.15": "Exception", "Sched F §2 p.16": "Exception",
     "Sched F §3 p.17": "Exception"},
    [("Sched F §1 p.15", "exception_to", "MSA §7 p.8"),
     ("Sched F §2 p.16", "exception_to", "Sched F §1 p.15"),
     ("Sched F §3 p.17", "exception_to", "Sched F §2 p.16")],
    ["MSA §7 p.8"], False,
    {"n_docs": 4, "n_relationships": 3, "exception_nesting": 3, "ambiguity": True}, ["wording"],
    {"Sched F §1 p.15|exception_to|MSA §7 p.8": "may not exercise that right",
     "Sched F §2 p.16|exception_to|Sched F §1 p.15": "does not apply to a change-of-control",
     "Sched F §3 p.17|exception_to|Sched F §2 p.16": "unavailable in the first month"},
    ambiguity="month-two change-of-control exit turns on three nested carve-outs",
    packet={"tfc": "allowed", "notice_days": 30, "penalty": None}))
C.append(_mk("l5_table_override_scope_date", "What penalty applies to a 2025 EU convenience termination?",
    [("a", "MSA §7.3 p.8", 0, "The penalty is two months of fees."),
     ("b", "Penalty Table Exhibit G (effective 2024) p.42", 1, "Exhibit tables prevail over the body. Row: EU convenience | 6 months of fees."),
     ("c", "Rider 9 §1 p.18", 2, "The Exhibit G table applies only from 2025 onward."),
     ("d", "Rider 9 §2 p.19", 3, "For non-EU deployments Exhibit G does not apply.")],
    ["table_vs_text", "appendix_precedence", "conditional_applicability", "effective_date_precedence"], 5,
    "Table precedence + effective-date gate + scope condition.",
    {"MSA §7.3 p.8": "Clause", "Penalty Table Exhibit G (effective 2024) p.42": "Table",
     "Rider 9 §1 p.18": "Exception", "Rider 9 §2 p.19": "Exception"},
    [("Penalty Table Exhibit G (effective 2024) p.42", "governs_over", "MSA §7.3 p.8"),
     ("Rider 9 §1 p.18", "exception_to", "Penalty Table Exhibit G (effective 2024) p.42"),
     ("Rider 9 §2 p.19", "exception_to", "Penalty Table Exhibit G (effective 2024) p.42")],
    ["Penalty Table Exhibit G (effective 2024) p.42"], False,
    {"n_docs": 4, "n_relationships": 3, "cross_format": True, "temporal": True, "ambiguity": True, "distractor_paths": 1},
    ["table_prose", "date_format"],
    {"Penalty Table Exhibit G (effective 2024) p.42|governs_over|MSA §7.3 p.8": "Exhibit tables prevail over the body",
     "Rider 9 §1 p.18|exception_to|Penalty Table Exhibit G (effective 2024) p.42": "applies only from 2025 onward",
     "Rider 9 §2 p.19|exception_to|Penalty Table Exhibit G (effective 2024) p.42": "non-EU deployments Exhibit G does not apply"},
    ambiguity="2025 EU -> table 6 months; earlier or non-EU -> prose 2 months",
    packet={"tfc": "unknown", "notice_days": None, "penalty": "6 months' fees"}))

# ============ variation coverage: sentence_structure + clause_numbering ===== #
C.append(_mk("var_passive_nominal", "Is convenience termination available to the customer?",
    [("a", "MSA §7 p.8", 0, "Termination for convenience by the customer is not to be permitted."),
     ("b", "Amendment 12 §1 p.24", 1, "By this amendment, the prohibition in Section 7 is removed and a sixty-day notice right is granted to the customer.")],
    ["version_supersession"], 2, "Passive/nominalised phrasing throughout.",
    {"MSA §7 p.8": "Clause", "Amendment 12 §1 p.24": "Clause"},
    [("Amendment 12 §1 p.24", "supersedes", "MSA §7 p.8")], ["Amendment 12 §1 p.24"], False,
    {"n_docs": 2, "n_relationships": 1}, ["sentence_structure", "voice"],
    {"Amendment 12 §1 p.24|supersedes|MSA §7 p.8": "the prohibition in Section 7 is removed"},
    packet={"tfc": "allowed", "notice_days": 60, "penalty": None}))
C.append(_mk("var_inconsistent_numbering", "What notice governs termination for convenience?",
    [("a", "MSA §7.1 p.8", 0, "Convenience termination requires ninety days notice."),
     ("b", "Amendment 13 §1 p.26", 1, "Clause 7.01 (being the same as Section 7.1) is replaced; the notice period becomes forty days.")],
    ["version_supersession"], 3, "Inconsistent numbering (7.1 vs 7.01) with an explicit alias.",
    {"MSA §7.1 p.8": "Clause", "Amendment 13 §1 p.26": "Clause"},
    [("Amendment 13 §1 p.26", "same_as", "MSA §7.1 p.8"),
     ("Amendment 13 §1 p.26", "supersedes", "MSA §7.1 p.8")], ["Amendment 13 §1 p.26"], False,
    {"n_docs": 2, "n_relationships": 2}, ["clause_numbering", "number_format"],
    {"Amendment 13 §1 p.26|same_as|MSA §7.1 p.8": "being the same as Section 7.1",
     "Amendment 13 §1 p.26|supersedes|MSA §7.1 p.8": "is replaced"},
    packet={"tfc": "allowed", "notice_days": 40, "penalty": None}))

# ============ deliberate REJECT / QUARANTINE (exercise the gates) ========== #
C.append(_mk("rej_nonunique_gold", "Which notice governs?",
    [("a", "Amendment U p.2", 0, "Convenience notice is thirty days."),
     ("b", "Amendment V p.3", 1, "Convenience notice is sixty days.")],
    ["conflicting_amendments"], 3, "Author labelled Amendment V determinate, but nothing ranks them.",
    {"Amendment U p.2": "Clause", "Amendment V p.3": "Clause"},
    [("Amendment V p.3", "supersedes", "Amendment U p.2")], ["Amendment V p.3"], False,
    {"n_docs": 2, "n_relationships": 1}, ["wording"],
    {"Amendment V p.3|supersedes|Amendment U p.2": "sixty days"},
    ann_edges=[("Amendment U p.3", "conflicts_with", "Amendment V p.3")], ann_gov=[], ann_abstain=True,
    decision="REJECTED",
    adj="evidence does not uniquely support the supersedes edge; no ordering given -> more than one governance outcome valid but labelled determinate. REJECT."))
C.append(_mk("rej_resolvable_abstain", "What notice governs?",
    [("a", "MSA §7 p.8", 0, "Convenience notice is ninety days."),
     ("b", "Amendment W p.2", 1, "Section 7 is deleted and replaced; convenience notice is thirty days.")],
    ["version_supersession"], 2, "Author labelled this an abstention, but it is clearly resolvable.",
    {"MSA §7 p.8": "Clause", "Amendment W p.2": "Clause"},
    [("Amendment W p.2", "supersedes", "MSA §7 p.8")], [], True,
    {"n_docs": 2, "n_relationships": 1, "must_abstain": True}, ["wording"],
    {"Amendment W p.2|supersedes|MSA §7 p.8": "deleted and replaced"},
    ann_gov=["Amendment W p.2"], ann_abstain=False, decision="REJECTED",
    adj="abstention labelled but the case is resolvable (clear supersession) -> REJECT (must not mislabel abstention)."))
C.append(_mk("quar_template_dup", "What notice applies to termination for convenience, and any charge?",
    [("a", "MSA §8 p.9", 0, "Either party may terminate for convenience on ninety days notice, at no charge."),
     ("b", "Rider 2 §1 p.14", 1, "Section 8 is modified solely as to the notice period, now forty-five days; everything else stands.")],
    ["partial_overrides"], 3, "Near-duplicate reasoning template of an accepted pilot case (one word changed).",
    {"MSA §8 p.9": "Clause", "Rider 2 §1 p.14": "Clause"},
    [("Rider 2 §1 p.14", "amends", "MSA §8 p.9")], ["MSA §8 p.9", "Rider 2 §1 p.14"], False,
    {"n_docs": 2, "n_relationships": 1}, ["wording"],
    {"Rider 2 §1 p.14|amends|MSA §8 p.9": "modified solely as to the notice period"},
    packet={"tfc": "allowed", "notice_days": 45, "penalty": None}, decision="QUARANTINED",
    adj="near-identical text + identical graph signature vs an accepted case -> shared reasoning template -> QUARANTINE."))
C.append(_mk("rej_external_knowledge", "Is termination permitted under the applicable statute?",
    [("a", "MSA §7 p.8", 0, "Termination is permitted as allowed by applicable law.")],
    ["conditional_applicability"], 3, "Answer requires unstated external legal knowledge.",
    {"MSA §7 p.8": "Clause"}, [], ["MSA §7 p.8"], False,
    {"n_docs": 1, "n_relationships": 0}, ["wording"], {},
    packet={"tfc": "unknown", "notice_days": None, "penalty": None}, decision="REJECTED",
    adj="the graph requires unstated external (statutory) knowledge to resolve -> REJECT."))
C.append(_mk("rej_obscure_wording", "May the counterparty rescind ad libitum?",
    [("a", "MSA §7 p.8", 0, "The counterparty may rescind ad libitum sine die upon lawful intimation."),
     ("b", "Amendment 14 p.2", 1, "The aforesaid faculty is hereby extinguished mutatis mutandis.")],
    ["version_supersession"], 4, "Difficulty is driven by obscure wording, not reasoning depth.",
    {"MSA §7 p.8": "Clause", "Amendment 14 p.2": "Clause"},
    [("Amendment 14 p.2", "supersedes", "MSA §7 p.8")], ["Amendment 14 p.2"], False,
    {"n_docs": 2, "n_relationships": 1}, ["wording"],
    {"Amendment 14 p.2|supersedes|MSA §7 p.8": "faculty is hereby extinguished"},
    packet={"tfc": "prohibited", "notice_days": None, "penalty": None}, decision="REJECTED",
    adj="difficulty depends primarily on obscure vocabulary rather than reasoning depth -> REJECT."))
