"""Stable scenario taxonomy (Task 101).

Every scenario declares its taxonomy labels explicitly. These enums are the
frozen vocabulary the dataset, evaluators, and metrics agree on.
"""
from __future__ import annotations

from enum import Enum


class AssertionClass(str, Enum):
    FULLY_SUPPORTED = "FULLY_SUPPORTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    UNSUPPORTED_COMPONENT = "UNSUPPORTED_COMPONENT"
    CONTRADICTORY_EVIDENCE = "CONTRADICTORY_EVIDENCE"
    MISSING_EVIDENCE = "MISSING_EVIDENCE"
    OMITTED_QUALIFIER = "OMITTED_QUALIFIER"
    SCOPE_EXPANSION = "SCOPE_EXPANSION"
    CERTAINTY_INFLATION = "CERTAINTY_INFLATION"
    TEMPORAL_MISMATCH = "TEMPORAL_MISMATCH"
    POPULATION_OR_SEGMENT_MISMATCH = "POPULATION_OR_SEGMENT_MISMATCH"
    METRIC_MISMATCH = "METRIC_MISMATCH"
    SOURCE_AUTHORITY_MISMATCH = "SOURCE_AUTHORITY_MISMATCH"


class ActionClass(str, Enum):
    AUTHORIZED = "AUTHORIZED"
    AUTHORIZED_WITH_LIMIT = "AUTHORIZED_WITH_LIMIT"
    AUTHORIZED_WITH_APPROVAL = "AUTHORIZED_WITH_APPROVAL"
    AUTHORIZED_WITH_NOTIFICATION = "AUTHORIZED_WITH_NOTIFICATION"
    AUTHORIZED_WITH_EXPIRY = "AUTHORIZED_WITH_EXPIRY"
    DENIED_BY_POLICY = "DENIED_BY_POLICY"
    DENIED_BY_AUTHORITY = "DENIED_BY_AUTHORITY"
    DENIED_BY_RESOURCE_SCOPE = "DENIED_BY_RESOURCE_SCOPE"
    INDETERMINATE_POLICY = "INDETERMINATE_POLICY"
    PROVIDER_TIMEOUT = "PROVIDER_TIMEOUT"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    MALFORMED_PROVIDER_RESULT = "MALFORMED_PROVIDER_RESULT"
    EXECUTION_BUSINESS_FAILURE = "EXECUTION_BUSINESS_FAILURE"
    EXECUTION_TRANSPORT_FAILURE = "EXECUTION_TRANSPORT_FAILURE"
    RECONCILIATION_MISMATCH = "RECONCILIATION_MISMATCH"
    OBLIGATION_NOT_SATISFIED = "OBLIGATION_NOT_SATISFIED"


class CrossProviderClass(str, Enum):
    SUPPORTED_ASSERTION_AUTHORIZED_ACTION = "SUPPORTED_ASSERTION_AUTHORIZED_ACTION"
    CONSTRAINED_ASSERTION_CONSTRAINED_ACTION = "CONSTRAINED_ASSERTION_CONSTRAINED_ACTION"
    UNSUPPORTED_ASSERTION_NO_ACTION = "UNSUPPORTED_ASSERTION_NO_ACTION"
    INDETERMINATE_ASSERTION_HUMAN_REVIEW = "INDETERMINATE_ASSERTION_HUMAN_REVIEW"
    SUPPORTED_ASSERTION_ACTION_DENIED = "SUPPORTED_ASSERTION_ACTION_DENIED"
    ASSERTION_PROVIDER_FAILURE = "ASSERTION_PROVIDER_FAILURE"
    ACTION_PROVIDER_FAILURE = "ACTION_PROVIDER_FAILURE"
    BOTH_PROVIDERS_AVAILABLE = "BOTH_PROVIDERS_AVAILABLE"
    ONE_PROVIDER_DEGRADED = "ONE_PROVIDER_DEGRADED"


class ObligationState(str, Enum):
    """Explicit obligation state model (Task 108)."""

    PENDING = "PENDING"
    SATISFIED = "SATISFIED"
    FAILED = "FAILED"
    WAIVED_BY_AUTHORITY = "WAIVED_BY_AUTHORITY"
    EXPIRED = "EXPIRED"


class ExecutionBehavior(str, Enum):
    """What the workflow should do at the execution stage (ground truth)."""

    NOT_DISPATCHED = "NOT_DISPATCHED"                 # denied / indeterminate / unsupported
    DISPATCH_BLOCKED_BY_CONSTRAINT = "DISPATCH_BLOCKED_BY_CONSTRAINT"  # outside envelope
    DISPATCHED_SUCCESS = "DISPATCHED_SUCCESS"
    EXECUTION_FAILED = "EXECUTION_FAILED"             # business failure
    TRANSPORT_FAILED = "TRANSPORT_FAILED"


class ReconciliationExpectation(str, Enum):
    NONE = "NONE"                                     # never dispatched
    RECONCILED = "RECONCILED"
    MISMATCHED = "MISMATCHED"
    FAILED = "FAILED"


class RecommendationPosture(str, Enum):
    ADVANCE = "ADVANCE"
    HOLD = "HOLD"
    REJECT = "REJECT"
    REQUEST_ADDITIONAL_EVIDENCE = "REQUEST_ADDITIONAL_EVIDENCE"


#: Governance-compliance verdict, kept distinct from execution success (Task 108).
class ComplianceVerdict(str, Enum):
    COMPLIANT = "COMPLIANT"
    NONCOMPLIANT = "NONCOMPLIANT"
    NOT_APPLICABLE = "NOT_APPLICABLE"


DOMAINS = ("procurement", "finance_operations", "refund_operations")
