"""
Symbol-U Pipeline Models (v3.0)

Dataclasses representing the main artifacts passed between pipeline stages.

These models provide a clean, typed interface for data flowing through:
    UserRequest -> Persona -> MLCR -> Fusion -> DHA -> Renderer -> RenderedOutput

The design follows the Symbol-U AGI architecture where:
- Persona represents the communicative identity layer
- MLCR handles multi-layer consciousness routing (Bhava awareness)
- Fusion blends HRM/LCM/LAM/MoE channels (Kosha integration)
- DHA manages delivery harmonization & adaptation
- Renderer produces the final output surface
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from symbolu.core.coherence import CoherenceState
    from symbolu.mechanical.pipeline.grounding.phase_minus_one_schema import PhaseMinusOneEnvelope
    from symbolu.mechanical.pipeline.phase_zero.phase_zero_schema import IntentEnvelope
    from symbolu.mechanical.pipeline.phase_one.phase_one_schema import AllowedActionSet
    from symbolu.mechanical.pipeline.phase_po4.po4_schema import PlannerProposalEnvelope
    from symbolu.mechanical.pipeline.phase_po5.po5_schema import ExecutionEligibilityEnvelope
    from symbolu.mechanical.pipeline.phase_p6.p6_schema import RegimeEnvelope
    from symbolu.mechanical.pipeline.p7_discourse.p7_discourse_schema import DiscourseEnvelope
    from symbolu.mechanical.pipeline.p8_semantics.p8_semantic_schema import SemanticFrame
    from symbolu.mechanical.pipeline.p9_lexical.p9_lexical_schema import LexicalFrame
    from symbolu.mechanical.pipeline.p10_acoustic.p10_acoustic_schema import AcousticParameterFrame
    from symbolu.mechanical.pipeline.p11_prosodic.p11_prosodic_schema import ProsodicEvidenceFrame
    from symbolu.mechanical.pipeline.p12_consistency.p12_consistency_schema import P12ConsistencyReport
    from symbolu.mechanical.pipeline.p13_acoustic_safety.p13_acoustic_safety_schema import AcousticSafetyEnvelope
    from symbolu.mechanical.pipeline.p14_surface.p14_surface_schema import SurfacePlan


@dataclass
class UserRequest:
    """
    Incoming user request to the pipeline.

    Attributes:
        user_id: Optional identifier for session/user tracking.
        text: The raw query or input text.
        metadata: Additional context (e.g., domain hints, emotional cues).
        render_mode: Output mode preference - minimal / standard / enhanced / regulated.
    """

    text: str
    user_id: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
    render_mode: Optional[str] = None  # e.g., "minimal", "standard", "enhanced", "regulated"

    def __post_init__(self) -> None:
        if not self.text or not self.text.strip():
            raise ValueError("UserRequest.text must be a non-empty string")


@dataclass
class PersonaContext:
    """
    Resolved persona context after persona selection.

    Attributes:
        active_persona_id: The selected persona identifier (e.g., "analyst", "sage", "coach").
        persona_config: Full persona configuration including traits, tone settings, etc.
    """

    active_persona_id: str
    persona_config: Dict[str, Any] = field(default_factory=dict)


@dataclass
class MlcrResult:
    """
    Result from MLCR (Multi-Layer Consciousness RAG) engine.

    Wraps the routing decision including activation plan, explain_log,
    and renderer context generated by MLCR.

    Attributes:
        entries: The raw MLCR output (routing decision dictionary).
        meta: Additional metadata for debugging/tracing.
    """

    entries: Any  # Keep loose - wraps whatever mlcr_engine.route() returns
    meta: Dict[str, Any] = field(default_factory=dict)

    @property
    def explain_log(self) -> Dict[str, Any]:
        """Extract explain_log from MLCR entries if available."""
        if isinstance(self.entries, dict):
            return self.entries.get("explain_log", {})
        return {}

    @property
    def activation_plan(self) -> Dict[str, Any]:
        """Extract activation_plan from MLCR entries if available."""
        if isinstance(self.entries, dict):
            return self.entries.get("activation_plan", {})
        return {}

    @property
    def renderer_context(self) -> Dict[str, Any]:
        """Extract renderer_context from MLCR entries if available."""
        if isinstance(self.entries, dict):
            return self.entries.get("renderer_context", {})
        return {}


@dataclass
class FusionResult:
    """
    Result from Fusion Engine.

    Contains the selected candidate, ranked alternatives, and routing decisions.

    Attributes:
        fused_candidates: The fusion engine result (selected candidate + rankings).
        trace: Trace data for debugging/explainability.
    """

    fused_candidates: Any  # Wraps FusionResult from fusion_engine
    trace: Dict[str, Any] = field(default_factory=dict)

    @property
    def selected_text(self) -> Optional[str]:
        """Extract the selected candidate text if available."""
        if hasattr(self.fused_candidates, "selected_candidate"):
            candidate = self.fused_candidates.selected_candidate
            if hasattr(candidate, "text"):
                return candidate.text
        return None

    @property
    def routing(self) -> Dict[str, Any]:
        """Extract routing decisions from fusion result."""
        if hasattr(self.fused_candidates, "routing"):
            return self.fused_candidates.routing
        return {}


@dataclass
class DhaDecision:
    """
    Decision from DHA (Delivery Harmonization & Adaptation) Engine.

    Captures the delivery adaptation including tone profile, readiness analysis,
    and any safety/resistance flags.

    Attributes:
        guarded_text: The potentially transformed/adapted text.
        tone_profile: Delivery profile (e.g., "sweet_resonance", "inverse_jolt", "symbolic_metaphor").
        readiness_level: User readiness level (HIGH / MEDIUM / LOW).
        resistance_flags: Detected resistance patterns.
        safety_flags: Safety filter results.
        adaptation_notes: Additional adaptation metadata.
    """

    guarded_text: str
    tone_profile: str  # e.g., "sweet_resonance", "inverse_jolt", "symbolic_metaphor"
    readiness_level: str  # HIGH / MEDIUM / LOW
    resistance_flags: Dict[str, Any] = field(default_factory=dict)
    safety_flags: Dict[str, Any] = field(default_factory=dict)
    adaptation_notes: Dict[str, Any] = field(default_factory=dict)


@dataclass
class RenderedOutput:
    """
    Final rendered output from the pipeline.

    Attributes:
        raw_text: The final rendered text content.
        mode: The render mode used (minimal / standard / enhanced / regulated).
        meta: Additional metadata (layers, trace info, etc.).
    """

    raw_text: str
    mode: str
    meta: Dict[str, Any] = field(default_factory=dict)


@dataclass
class MapperProfile:
    """
    Mapper influence profile for renderer and DHA modulation.

    Computed deterministically from HRM/LCM/LAM activation flags
    and routing signals. Used to modulate expression (NOT semantic truth).

    Attributes:
        resolution_level: "low" | "medium" | "high" - Detail granularity
        arc_mode: "none" | "temporal" | "identity" | "deep_context" - Long-arc framing
        detail_bias: 0.0–1.0 - Preference for fine-grained detail
        practical_bias: 0.0–1.0 - Preference for concrete/task-focused delivery
        reflective_bias: 0.0–1.0 - Preference for introspective/philosophical framing
        guna_resonance_bias: 0.0 - Phase 9 Guna resonance modulation [-0.10, +0.10]
        kosha_resonance_bias: 0.0 - Phase 9 Kosha resonance modulation [-0.10, +0.10]
        expression_harmonics: None - Phase 9 expression harmonics from kosha vector
        symbolic_harmony_bias: None - Phase 28 Symbolic harmony bias [-0.05, +0.05]
        symbolic_resonance_tags: None - Phase 28 Symbolic resonance tags (HIGH_HARMONY/MEDIUM/LOW)
    """

    resolution_level: str = "medium"  # "low" | "medium" | "high"
    arc_mode: str = "none"  # "none" | "temporal" | "identity" | "deep_context"
    detail_bias: float = 0.5  # 0.0–1.0
    practical_bias: float = 0.5  # 0.0–1.0
    reflective_bias: float = 0.5  # 0.0–1.0

    # Phase 9: Guna/Kosha resonance biases (observation-only modulation)
    guna_resonance_bias: float = 0.0  # [-0.10, +0.10]
    kosha_resonance_bias: float = 0.0  # [-0.10, +0.10]
    expression_harmonics: Optional[List[float]] = None  # Derived from kosha_activation_vector

    # Phase 28: Symbolic Harmonization biases (renderer-only modulation)
    symbolic_harmony_bias: Optional[float] = None  # Symbolic richness bias [-0.05, +0.05]
    symbolic_resonance_tags: Optional[List[str]] = None  # HIGH_HARMONY | MEDIUM_HARMONY | LOW_HARMONY

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "resolution_level": self.resolution_level,
            "arc_mode": self.arc_mode,
            "detail_bias": self.detail_bias,
            "practical_bias": self.practical_bias,
            "reflective_bias": self.reflective_bias,
            "guna_resonance_bias": self.guna_resonance_bias,
            "kosha_resonance_bias": self.kosha_resonance_bias,
            "expression_harmonics": self.expression_harmonics,
            "symbolic_harmony_bias": self.symbolic_harmony_bias,
            "symbolic_resonance_tags": self.symbolic_resonance_tags,
        }


@dataclass
class PipelineContext:
    """
    Full context object passed through the pipeline stages.

    Accumulates results from each stage for tracing and debugging.
    The router_mode field enables Option C routing (linear for v3.0,
    with future support for adaptive flows).

    Attributes:
        request: The original UserRequest.
        persona: PersonaContext after persona resolution.
        mlcr: MlcrResult after MLCR routing.
        phase_minus_one: PhaseMinusOneEnvelope from Phase −1 grounding analysis.
        phase_zero: IntentEnvelope from Phase 0 intent resolution.
        allowed_actions: AllowedActionSet from Phase 1 action binding.
        po4_proposal: PlannerProposalEnvelope from PO4 planner proposal validation.
        po5_execution_eligibility: ExecutionEligibilityEnvelope from PO5 execution gate (non-actuating).
        p6_regime: RegimeEnvelope from P6 regime selection gate (gating-only).
        p7_discourse_envelope: DiscourseEnvelope from P7 discourse act resolver (gating-only).
        semantic_frame: SemanticFrame from P8 semantic slot resolver (gating-only).
        lexical_frame: LexicalFrame from P9 lexical selection engine (gating-only).
        p10_acoustic: AcousticParameterFrame from P10 acoustic parameterization (gating-only).
        p11_prosodic_evidence: ProsodicEvidenceFrame from P11 prosodic evidence capture (witness-only).
        p12_consistency: P12ConsistencyReport from P12 consistency validation (audit-only).
        p13_safety_envelope: AcousticSafetyEnvelope from P13 acoustic safety (binding).
        p14_surface: SurfacePlan from P14 expression surface realizer (surface-shaping).
        hrm_map: Optional HighResolutionMap from HRM engine (when use_hrm=True).
        lcm_map: Optional LowContextMap from LCM engine (when use_lcm=True).
        lam_map: Optional LongArcMap from LAM engine (when use_lam=True or long_arc_tension high).
        fusion: FusionResult after candidate fusion.
        dha: DhaDecision after delivery harmonization.
        rendered: RenderedOutput after final rendering.
        router_mode: Pipeline routing mode ("linear" for v3.0).
        mapper_profile: Mapper influence profile for renderer/DHA modulation.
        coherence_state: Optional CoherenceState tracking multi-turn conversation coherence.
        coherence_report: Optional observability report dict from CoherenceObserver.
    """

    request: UserRequest
    persona: Optional[PersonaContext] = None
    mlcr: Optional[MlcrResult] = None
    phase_minus_one: Optional["PhaseMinusOneEnvelope"] = None  # Phase −1 grounding envelope
    phase_zero: Optional["IntentEnvelope"] = None  # Phase 0 intent envelope
    allowed_actions: Optional["AllowedActionSet"] = None  # Phase 1 allowed action set
    po4_proposal: Optional["PlannerProposalEnvelope"] = None  # PO4 planner proposal envelope
    po5_execution_eligibility: Optional["ExecutionEligibilityEnvelope"] = None  # PO5 execution eligibility envelope
    p6_regime: Optional["RegimeEnvelope"] = None  # P6 regime selection envelope
    p7_discourse_envelope: Optional["DiscourseEnvelope"] = None  # P7 discourse act envelope
    semantic_frame: Optional["SemanticFrame"] = None  # P8 semantic slot resolution frame
    lexical_frame: Optional["LexicalFrame"] = None  # P9 lexical selection frame
    p10_acoustic: Optional["AcousticParameterFrame"] = None  # P10 acoustic parameterization frame
    p11_prosodic_evidence: Optional["ProsodicEvidenceFrame"] = None  # P11 prosodic evidence frame
    p12_consistency: Optional["P12ConsistencyReport"] = None  # P12 consistency validation report
    p13_safety_envelope: Optional["AcousticSafetyEnvelope"] = None  # P13 acoustic safety envelope (binding)
    p14_surface: Optional["SurfacePlan"] = None  # P14 expression surface plan (surface-shaping)
    hrm_map: Optional[Any] = None  # HighResolutionMap from HRM engine
    lcm_map: Optional[Any] = None  # LowContextMap from LCM engine
    lam_map: Optional[Any] = None  # LongArcMap from LAM engine
    fusion: Optional[FusionResult] = None
    dha: Optional[DhaDecision] = None
    rendered: Optional[RenderedOutput] = None
    router_mode: str = "linear"
    mapper_profile: Optional[MapperProfile] = None
    coherence_state: Optional["CoherenceState"] = None  # Multi-turn coherence tracking
    coherence_report: Optional[Dict[str, Any]] = None  # Observability report from CoherenceObserver
    unified_output: Optional[Dict[str, Any]] = None  # Unified API output (USU-API v1.0)

    # Phase 1 temporal formulas (observation only - not used in routing/behavior yet)
    smi: Optional[float] = None  # Symbolic Mental Index (0.0 to 1.0)
    delta_smi: Optional[float] = None  # SMI momentum (-1.0 to 1.0)
    bhava_gap: Optional[float] = None  # Bhava circular distance (0.0 to 1.0)
    tension_corridor: Optional[float] = None  # Tension dynamics signal (0.0 to 1.0)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize context to dictionary for logging/debugging."""
        return {
            "request": {
                "user_id": self.request.user_id,
                "text": self.request.text,
                "render_mode": self.request.render_mode,
            },
            "persona": {
                "active_persona_id": self.persona.active_persona_id if self.persona else None,
            },
            "mlcr": {
                "has_entries": self.mlcr is not None and self.mlcr.entries is not None,
            },
            "phase_minus_one": {
                "has_envelope": self.phase_minus_one is not None,
                "overall_policy": self.phase_minus_one.overall_policy.value if self.phase_minus_one else None,
                "clause_count": len(self.phase_minus_one.clauses) if self.phase_minus_one else 0,
                "is_blocked": self.phase_minus_one.is_blocked() if self.phase_minus_one else False,
            },
            "phase_zero": {
                "has_envelope": self.phase_zero is not None,
                "intent_type": self.phase_zero.intent_type.value if self.phase_zero else None,
                "response_posture": self.phase_zero.response_posture.value if self.phase_zero else None,
                "planning_allowed": self.phase_zero.planning_allowed if self.phase_zero else None,
            },
            "phase_one": {
                "has_allowed_actions": self.allowed_actions is not None,
                "intent_type": self.allowed_actions.intent_type.value if self.allowed_actions else None,
                "action_count": self.allowed_actions.count() if self.allowed_actions else 0,
                "is_empty": self.allowed_actions.is_empty() if self.allowed_actions else None,
                "allowed_actions": sorted([a.value for a in self.allowed_actions.allowed_actions]) if self.allowed_actions else [],
            },
            "po4": {
                "has_proposal": self.po4_proposal is not None,
                "status": self.po4_proposal.status.value if self.po4_proposal else None,
                "intent": self.po4_proposal.intent.value if self.po4_proposal else None,
                "allowed_count": self.po4_proposal.allowed_count() if self.po4_proposal else 0,
                "rejected_count": self.po4_proposal.rejected_count() if self.po4_proposal else 0,
                "proposed_count": self.po4_proposal.proposed_count() if self.po4_proposal else 0,
                "blocked_reason": self.po4_proposal.blocked_reason if self.po4_proposal else None,
            },
            "po5": {
                "has_eligibility": self.po5_execution_eligibility is not None,
                "eligibility": self.po5_execution_eligibility.eligibility.value if self.po5_execution_eligibility else None,
                "intent": self.po5_execution_eligibility.intent.value if self.po5_execution_eligibility else None,
                "proposal_status": self.po5_execution_eligibility.proposal_status.value if self.po5_execution_eligibility else None,
                "reason": self.po5_execution_eligibility.reason if self.po5_execution_eligibility else None,
            },
            "p6": {
                "has_regime": self.p6_regime is not None,
                "regime": self.p6_regime.regime.value if self.p6_regime else None,
                "intent": self.p6_regime.intent.value if self.p6_regime else None,
                "execution_eligibility": self.p6_regime.execution_eligibility.value if self.p6_regime else None,
                "coherence_regime": self.p6_regime.coherence_regime if self.p6_regime else None,
                "reason": self.p6_regime.reason if self.p6_regime else None,
            },
            "p7": {
                "has_discourse": self.p7_discourse_envelope is not None,
                "act": self.p7_discourse_envelope.act.value if self.p7_discourse_envelope else None,
                "allowed": self.p7_discourse_envelope.allowed if self.p7_discourse_envelope else None,
                "intent": self.p7_discourse_envelope.intent.value if self.p7_discourse_envelope else None,
                "regime": self.p7_discourse_envelope.regime.value if self.p7_discourse_envelope else None,
                "reason": self.p7_discourse_envelope.reason if self.p7_discourse_envelope else None,
            },
            "p8": {
                "has_semantic_frame": self.semantic_frame is not None,
                "discourse_act": self.semantic_frame.discourse_act.value if self.semantic_frame else None,
                "allowed": self.semantic_frame.allowed if self.semantic_frame else None,
                "slot_count": len(self.semantic_frame.slots) if self.semantic_frame else 0,
                "populated_count": len(self.semantic_frame.get_populated_slots()) if self.semantic_frame else 0,
                "reason": self.semantic_frame.reason if self.semantic_frame else None,
            },
            "p9": {
                "has_lexical_frame": self.lexical_frame is not None,
                "allowed": self.lexical_frame.allowed if self.lexical_frame else None,
                "selection_count": self.lexical_frame.count() if self.lexical_frame else 0,
                "is_empty": self.lexical_frame.is_empty() if self.lexical_frame else True,
                "source_discourse_act": self.lexical_frame.source_discourse_act if self.lexical_frame else None,
                "source_regime": self.lexical_frame.source_regime if self.lexical_frame else None,
                "reason": self.lexical_frame.reason if self.lexical_frame else None,
            },
            "p10": {
                "has_acoustic_frame": self.p10_acoustic is not None,
                "regime": self.p10_acoustic.regime.value if self.p10_acoustic else None,
                "speech_rate": self.p10_acoustic.speech_rate if self.p10_acoustic else None,
                "energy_level": self.p10_acoustic.energy_level if self.p10_acoustic else None,
                "is_flat": self.p10_acoustic.is_flat_regime() if self.p10_acoustic else True,
                "is_suppressed": self.p10_acoustic.is_suppressed() if self.p10_acoustic else True,
                "allows_emphasis": self.p10_acoustic.allows_emphasis() if self.p10_acoustic else False,
                "source_regime": self.p10_acoustic.source_regime if self.p10_acoustic else None,
                "source_discourse_act": self.p10_acoustic.source_discourse_act if self.p10_acoustic else None,
            },
            "p11": {
                "has_prosodic_evidence": self.p11_prosodic_evidence is not None,
                "violations_detected": self.p11_prosodic_evidence.violations_detected if self.p11_prosodic_evidence else None,
                "failed_invariants": self.p11_prosodic_evidence.get_failed_invariants() if self.p11_prosodic_evidence else [],
                "is_fully_suppressed": self.p11_prosodic_evidence.is_fully_suppressed() if self.p11_prosodic_evidence else True,
                "source_regime": self.p11_prosodic_evidence.source_regime if self.p11_prosodic_evidence else None,
                "source_discourse_act": self.p11_prosodic_evidence.source_discourse_act if self.p11_prosodic_evidence else None,
                "source_p10_version": self.p11_prosodic_evidence.source_p10_version if self.p11_prosodic_evidence else None,
                "timestamp_utc": self.p11_prosodic_evidence.timestamp_utc if self.p11_prosodic_evidence else None,
            },
            "p12": {
                "has_consistency_report": self.p12_consistency is not None,
                "is_consistent": self.p12_consistency.is_consistent if self.p12_consistency else None,
                "violation_count": self.p12_consistency.violation_count() if self.p12_consistency else 0,
                "warning_count": self.p12_consistency.warning_count() if self.p12_consistency else 0,
                "has_critical": self.p12_consistency.has_critical_violations() if self.p12_consistency else False,
                "has_major": self.p12_consistency.has_major_violations() if self.p12_consistency else False,
                "checked_invariants": len(self.p12_consistency.checked_invariants) if self.p12_consistency else 0,
                "source_regime": self.p12_consistency.source_regime if self.p12_consistency else None,
                "source_discourse_act": self.p12_consistency.source_discourse_act if self.p12_consistency else None,
                "timestamp_utc": self.p12_consistency.timestamp_utc if self.p12_consistency else None,
            },
            "p13": {
                "has_safety_envelope": self.p13_safety_envelope is not None,
                "risk_level": self.p13_safety_envelope.risk_level.value if self.p13_safety_envelope else None,
                "is_safe": self.p13_safety_envelope.is_safe() if self.p13_safety_envelope else False,
                "is_blocked": self.p13_safety_envelope.is_blocked() if self.p13_safety_envelope else True,
                "has_violations": self.p13_safety_envelope.has_violations() if self.p13_safety_envelope else False,
                "violation_count": len(self.p13_safety_envelope.violations) if self.p13_safety_envelope else 0,
                "allow_emphasis": self.p13_safety_envelope.allow_emphasis if self.p13_safety_envelope else False,
                "allow_pitch_contours": self.p13_safety_envelope.allow_pitch_contours if self.p13_safety_envelope else False,
                "is_fully_restricted": self.p13_safety_envelope.is_fully_restricted() if self.p13_safety_envelope else True,
                "source_regime": self.p13_safety_envelope.source_regime if self.p13_safety_envelope else None,
                "source_discourse_act": self.p13_safety_envelope.source_discourse_act if self.p13_safety_envelope else None,
                "timestamp_utc": self.p13_safety_envelope.timestamp_utc if self.p13_safety_envelope else None,
            },
            "p14": {
                "has_surface_plan": self.p14_surface is not None,
                "style": self.p14_surface.style.value if self.p14_surface else None,
                "punctuation": self.p14_surface.punctuation.value if self.p14_surface else None,
                "hedging": self.p14_surface.hedging.value if self.p14_surface else None,
                "length": self.p14_surface.length.value if self.p14_surface else None,
                "persona_signals": self.p14_surface.persona_signals.value if self.p14_surface else None,
                "requires_question": self.p14_surface.requires_question if self.p14_surface else True,
                "is_deferral": self.p14_surface.is_deferral() if self.p14_surface else True,
                "allows_exclamation": self.p14_surface.allows_exclamation() if self.p14_surface else False,
                "allows_bullets": self.p14_surface.allows_bullets() if self.p14_surface else False,
                "max_sentences": self.p14_surface.get_max_sentences() if self.p14_surface else 1,
                "connector_count": len(self.p14_surface.allowed_connectors) if self.p14_surface else 0,
                "forbidden_count": len(self.p14_surface.forbidden_tokens) if self.p14_surface else 0,
                "source_regime": self.p14_surface.source_regime if self.p14_surface else None,
                "source_discourse_act": self.p14_surface.source_discourse_act if self.p14_surface else None,
                "timestamp_utc": self.p14_surface.timestamp_utc if self.p14_surface else None,
            },
            "hrm": {
                "has_map": self.hrm_map is not None,
                "tier": self.hrm_map.tier if self.hrm_map else None,
                "conflict_count": len(self.hrm_map.conflict_zones) if self.hrm_map else 0,
            },
            "lam": {
                "has_map": self.lam_map is not None,
                "arc_state": self.lam_map.arc_state if self.lam_map else None,
                "pattern_count": len(self.lam_map.active_patterns) if self.lam_map else 0,
            },
            "fusion": {
                "has_candidates": self.fusion is not None,
            },
            "dha": {
                "tone_profile": self.dha.tone_profile if self.dha else None,
                "readiness_level": self.dha.readiness_level if self.dha else None,
            },
            "rendered": {
                "mode": self.rendered.mode if self.rendered else None,
                "has_text": self.rendered is not None and bool(self.rendered.raw_text),
            },
            "router_mode": self.router_mode,
            "coherence": {
                "has_state": self.coherence_state is not None,
                "coherence_score": self.coherence_state.coherence_score if self.coherence_state else None,
                "persona_drift": self.coherence_state.persona_drift_score if self.coherence_state else None,
                "semantic_stability": self.coherence_state.semantic_stability_score if self.coherence_state else None,
            },
            "coherence_report": self.coherence_report,
        }


# Public exports
__all__ = [
    "UserRequest",
    "PersonaContext",
    "MlcrResult",
    "FusionResult",
    "DhaDecision",
    "RenderedOutput",
    "PipelineContext",
    "MapperProfile",
]
