"""
Symbol-U Pipeline Models (v3.0)

Dataclasses representing the main artifacts passed between pipeline stages.

These models provide a clean, typed interface for data flowing through:
    UserRequest -> Persona -> MLCR -> Fusion -> DHA -> Renderer -> RenderedOutput

The design follows the Symbol-U AGI architecture where:
- Persona represents the communicative identity layer
- MLCR handles multi-layer consciousness routing (Bhava awareness)
- Fusion blends HRM/LCM/LAM/MoE channels (Kosha integration)
- DHA manages delivery harmonization & adaptation
- Renderer produces the final output surface
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from symbolu.core.coherence import CoherenceState


@dataclass
class UserRequest:
    """
    Incoming user request to the pipeline.

    Attributes:
        user_id: Optional identifier for session/user tracking.
        text: The raw query or input text.
        metadata: Additional context (e.g., domain hints, emotional cues).
        render_mode: Output mode preference - minimal / standard / enhanced / regulated.
    """

    text: str
    user_id: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
    render_mode: Optional[str] = None  # e.g., "minimal", "standard", "enhanced", "regulated"

    def __post_init__(self) -> None:
        if not self.text or not self.text.strip():
            raise ValueError("UserRequest.text must be a non-empty string")


@dataclass
class PersonaContext:
    """
    Resolved persona context after persona selection.

    Attributes:
        active_persona_id: The selected persona identifier (e.g., "analyst", "sage", "coach").
        persona_config: Full persona configuration including traits, tone settings, etc.
    """

    active_persona_id: str
    persona_config: Dict[str, Any] = field(default_factory=dict)


@dataclass
class MlcrResult:
    """
    Result from MLCR (Multi-Layer Consciousness RAG) engine.

    Wraps the routing decision including activation plan, explain_log,
    and renderer context generated by MLCR.

    Attributes:
        entries: The raw MLCR output (routing decision dictionary).
        meta: Additional metadata for debugging/tracing.
    """

    entries: Any  # Keep loose - wraps whatever mlcr_engine.route() returns
    meta: Dict[str, Any] = field(default_factory=dict)

    @property
    def explain_log(self) -> Dict[str, Any]:
        """Extract explain_log from MLCR entries if available."""
        if isinstance(self.entries, dict):
            return self.entries.get("explain_log", {})
        return {}

    @property
    def activation_plan(self) -> Dict[str, Any]:
        """Extract activation_plan from MLCR entries if available."""
        if isinstance(self.entries, dict):
            return self.entries.get("activation_plan", {})
        return {}

    @property
    def renderer_context(self) -> Dict[str, Any]:
        """Extract renderer_context from MLCR entries if available."""
        if isinstance(self.entries, dict):
            return self.entries.get("renderer_context", {})
        return {}


@dataclass
class FusionResult:
    """
    Result from Fusion Engine.

    Contains the selected candidate, ranked alternatives, and routing decisions.

    Attributes:
        fused_candidates: The fusion engine result (selected candidate + rankings).
        trace: Trace data for debugging/explainability.
    """

    fused_candidates: Any  # Wraps FusionResult from fusion_engine
    trace: Dict[str, Any] = field(default_factory=dict)

    @property
    def selected_text(self) -> Optional[str]:
        """Extract the selected candidate text if available."""
        if hasattr(self.fused_candidates, "selected_candidate"):
            candidate = self.fused_candidates.selected_candidate
            if hasattr(candidate, "text"):
                return candidate.text
        return None

    @property
    def routing(self) -> Dict[str, Any]:
        """Extract routing decisions from fusion result."""
        if hasattr(self.fused_candidates, "routing"):
            return self.fused_candidates.routing
        return {}


@dataclass
class DhaDecision:
    """
    Decision from DHA (Delivery Harmonization & Adaptation) Engine.

    Captures the delivery adaptation including tone profile, readiness analysis,
    and any safety/resistance flags.

    Attributes:
        guarded_text: The potentially transformed/adapted text.
        tone_profile: Delivery profile (e.g., "sweet_resonance", "inverse_jolt", "symbolic_metaphor").
        readiness_level: User readiness level (HIGH / MEDIUM / LOW).
        resistance_flags: Detected resistance patterns.
        safety_flags: Safety filter results.
        adaptation_notes: Additional adaptation metadata.
    """

    guarded_text: str
    tone_profile: str  # e.g., "sweet_resonance", "inverse_jolt", "symbolic_metaphor"
    readiness_level: str  # HIGH / MEDIUM / LOW
    resistance_flags: Dict[str, Any] = field(default_factory=dict)
    safety_flags: Dict[str, Any] = field(default_factory=dict)
    adaptation_notes: Dict[str, Any] = field(default_factory=dict)


@dataclass
class RenderedOutput:
    """
    Final rendered output from the pipeline.

    Attributes:
        raw_text: The final rendered text content.
        mode: The render mode used (minimal / standard / enhanced / regulated).
        meta: Additional metadata (layers, trace info, etc.).
    """

    raw_text: str
    mode: str
    meta: Dict[str, Any] = field(default_factory=dict)


@dataclass
class MapperProfile:
    """
    Mapper influence profile for renderer and DHA modulation.

    Computed deterministically from HRM/LCM/LAM activation flags
    and routing signals. Used to modulate expression (NOT semantic truth).

    Attributes:
        resolution_level: "low" | "medium" | "high" - Detail granularity
        arc_mode: "none" | "temporal" | "identity" | "deep_context" - Long-arc framing
        detail_bias: 0.0–1.0 - Preference for fine-grained detail
        practical_bias: 0.0–1.0 - Preference for concrete/task-focused delivery
        reflective_bias: 0.0–1.0 - Preference for introspective/philosophical framing
    """

    resolution_level: str = "medium"  # "low" | "medium" | "high"
    arc_mode: str = "none"  # "none" | "temporal" | "identity" | "deep_context"
    detail_bias: float = 0.5  # 0.0–1.0
    practical_bias: float = 0.5  # 0.0–1.0
    reflective_bias: float = 0.5  # 0.0–1.0

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "resolution_level": self.resolution_level,
            "arc_mode": self.arc_mode,
            "detail_bias": self.detail_bias,
            "practical_bias": self.practical_bias,
            "reflective_bias": self.reflective_bias,
        }


@dataclass
class PipelineContext:
    """
    Full context object passed through the pipeline stages.

    Accumulates results from each stage for tracing and debugging.
    The router_mode field enables Option C routing (linear for v3.0,
    with future support for adaptive flows).

    Attributes:
        request: The original UserRequest.
        persona: PersonaContext after persona resolution.
        mlcr: MlcrResult after MLCR routing.
        hrm_map: Optional HighResolutionMap from HRM engine (when use_hrm=True).
        lcm_map: Optional LowContextMap from LCM engine (when use_lcm=True).
        lam_map: Optional LongArcMap from LAM engine (when use_lam=True or long_arc_tension high).
        fusion: FusionResult after candidate fusion.
        dha: DhaDecision after delivery harmonization.
        rendered: RenderedOutput after final rendering.
        router_mode: Pipeline routing mode ("linear" for v3.0).
        mapper_profile: Mapper influence profile for renderer/DHA modulation.
        coherence_state: Optional CoherenceState tracking multi-turn conversation coherence.
        coherence_report: Optional observability report dict from CoherenceObserver.
    """

    request: UserRequest
    persona: Optional[PersonaContext] = None
    mlcr: Optional[MlcrResult] = None
    hrm_map: Optional[Any] = None  # HighResolutionMap from HRM engine
    lcm_map: Optional[Any] = None  # LowContextMap from LCM engine
    lam_map: Optional[Any] = None  # LongArcMap from LAM engine
    fusion: Optional[FusionResult] = None
    dha: Optional[DhaDecision] = None
    rendered: Optional[RenderedOutput] = None
    router_mode: str = "linear"
    mapper_profile: Optional[MapperProfile] = None
    coherence_state: Optional["CoherenceState"] = None  # Multi-turn coherence tracking
    coherence_report: Optional[Dict[str, Any]] = None  # Observability report from CoherenceObserver
    unified_output: Optional[Dict[str, Any]] = None  # Unified API output (USU-API v1.0)

    # Phase 1 temporal formulas (observation only - not used in routing/behavior yet)
    smi: Optional[float] = None  # Symbolic Mental Index (0.0 to 1.0)
    delta_smi: Optional[float] = None  # SMI momentum (-1.0 to 1.0)
    bhava_gap: Optional[float] = None  # Bhava circular distance (0.0 to 1.0)
    tension_corridor: Optional[float] = None  # Tension dynamics signal (0.0 to 1.0)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize context to dictionary for logging/debugging."""
        return {
            "request": {
                "user_id": self.request.user_id,
                "text": self.request.text,
                "render_mode": self.request.render_mode,
            },
            "persona": {
                "active_persona_id": self.persona.active_persona_id if self.persona else None,
            },
            "mlcr": {
                "has_entries": self.mlcr is not None and self.mlcr.entries is not None,
            },
            "hrm": {
                "has_map": self.hrm_map is not None,
                "tier": self.hrm_map.tier if self.hrm_map else None,
                "conflict_count": len(self.hrm_map.conflict_zones) if self.hrm_map else 0,
            },
            "lam": {
                "has_map": self.lam_map is not None,
                "arc_state": self.lam_map.arc_state if self.lam_map else None,
                "pattern_count": len(self.lam_map.active_patterns) if self.lam_map else 0,
            },
            "fusion": {
                "has_candidates": self.fusion is not None,
            },
            "dha": {
                "tone_profile": self.dha.tone_profile if self.dha else None,
                "readiness_level": self.dha.readiness_level if self.dha else None,
            },
            "rendered": {
                "mode": self.rendered.mode if self.rendered else None,
                "has_text": self.rendered is not None and bool(self.rendered.raw_text),
            },
            "router_mode": self.router_mode,
            "coherence": {
                "has_state": self.coherence_state is not None,
                "coherence_score": self.coherence_state.coherence_score if self.coherence_state else None,
                "persona_drift": self.coherence_state.persona_drift_score if self.coherence_state else None,
                "semantic_stability": self.coherence_state.semantic_stability_score if self.coherence_state else None,
            },
            "coherence_report": self.coherence_report,
        }


# Public exports
__all__ = [
    "UserRequest",
    "PersonaContext",
    "MlcrResult",
    "FusionResult",
    "DhaDecision",
    "RenderedOutput",
    "PipelineContext",
    "MapperProfile",
]
