"""Ugence Model Egress Unit — the reference exchange between the worker and a model call.

**This distribution cannot call a model vendor.** It carries no HTTP client, no
vendor SDK, no credential reader and no destination configuration, and the only
providers it ships compute their answers from a hash or refuse outright. What is
real here is the boundary: a dedicated PostgreSQL schema, three roles of which the
owner cannot log in, forced row-level security keyed on a required tenant
identity, request and result records with complete canonical digests, terminal
refusals, ``OUTCOME_UNKNOWN``, consumption acknowledgement, and content purge
leaving digest-only tombstones.

The unit exists as a separate deployment unit so the governance worker's egress
claim stays intact. **D-1 through D-5 were ratified on 2026-09-10**, together with
the exchange grants and tenancy and the retention horizons; this package is written
against those rulings. What remains unauthorized is a *live* provider: D-3 keeps
provider custody out of this deployment, and CR-1 still admits only one companion
deployment unit, so the MEU's boundary is specified while its commissioning as a
running unit is not `[G]`.

Since 0.2.0 (2026-09-11) the package carries the three pieces of mechanism the
commissioning ballot (``ADR_UGENCE_LIVE_MODEL_PROVIDER_COMMISSIONING.md``) can carry
before the owner rules: the provider-credential custody **port** with an inert
reference adapter (``custody``), the ledger-kind schema that refuses content-bearing
keys (``ledger_kinds``), and transport protection for the exchange's own DSNs
(``postgres.transport``). None of them holds, reads or reaches a credential; the
owner's designations (OpenAI; Google Secret Manager) live in
``MEU_LIVE_PROVIDER_DESIGNATION.json`` beside the package, and
``MEU_LIVE_VALIDATION.json`` stays ``BLOCKED_PENDING_OWNER_RULINGS``.
"""

from __future__ import annotations

from .authorization import (
    AUTHORIZATION_DIGEST_DOMAIN,
    AUTHORIZATION_SCHEMA,
    DESIGNATION_RECORD_DIGEST_DOMAIN,
    NOT_GIVEN,
    AuthorizationLedger,
    AuthorizationRefusal,
    AuthorizationRefused,
    CommissioningRecordView,
    InMemoryAuthorizationLedger,
    LiveSyntheticValidationAuthorization,
    ScopeExpectation,
    admit_genuine_call,
    check_live_authorization,
    designation_record_digest,
)
from .canonical import (
    EGRESS_REQUEST_DIGEST_DOMAIN,
    EGRESS_RESULT_DIGEST_DOMAIN,
    EXCHANGE_CONTENT_DIGEST_DOMAIN,
    MEU_CANONICALIZATION_VERSION,
    CanonicalizationError,
    canonical_bytes,
    canonical_digest,
    content_digest,
    minimized_context_digest,
    payload_digest,
)
from .custody import (
    CUSTODY_AUDIT_DOMAIN,
    CUSTODY_REQUEST_DOMAIN,
    REFERENCE_CUSTODY_MARKER,
    CredentialLease,
    CredentialRequest,
    CustodyAuditEvent,
    CustodyRefusal,
    CustodyRefused,
    CustodyRefusedInProduction,
    CustodyIdentity,
    IDENTITY_KINDS,
    PRODUCTION_AUTHORITATIVE_IDENTITY_KINDS,
    is_service_account_resource,
    ModelCredentialCustodyPort,
    PinnedSecretVersionCustodyAdapter,
    ReferenceCustodyAdapter,
    is_pinned_secret_version,
    materialize_with_audit,
)
from .egress_policy import (
    OPENAI_RESPONSES,
    DesignatedDestination,
    DestinationRefused,
    check_destination,
)
from .errors import (
    ExchangeError,
    RequestNotClaimable,
    ResultNotAcknowledgeable,
    TenantMismatch,
    UnscopableConnection,
)
from .limits import (
    COMMISSIONING_LIMITS,
    FORBIDDEN_REQUEST_FEATURES,
    BudgetExhausted,
    CallBudget,
    CommissioningLimits,
    LimitViolation,
    check_request,
    is_pinned_snapshot,
)
from .infrastructure import (
    CREDENTIAL_SHAPE_PREFIXES,
    IDENTITY_MECHANISMS,
    MAX_ROTATION_INTERVAL,
    OPENAI_KEY_SCOPE,
    PLACEHOLDER_MARKERS,
    ROTATION_SEQUENCE,
    SPEND_CONTROL_CLASSIFICATIONS,
    STEP8_ATTESTATION_FIELDS,
    STEP8_DERIVED_SUBFIELDS,
    STEP8_OBLIGATION_COUNT,
    STEP8_OBLIGATIONS,
    STEP8_REQUIRED_VALUES,
    DesignationRefused,
    NativeGcpWorkloadIdentity,
    RotationRefused,
    Step8Designation,
    WorkloadIdentityFederation,
    check_rotation_plan,
    check_step8_designation,
    looks_like_a_credential,
    rollback_permitted,
    step8_field_counts,
    CI_ENVIRONMENT_MARKERS,
    FORBIDDEN_CREDENTIAL_HOLDERS,
    LIVE_VALIDATION_EXECUTION_POSTURE,
    NON_PRODUCTION_VALIDATION_OUTCOME_SCOPE,
    PRODUCTION_FORM_CUSTODY_ADAPTER,
    ExecutionPosture,
    ExecutionPostureRefused,
    check_execution_posture,
    ci_environment_markers_present,
    sequence_complete,
)
from .ledger_kinds import (
    CONTENT_BEARING_KEYS,
    MAX_LEDGER_STRING,
    MEU_LEDGER_KINDS,
    LedgerKindViolation,
    ledger_payload,
    result_ledger_payload,
)
from .provider import (
    REFERENCE_CLEARANCE_DOMAIN,
    REFERENCE_RESPONSE_MARKER,
    DeterministicFakeProvider,
    EgressProvider,
    LiveEgressUnavailableProvider,
    ProviderRefusedInProduction,
    reference_clearance,
)
from .reconcile import ReconciliationPass, ReconciliationScheduler
from .records import (
    ACKNOWLEDGEMENT_GRACE,
    EXCHANGE_SCHEMA_VERSION,
    HARD_RETENTION_DEADLINE,
    TERMINAL_STATES,
    TRUST_LEVEL,
    AuthorizationBinding,
    DispatchAttempt,
    EgressRequest,
    EgressResult,
    GenuineCallAdmission,
    MinimizedUnit,
    ProvenanceKind,
    RefusalReason,
    RequestState,
    ResultOutcome,
    purge_deadline,
)
from .unit import EgressUnit, UnitPass
from .version import (
    COMMISSIONING_STATUS,
    GENUINE_CALL_ADMITTING_STATUSES,
    LIVE_SYNTHETIC_VALIDATION_AUTHORIZATION_DIGEST,
    status_admits_genuine_call,
    CONTRACT_VERSION,
    ENFORCEMENT_ENABLED,
    LIVE_VENDOR_EGRESS,
    MATURITY,
    __version__,
)

__all__ = [
    "__version__",
    "CONTRACT_VERSION",
    "COMMISSIONING_STATUS",
    "LIVE_SYNTHETIC_VALIDATION_AUTHORIZATION_DIGEST",
    "GENUINE_CALL_ADMITTING_STATUSES",
    "status_admits_genuine_call",
    "AUTHORIZATION_SCHEMA",
    "AUTHORIZATION_DIGEST_DOMAIN",
    "DESIGNATION_RECORD_DIGEST_DOMAIN",
    "NOT_GIVEN",
    "AuthorizationRefusal",
    "AuthorizationRefused",
    "LiveSyntheticValidationAuthorization",
    "ScopeExpectation",
    "CommissioningRecordView",
    "designation_record_digest",
    "AuthorizationLedger",
    "InMemoryAuthorizationLedger",
    "check_live_authorization",
    "admit_genuine_call",
    "GenuineCallAdmission",
    "MATURITY",
    "ENFORCEMENT_ENABLED",
    "LIVE_VENDOR_EGRESS",
    "MEU_CANONICALIZATION_VERSION",
    "EGRESS_REQUEST_DIGEST_DOMAIN",
    "EGRESS_RESULT_DIGEST_DOMAIN",
    "EXCHANGE_CONTENT_DIGEST_DOMAIN",
    "CanonicalizationError",
    "canonical_bytes",
    "canonical_digest",
    "content_digest",
    "minimized_context_digest",
    "payload_digest",
    "EXCHANGE_SCHEMA_VERSION",
    "TRUST_LEVEL",
    "ACKNOWLEDGEMENT_GRACE",
    "HARD_RETENTION_DEADLINE",
    "purge_deadline",
    "AuthorizationBinding",
    "MinimizedUnit",
    "DispatchAttempt",
    "ProvenanceKind",
    "RequestState",
    "ResultOutcome",
    "RefusalReason",
    "TERMINAL_STATES",
    "EgressRequest",
    "EgressResult",
    "ExchangeError",
    "UnscopableConnection",
    "TenantMismatch",
    "RequestNotClaimable",
    "ResultNotAcknowledgeable",
    "CUSTODY_AUDIT_DOMAIN",
    "CUSTODY_REQUEST_DOMAIN",
    "REFERENCE_CUSTODY_MARKER",
    "CredentialRequest",
    "CredentialLease",
    "CustodyAuditEvent",
    "CustodyRefusal",
    "CustodyRefused",
    "CustodyRefusedInProduction",
    "ModelCredentialCustodyPort",
    "ReferenceCustodyAdapter",
    "CustodyIdentity",
    "IDENTITY_KINDS",
    "PRODUCTION_AUTHORITATIVE_IDENTITY_KINDS",
    "is_service_account_resource",
    "is_pinned_secret_version",
    "PinnedSecretVersionCustodyAdapter",
    "materialize_with_audit",
    "DesignatedDestination",
    "OPENAI_RESPONSES",
    "DestinationRefused",
    "check_destination",
    "CommissioningLimits",
    "COMMISSIONING_LIMITS",
    "FORBIDDEN_REQUEST_FEATURES",
    "LimitViolation",
    "is_pinned_snapshot",
    "check_request",
    "CallBudget",
    "BudgetExhausted",
    "STEP8_OBLIGATIONS",
    "STEP8_OBLIGATION_COUNT",
    "STEP8_DERIVED_SUBFIELDS",
    "STEP8_ATTESTATION_FIELDS",
    "STEP8_REQUIRED_VALUES",
    "step8_field_counts",
    "PLACEHOLDER_MARKERS",
    "CREDENTIAL_SHAPE_PREFIXES",
    "OPENAI_KEY_SCOPE",
    "SPEND_CONTROL_CLASSIFICATIONS",
    "IDENTITY_MECHANISMS",
    "MAX_ROTATION_INTERVAL",
    "looks_like_a_credential",
    "DesignationRefused",
    "WorkloadIdentityFederation",
    "NativeGcpWorkloadIdentity",
    "Step8Designation",
    "check_step8_designation",
    "ROTATION_SEQUENCE",
    "RotationRefused",
    "check_rotation_plan",
    "rollback_permitted",
    "CI_ENVIRONMENT_MARKERS",
    "FORBIDDEN_CREDENTIAL_HOLDERS",
    "LIVE_VALIDATION_EXECUTION_POSTURE",
    "NON_PRODUCTION_VALIDATION_OUTCOME_SCOPE",
    "PRODUCTION_FORM_CUSTODY_ADAPTER",
    "ExecutionPosture",
    "ExecutionPostureRefused",
    "check_execution_posture",
    "ci_environment_markers_present",
    "sequence_complete",
    "MEU_LEDGER_KINDS",
    "CONTENT_BEARING_KEYS",
    "MAX_LEDGER_STRING",
    "LedgerKindViolation",
    "ledger_payload",
    "result_ledger_payload",
    "EgressProvider",
    "DeterministicFakeProvider",
    "LiveEgressUnavailableProvider",
    "ProviderRefusedInProduction",
    "REFERENCE_RESPONSE_MARKER",
    "REFERENCE_CLEARANCE_DOMAIN",
    "reference_clearance",
    "EgressUnit",
    "UnitPass",
    "ReconciliationScheduler",
    "ReconciliationPass",
]
