#!/usr/bin/env python3
"""Canonical varṇa romanization → ROMANIZATION.md + `_romanization` in the lexicon JSON.

Per the agreed schema: IAST is CANONICAL; plain_input is a list of ASCII/English ALIASES (derived
directly from the engine's own parser tables, so the doc can never drift from what actually parses);
plus a pronunciation_note. Dental vs retroflex vs aspirated are stated explicitly so no arbitrary
spelling sneaks in. English *words* should still use g2p (pronunciation); this table governs romanized
/ explicit input.
"""
import json, pathlib
import varna_lens as V

HERE = pathlib.Path(__file__).parent
JPATH = HERE / "lexicon_authoritative.json"
MDPATH = HERE / "ROMANIZATION.md"

PRON = {
 # vowels
 "a": "short a, as in 'about'", "aa": "long ā, as in 'father'",
 "i": "short i, as in 'sit'", "ii": "long ī, as in 'see'",
 "u": "short u, as in 'put'", "uu": "long ū, as in 'moon' (distinct from o)",
 "e": "long ē, as in 'play' (monophthong)", "ai": "diphthong ai, as in 'aisle'",
 "o": "long ō, as in 'go'", "au": "diphthong au, as in 'cow'",
 "am": "anusvāra — nasalization (ṁ)", "ah": "visarga — soft breath (ḥ)",
 # consonants
 "ka": "unaspirated k (guttural)", "kha": "aspirated kh", "ga": "unaspirated g", "gha": "aspirated gh",
 "nga": "ṅ — guttural nasal, as in 'sing'",
 "ca": "ch as in 'church' (unaspirated, palatal)", "cha": "aspirated chh", "ja": "j as in 'jam'",
 "jha": "aspirated jh", "nya": "ñ — palatal nasal, as in 'canyon'",
 "tta": "retroflex ṭ — tongue curled back to the ridge (hard t)", "ttha": "aspirated retroflex ṭh",
 "dda": "retroflex ḍ — tongue curled back (hard d)", "ddha": "aspirated retroflex ḍh",
 "nna": "retroflex ṇ",
 "ta": "dental t — tongue touches the teeth (soft t)", "tha": "aspirated dental th",
 "da": "dental d — tongue on the teeth", "dha": "aspirated dental dh", "na": "dental n",
 "pa": "unaspirated p", "pha": "aspirated ph (also used for English f)", "ba": "b", "bha": "aspirated bh",
 "ma": "m", "ya": "y as in 'yes'", "ra": "r — rolled / tapped", "la": "l", "va": "v / w",
 "sha": "palatal śa — soft 'sh' as in 'sheet'",
 "ssa": "retroflex ṣa — 'sh' with the tongue curled back (informally 'shha')",
 "sa": "dental s, as in 'sit'", "ha": "h", "ksha": "kṣ — compound k+ṣ",
}


def _invert(table):
    out = {}
    for surface, key in table:
        out.setdefault(key, []).append(surface)
    return out


def main():
    cons_alias = _invert(V._CONS)
    vow_alias = _invert(V._VOW)

    rom = {}
    L = ["# Varṇa ↔ English romanization (canonical, generated)", "",
         "> Generated by `gen_romanization.py`. **IAST is canonical**; `plain_input` lists the ASCII/English",
         "> aliases the parser accepts (derived from the engine's own tables, so this can't drift from",
         "> behaviour). Retroflex vs dental vs aspirated are stated explicitly. **English *words* should use",
         "> g2p (pronunciation)** — least arbitrary; this table governs romanized / explicit input.",
         "> Disambiguation: retroflex = ITRANS CAPITALS `T Th D Dh N Sh`; long vowels `ee`→ī, `oo`→ū.", "",
         "## Vowels", "| Devanāgarī | IAST (canonical) | plain_input (aliases) | pronunciation |",
         "|---|---|---|---|"]
    for k, d in V.VOW.items():
        iast_full = d["iast"]                      # e.g. "ū (ऊ)"
        iast = iast_full.split(" ")[0]
        deva = iast_full.split("(")[-1].rstrip(")") if "(" in iast_full else ""
        aliases = vow_alias.get(k, [])
        rom[k] = {"deva": deva, "iast": iast, "plain_input": aliases, "pronunciation_note": PRON.get(k, "")}
        L.append(f"| {deva} | {iast} | {', '.join('`'+a+'`' for a in aliases)} | {PRON.get(k,'')} |")

    L += ["", "## Consonants", "| Devanāgarī | IAST (canonical) | plain_input (aliases) | pronunciation |",
          "|---|---|---|---|"]
    for k, d in V.CONS.items():
        deva = V._VARGA[k][1]; iast = d["iast"]
        aliases = cons_alias.get(k, [])
        rom[k] = {"deva": deva, "iast": iast, "plain_input": aliases, "pronunciation_note": PRON.get(k, "")}
        L.append(f"| {deva} | {iast} | {', '.join('`'+a+'`' for a in aliases)} | {PRON.get(k,'')} |")
    MDPATH.write_text("\n".join(L) + "\n", encoding="utf-8")

    data = json.loads(JPATH.read_text(encoding="utf-8"))
    data["_romanization"] = rom
    data["_romanization_note"] = ("IAST is canonical; plain_input = ASCII/English aliases the parser "
                                  "accepts (derived from the engine tables); pronunciation_note describes "
                                  "the sound (dental/retroflex/aspirated). English words use g2p.")
    JPATH.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {MDPATH.name}; injected _romanization ({len(rom)} varṇas, IAST canonical + aliases).")


if __name__ == "__main__":
    main()
