#!/usr/bin/env python3
"""Generate the canonical varṇa ↔ English/IAST/ITRANS romanization table → ROMANIZATION.md, and inject a
compact `_romanization` reference into lexicon_authoritative.json (single source). Reduces arbitrary
parses: each varṇa has ONE Devanāgarī, ONE IAST, an ASCII (ITRANS) form, and the plain-English spelling.
English long vowels ee→ī and oo→ū are honored by the roman parser; other English vowel spellings are
ambiguous → use g2p (pronunciation) or --varnas.
"""
import json, pathlib
import varna_lens as V

HERE = pathlib.Path(__file__).parent
JPATH = HERE / "lexicon_authoritative.json"
MDPATH = HERE / "ROMANIZATION.md"

# vowel key -> (devanāgarī, itrans/ascii, english spelling, example)
VOW = {
 "a":  ("अ", "a",       "a",        "about"),
 "aa": ("आ", "aa / A",  "aa",       "father"),
 "i":  ("इ", "i",       "i",        "sit"),
 "ii": ("ई", "ii / I",  "ee",       "see"),
 "u":  ("उ", "u",       "u",        "put"),
 "uu": ("ऊ", "uu / U",  "oo",       "moon"),
 "e":  ("ए", "e",       "e / ay",   "play (pure ē)"),
 "ai": ("ऐ", "ai",      "ai",       "aisle"),
 "o":  ("ओ", "o",       "o",        "go"),
 "au": ("औ", "au",      "au / ow",  "cow"),
 "am": ("अं","M / .m",  "ṁ (nasal)","saṁ-"),
 "ah": ("अः","H / .h",  "ḥ (breath)","-aḥ"),
}

# consonant key -> (itrans/ascii, english spelling/sound)
CON = {
 "ka": ("k", "k (skate)"), "kha": ("kh", "kh (aspirated k)"), "ga": ("g", "g (go)"),
 "gha": ("gh", "gh (aspirated g)"), "nga": ("~N / N^", "ng (sing)"),
 "ca": ("ch / c", "ch (church)"), "cha": ("Ch / chh", "chh (aspirated ch)"), "ja": ("j", "j (jam)"),
 "jha": ("jh", "jh (aspirated j)"), "nya": ("~n / GY", "ny (canyon)"),
 "tta": ("T", "ṭ (retroflex t — curl tongue)"), "ttha": ("Th", "ṭh (aspirated retroflex t)"),
 "dda": ("D", "ḍ (retroflex d)"), "ddha": ("Dh", "ḍh (aspirated retroflex d)"),
 "nna": ("N", "ṇ (retroflex n)"),
 "ta": ("t", "t (dental — tongue on teeth)"), "tha": ("th", "th (aspirated dental t)"),
 "da": ("d", "d (dental)"), "dha": ("dh", "dh (aspirated dental d)"), "na": ("n", "n (dental)"),
 "pa": ("p", "p (spin)"), "pha": ("ph / f", "ph / f (aspirated p)"), "ba": ("b", "b (bin)"),
 "bha": ("bh", "bh (aspirated b)"), "ma": ("m", "m (man)"),
 "ya": ("y", "y (yes)"), "ra": ("r", "r (rolled/tap)"), "la": ("l", "l (let)"), "va": ("v / w", "v / w"),
 "sha": ("sh / z", "ś (sh — palatal, as in 'sheet')"), "ssa": ("Sh / S", "ṣ (retroflex sh)"),
 "sa": ("s", "s (sit)"), "ha": ("h", "h (hat)"), "ksha": ("kSh / x", "kṣ (ksh)"),
}


def main():
    rom = {}
    L = ["# Varṇa ↔ English romanization (canonical, generated)", "",
         "> Generated by `gen_romanization.py`. One Devanāgarī, one IAST, an ASCII (ITRANS) form, and the",
         "> plain-English spelling per varṇa — so romanized input parses deterministically. **English",
         "> *words* should use g2p (pronunciation), which is least arbitrary; this table is for romanized /",
         "> explicit input.** Disambiguation: retroflex = ITRANS CAPITALS `T Th D Dh N` and `Sh`; English",
         "> long vowels `ee`→ī, `oo`→ū are honored; ambiguous English vowels (ai/ay, ow, ea) → use g2p or",
         "> `--varnas`.", "",
         "## Vowels", "| Devanāgarī | IAST | ASCII (ITRANS) | English | example |", "|---|---|---|---|---|"]
    for k, (deva, itr, eng, ex) in VOW.items():
        iast = V.VOW[k]["iast"].split(" ")[0]
        rom[k] = {"deva": deva, "iast": iast, "itrans": itr, "english": eng}
        L.append(f"| {deva} | {iast} | {itr} | {eng} | {ex} |")
    L += ["", "## Consonants", "| Devanāgarī | IAST | ASCII (ITRANS) | English | varga |", "|---|---|---|---|---|"]
    for k, (itr, eng) in CON.items():
        deva = V._VARGA[k][1]; iast = V.CONS[k]["iast"]; varga = V._VARGA[k][0]
        rom[k] = {"deva": deva, "iast": iast, "itrans": itr, "english": eng}
        L.append(f"| {deva} | {iast} | {itr} | {eng} | {varga} |")
    MDPATH.write_text("\n".join(L) + "\n", encoding="utf-8")

    data = json.loads(JPATH.read_text(encoding="utf-8"))
    data["_romanization"] = rom
    data["_romanization_note"] = ("Canonical varṇa ↔ Devanāgarī / IAST / ITRANS-ascii / English spelling. "
                                  "Reference for deterministic romanized input; English words use g2p. "
                                  "Long-vowel digraphs ee→ī, oo→ū are honored by the parser.")
    JPATH.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {MDPATH.name} and injected _romanization ({len(rom)} varṇas) into the JSON.")


if __name__ == "__main__":
    main()
