#!/usr/bin/env python3
"""Regenerate LEXICON.md from lexicon_authoritative.json (single source of truth).

Renders the corrected consonant + vowel tables and an expanded-properties appendix. Also backfills
`deva` and `varga` display fields into the JSON if missing (presentation metadata; not scoring).
"""
import json, pathlib

HERE = pathlib.Path(__file__).parent
JPATH = HERE / "lexicon_authoritative.json"
MDPATH = HERE / "LEXICON.md"

# key -> (devanāgarī, varga)  [presentation only]
DV = {
 "ka": ("क", "guttural · ka-varga"), "kha": ("ख", "guttural · ka-varga"),
 "ga": ("ग", "guttural · ka-varga"), "gha": ("घ", "guttural · ka-varga"), "nga": ("ङ", "guttural · ka-varga"),
 "ca": ("च", "palatal · ca-varga"), "cha": ("छ", "palatal · ca-varga"), "ja": ("ज", "palatal · ca-varga"),
 "jha": ("झ", "palatal · ca-varga"), "nya": ("ञ", "palatal · ca-varga"),
 "tta": ("ट", "RETROFLEX · Ṭa-varga"), "ttha": ("ठ", "RETROFLEX · Ṭa-varga"),
 "dda": ("ड", "RETROFLEX · Ṭa-varga"), "ddha": ("ढ", "RETROFLEX · Ṭa-varga"), "nna": ("ण", "RETROFLEX · Ṭa-varga"),
 "ta": ("त", "dental · ta-varga"), "tha": ("थ", "dental · ta-varga"), "da": ("द", "dental · ta-varga"),
 "dha": ("ध", "dental · ta-varga"), "na": ("न", "dental · ta-varga"),
 "pa": ("प", "labial · pa-varga"), "pha": ("फ", "labial · pa-varga"), "ba": ("ब", "labial · pa-varga"),
 "bha": ("भ", "labial · pa-varga"), "ma": ("म", "labial · pa-varga"),
 "ya": ("य", "semivowel · antaḥstha"), "ra": ("र", "semivowel · antaḥstha"),
 "la": ("ल", "semivowel · antaḥstha"), "va": ("व", "semivowel · antaḥstha"),
 "sha": ("श", "sibilant palatal · ūṣma"), "ssa": ("ष", "sibilant RETROFLEX · ūṣma"),
 "sa": ("स", "sibilant dental · ūṣma"), "ha": ("ह", "aspirate · ūṣma"), "ksha": ("क्ष", "compound"),
}


def main():
    data = json.loads(JPATH.read_text(encoding="utf-8"))
    cons = data["consonants"]
    changed = False
    for k, v in cons.items():
        if k in DV and ("deva" not in v or "varga" not in v):
            v["deva"], v["varga"] = DV[k]; changed = True
    if changed:
        JPATH.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    L = ["# Varṇa Lexicon — AUTHORITATIVE (generated from lexicon_authoritative.json)", "",
         "> **Generated by `gen_lexicon_md.py` — do not hand-edit; edit the JSON.** `positive` = liberating/",
         "> balance pole (the only fields, with `negative`, used for scoring). `negative` = binding/worldly",
         "> (bīja) pole. The reading uses ONLY positive/negative; everything under *Expanded properties* is",
         "> source literature (P.R. Sarkar, Varṇa Vijñāna) as **interpretive metadata**, never scoring.",
         "",
         "## How to write each letter (retroflex vs dental)",
         "Retroflex **Ṭa-varga** (ṭ ṭh ḍ ḍh ṇ) vs dental **ta-varga** (t th d dh n) are different sounds with",
         "different vṛttis. Write retroflex via diacritics (`ṭ ḍ ṇ ṣ`) or ITRANS capitals (`T D N Sh`); English",
         "g2p routes by sound (stops t/d/n → retroflex Ṭa/Ḍa/Ṇa; dental fricatives th → dental ta/da).",
         "",
         "## Consonants",
         "| Deva | IAST | Varga | positive (dissolved/spiritual) | negative (**worldly / bīja**) |",
         "|---|---|---|---|---|"]
    for k, v in cons.items():
        deva, varga = v.get("deva", ""), v.get("varga", "")
        L.append(f"| {deva} | {v['iast']} | {varga} | {v['positive']} | {v['negative']} |")

    L += ["", "## Vowels", "| Vowel | positive | negative |", "|---|---|---|"]
    for k, v in data["vowels"].items():
        L.append(f"| {v['iast']} | {v['positive']} | {v['negative']} |")

    L += ["", "## Expanded properties (source literature — interpretive metadata, NOT scoring)", ""]
    for k, v in cons.items():
        ep = v.get("expanded_properties")
        if not ep:
            continue
        vr = ep.get("vrtti", {})
        L.append(f"### {v['iast']}  ({v.get('deva','')})")
        if vr:
            L.append(f"- **vṛtti:** {vr.get('name','')} — {vr.get('english','')}"
                     + (f"  _({vr['type']})_" if vr.get("type") else ""))
        if ep.get("elemental"):
            L.append(f"- **elemental:** {ep['elemental']}")
        if ep.get("acoustic_roots"):
            L.append(f"- **acoustic roots:** {'; '.join(ep['acoustic_roots'])}")
        for fld, label in [("imagery", "imagery"), ("etymology", "etymology"), ("note", "note"),
                           ("history", "history"), ("mantra_note", "mantra")]:
            if ep.get(fld):
                L.append(f"- **{label}:** {ep[fld]}")
        if ep.get("semantic_extensions"):
            L.append(f"- **semantic extensions:** {'; '.join(ep['semantic_extensions'])}")
        if ep.get("deity_links"):
            L.append(f"- **deity links:** {'; '.join(ep['deity_links'])}")
        if ep.get("domain_tags"):
            L.append(f"- **tags:** {', '.join(ep['domain_tags'])}")
        if ep.get("source_quote"):
            L.append(f"- _source:_ \"{ep['source_quote']}\"")
        L.append("")
    MDPATH.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {MDPATH.name} ({len(cons)} consonants, {len(data['vowels'])} vowels)"
          + ("; backfilled deva/varga into JSON" if changed else ""))


if __name__ == "__main__":
    main()
